# Half-open intervals [Start, End), measured in integer minutes.

from peye import *

fact(interval('a', 600, 720))
fact(interval('b', 780, 900))
fact(interval('c', 720, 840))
fact(interval('d', 660, 780))
fact(interval('e', 600, 720))
fact(interval('f', 600, 660))
fact(interval('g', 660, 720))
fact(interval('h', 540, 960))
fact(start_duration('i', 960, 120))
fact(end_duration('j', 960, 60))
forward(interval(I, S, E), start_duration(I, S, D), D > 0, is_(E, S + D))
forward(interval(I, S, E), end_duration(I, E, D), D > 0, is_(S, E - D))
backward(valid_interval(I, S, E), interval(I, S, E), S < E)
backward(pair(I, J, SI, EI, SJ, EJ), valid_interval(I, SI, EI), valid_interval(J, SJ, EJ))
forward(relation(I, 'before', J), pair(I, J, SI, EI, SJ, EJ), EI < SJ)
forward(relation(I, 'meets', J), pair(I, J, SI, EI, SJ, EJ), eq(EI, SJ))
forward(relation(I, 'overlaps', J), pair(I, J, SI, EI, SJ, EJ), SI < SJ, SJ < EI, EI < EJ)
forward(relation(I, 'starts', J), pair(I, J, SI, EI, SJ, EJ), eq(SI, SJ), EI < EJ)
forward(relation(I, 'during', J), pair(I, J, SI, EI, SJ, EJ), SJ < SI, EI < EJ)
forward(relation(I, 'finishes', J), pair(I, J, SI, EI, SJ, EJ), SJ < SI, eq(EI, EJ))
forward(relation(I, 'equals', J), pair(I, J, SI, EI, SJ, EJ), eq(SI, SJ), eq(EI, EJ))
forward(relation(J, 'after', I), relation(I, 'before', J))
forward(relation(J, 'met_by', I), relation(I, 'meets', J))
forward(relation(J, 'overlapped_by', I), relation(I, 'overlaps', J))
forward(relation(J, 'started_by', I), relation(I, 'starts', J))
forward(relation(J, 'contains', I), relation(I, 'during', J))
forward(relation(J, 'finished_by', I), relation(I, 'finishes', J))
query(relation(I, Relation, J))
