route('paris', 'brussels')
route('paris', 'lille')
train('paris', 'brussels') | bus('paris', 'lille')
once(route('paris', 'brussels'))

clause(1, fact(train('paris', 'brussels')))
clause(2, fact(bus('paris', 'lille')))
clause(3, backward(route(From, To), train(From, To)))
clause(4, backward(route(From, To), bus(From, To)))

step(route('paris', 'brussels'), rule(3), {'From': 'paris', 'To': 'brussels'}, [train('paris', 'brussels')])
step(train('paris', 'brussels'), fact(1), {}, [])
step(route('paris', 'lille'), rule(4), {'From': 'paris', 'To': 'lille'}, [bus('paris', 'lille')])
step(bus('paris', 'lille'), fact(2), {}, [])
step(train('paris', 'brussels') | bus('paris', 'lille'), 'control', {}, [train('paris', 'brussels')])
step(once(route('paris', 'brussels')), 'control', {}, [route('paris', 'brussels')])
