verdict('checked_with_obligations')
at_risk(grant('cara'), income('cara', 1800))
at_risk(grant('dan'), income('dan', 2400))
at_risk(top_up('dan'), income('dan', 2400))
explanation(refused('bob', 'income above 2500'), [applicant('bob'), income('bob', 2900)], [])
explanation(grant('ann'), [applicant('ann'), income('ann', 2100)], [~already_received('ann')])
explanation(grant('cara'), [applicant('cara'), income('cara', 1800)], [~already_received('cara')])
explanation(grant('dan'), [applicant('dan'), income('dan', 2400)], [~already_received('dan')])
explanation(top_up('ann'), [household('ann', 4), applicant('ann'), income('ann', 2100)], [~already_received('ann')])
explanation(top_up('dan'), [household('dan', 3), applicant('dan'), income('dan', 2400)], [~already_received('dan')])

clause(17, fact(verdict('checked_with_obligations')))
clause(18, fact(decision(refused('bob', 'income above 2500'))))
clause(19, fact(decision(grant('ann'))))
clause(20, fact(decision(grant('cara'))))
clause(21, fact(decision(grant('dan'))))
clause(22, fact(decision(top_up('ann'))))
clause(23, fact(decision(top_up('dan'))))
clause(33, fact(step_of(grant('cara'), clause(17), [applicant('cara'), income('cara', 1800), 1800 < 2500, ~already_received('cara')])))
clause(35, fact(step_of(income('cara', 1800), clause(8), [])))
clause(38, fact(step_of(grant('dan'), clause(17), [applicant('dan'), income('dan', 2400), 2400 < 2500, ~already_received('dan')])))
clause(40, fact(step_of(income('dan', 2400), clause(11), [])))
clause(46, fact(step_of(top_up('dan'), clause(18), [grant('dan'), household('dan', 3), 3 >= 3])))
clause(51, fact(evidence_of(income('cara', 1800), 'self_declared')))
clause(52, fact(evidence_of(income('dan', 2400), 'self_declared')))
clause(54, fact(member(X, [X, *_0])))
clause(55, backward(member(X, [_0, *T]), member(X, T)))
clause(56, forward(depends(G, U), step_of(G, By, Uses), member(U, Uses)))
clause(57, forward(depends(G, W), depends(G, U), depends(U, W)))
clause(58, forward(rests_on(D, F), decision(D), depends(D, F), step_of(F, clause(_0), [])))
clause(61, forward(at_risk(D, F), rests_on(D, F), evidence_of(F, 'self_declared')))
clause(63, forward(explanation(D, Data, Assumptions), decision(D), findall(F, rests_on(D, F), Data), findall(A, assumes(D, A), Assumptions)))

step(verdict('checked_with_obligations'), clause(17), {}, [])
step(at_risk(grant('cara'), income('cara', 1800)), clause(61), {'D': grant('cara'), 'F': income('cara', 1800)}, [rests_on(grant('cara'), income('cara', 1800)), evidence_of(income('cara', 1800), 'self_declared')])
step(rests_on(grant('cara'), income('cara', 1800)), clause(58), {'D': grant('cara'), 'F': income('cara', 1800), '_0': 8}, [decision(grant('cara')), depends(grant('cara'), income('cara', 1800)), step_of(income('cara', 1800), clause(8), [])])
step(decision(grant('cara')), clause(20), {}, [])
step(depends(grant('cara'), income('cara', 1800)), clause(56), {'G': grant('cara'), 'U': income('cara', 1800), 'By': clause(17), 'Uses': [applicant('cara'), income('cara', 1800), 1800 < 2500, ~already_received('cara')]}, [step_of(grant('cara'), clause(17), [applicant('cara'), income('cara', 1800), 1800 < 2500, ~already_received('cara')]), member(income('cara', 1800), [applicant('cara'), income('cara', 1800), 1800 < 2500, ~already_received('cara')])])
step(step_of(grant('cara'), clause(17), [applicant('cara'), income('cara', 1800), 1800 < 2500, ~already_received('cara')]), clause(33), {}, [])
step(member(income('cara', 1800), [applicant('cara'), income('cara', 1800), 1800 < 2500, ~already_received('cara')]), clause(55), {'X': income('cara', 1800), '_0': applicant('cara'), 'T': [income('cara', 1800), 1800 < 2500, ~already_received('cara')]}, [member(income('cara', 1800), [income('cara', 1800), 1800 < 2500, ~already_received('cara')])])
step(member(income('cara', 1800), [income('cara', 1800), 1800 < 2500, ~already_received('cara')]), clause(54), {'X': income('cara', 1800), '_0': [1800 < 2500, ~already_received('cara')]}, [])
step(step_of(income('cara', 1800), clause(8), []), clause(35), {}, [])
step(evidence_of(income('cara', 1800), 'self_declared'), clause(51), {}, [])
step(at_risk(grant('dan'), income('dan', 2400)), clause(61), {'D': grant('dan'), 'F': income('dan', 2400)}, [rests_on(grant('dan'), income('dan', 2400)), evidence_of(income('dan', 2400), 'self_declared')])
step(rests_on(grant('dan'), income('dan', 2400)), clause(58), {'D': grant('dan'), 'F': income('dan', 2400), '_0': 11}, [decision(grant('dan')), depends(grant('dan'), income('dan', 2400)), step_of(income('dan', 2400), clause(11), [])])
step(decision(grant('dan')), clause(21), {}, [])
step(depends(grant('dan'), income('dan', 2400)), clause(56), {'G': grant('dan'), 'U': income('dan', 2400), 'By': clause(17), 'Uses': [applicant('dan'), income('dan', 2400), 2400 < 2500, ~already_received('dan')]}, [step_of(grant('dan'), clause(17), [applicant('dan'), income('dan', 2400), 2400 < 2500, ~already_received('dan')]), member(income('dan', 2400), [applicant('dan'), income('dan', 2400), 2400 < 2500, ~already_received('dan')])])
step(step_of(grant('dan'), clause(17), [applicant('dan'), income('dan', 2400), 2400 < 2500, ~already_received('dan')]), clause(38), {}, [])
step(member(income('dan', 2400), [applicant('dan'), income('dan', 2400), 2400 < 2500, ~already_received('dan')]), clause(55), {'X': income('dan', 2400), '_0': applicant('dan'), 'T': [income('dan', 2400), 2400 < 2500, ~already_received('dan')]}, [member(income('dan', 2400), [income('dan', 2400), 2400 < 2500, ~already_received('dan')])])
step(member(income('dan', 2400), [income('dan', 2400), 2400 < 2500, ~already_received('dan')]), clause(54), {'X': income('dan', 2400), '_0': [2400 < 2500, ~already_received('dan')]}, [])
step(step_of(income('dan', 2400), clause(11), []), clause(40), {}, [])
step(evidence_of(income('dan', 2400), 'self_declared'), clause(52), {}, [])
step(at_risk(top_up('dan'), income('dan', 2400)), clause(61), {'D': top_up('dan'), 'F': income('dan', 2400)}, [rests_on(top_up('dan'), income('dan', 2400)), evidence_of(income('dan', 2400), 'self_declared')])
step(rests_on(top_up('dan'), income('dan', 2400)), clause(58), {'D': top_up('dan'), 'F': income('dan', 2400), '_0': 11}, [decision(top_up('dan')), depends(top_up('dan'), income('dan', 2400)), step_of(income('dan', 2400), clause(11), [])])
step(decision(top_up('dan')), clause(23), {}, [])
step(depends(top_up('dan'), income('dan', 2400)), clause(57), {'G': top_up('dan'), 'W': income('dan', 2400), 'U': grant('dan')}, [depends(top_up('dan'), grant('dan')), depends(grant('dan'), income('dan', 2400))])
step(depends(top_up('dan'), grant('dan')), clause(56), {'G': top_up('dan'), 'U': grant('dan'), 'By': clause(18), 'Uses': [grant('dan'), household('dan', 3), 3 >= 3]}, [step_of(top_up('dan'), clause(18), [grant('dan'), household('dan', 3), 3 >= 3]), member(grant('dan'), [grant('dan'), household('dan', 3), 3 >= 3])])
step(step_of(top_up('dan'), clause(18), [grant('dan'), household('dan', 3), 3 >= 3]), clause(46), {}, [])
step(member(grant('dan'), [grant('dan'), household('dan', 3), 3 >= 3]), clause(54), {'X': grant('dan'), '_0': [household('dan', 3), 3 >= 3]}, [])
step(explanation(refused('bob', 'income above 2500'), [applicant('bob'), income('bob', 2900)], []), clause(63), {'D': refused('bob', 'income above 2500'), 'Data': [applicant('bob'), income('bob', 2900)], 'Assumptions': [], 'F': A, 'A': B}, [decision(refused('bob', 'income above 2500')), findall(A, rests_on(refused('bob', 'income above 2500'), A), [applicant('bob'), income('bob', 2900)]), findall(B, assumes(refused('bob', 'income above 2500'), B), [])])
step(decision(refused('bob', 'income above 2500')), clause(18), {}, [])
step(findall(A, rests_on(refused('bob', 'income above 2500'), A), [applicant('bob'), income('bob', 2900)]), 'collected', {}, [])
step(findall(B, assumes(refused('bob', 'income above 2500'), B), []), 'collected', {}, [])
step(explanation(grant('ann'), [applicant('ann'), income('ann', 2100)], [~already_received('ann')]), clause(63), {'D': grant('ann'), 'Data': [applicant('ann'), income('ann', 2100)], 'Assumptions': [~already_received('ann')], 'F': A, 'A': B}, [decision(grant('ann')), findall(A, rests_on(grant('ann'), A), [applicant('ann'), income('ann', 2100)]), findall(B, assumes(grant('ann'), B), [~already_received('ann')])])
step(decision(grant('ann')), clause(19), {}, [])
step(findall(A, rests_on(grant('ann'), A), [applicant('ann'), income('ann', 2100)]), 'collected', {}, [])
step(findall(B, assumes(grant('ann'), B), [~already_received('ann')]), 'collected', {}, [])
step(explanation(grant('cara'), [applicant('cara'), income('cara', 1800)], [~already_received('cara')]), clause(63), {'D': grant('cara'), 'Data': [applicant('cara'), income('cara', 1800)], 'Assumptions': [~already_received('cara')], 'F': A, 'A': B}, [decision(grant('cara')), findall(A, rests_on(grant('cara'), A), [applicant('cara'), income('cara', 1800)]), findall(B, assumes(grant('cara'), B), [~already_received('cara')])])
step(findall(A, rests_on(grant('cara'), A), [applicant('cara'), income('cara', 1800)]), 'collected', {}, [])
step(findall(B, assumes(grant('cara'), B), [~already_received('cara')]), 'collected', {}, [])
step(explanation(grant('dan'), [applicant('dan'), income('dan', 2400)], [~already_received('dan')]), clause(63), {'D': grant('dan'), 'Data': [applicant('dan'), income('dan', 2400)], 'Assumptions': [~already_received('dan')], 'F': A, 'A': B}, [decision(grant('dan')), findall(A, rests_on(grant('dan'), A), [applicant('dan'), income('dan', 2400)]), findall(B, assumes(grant('dan'), B), [~already_received('dan')])])
step(findall(A, rests_on(grant('dan'), A), [applicant('dan'), income('dan', 2400)]), 'collected', {}, [])
step(findall(B, assumes(grant('dan'), B), [~already_received('dan')]), 'collected', {}, [])
step(explanation(top_up('ann'), [household('ann', 4), applicant('ann'), income('ann', 2100)], [~already_received('ann')]), clause(63), {'D': top_up('ann'), 'Data': [household('ann', 4), applicant('ann'), income('ann', 2100)], 'Assumptions': [~already_received('ann')], 'F': A, 'A': B}, [decision(top_up('ann')), findall(A, rests_on(top_up('ann'), A), [household('ann', 4), applicant('ann'), income('ann', 2100)]), findall(B, assumes(top_up('ann'), B), [~already_received('ann')])])
step(decision(top_up('ann')), clause(22), {}, [])
step(findall(A, rests_on(top_up('ann'), A), [household('ann', 4), applicant('ann'), income('ann', 2100)]), 'collected', {}, [])
step(findall(B, assumes(top_up('ann'), B), [~already_received('ann')]), 'collected', {}, [])
step(explanation(top_up('dan'), [household('dan', 3), applicant('dan'), income('dan', 2400)], [~already_received('dan')]), clause(63), {'D': top_up('dan'), 'Data': [household('dan', 3), applicant('dan'), income('dan', 2400)], 'Assumptions': [~already_received('dan')], 'F': A, 'A': B}, [decision(top_up('dan')), findall(A, rests_on(top_up('dan'), A), [household('dan', 3), applicant('dan'), income('dan', 2400)]), findall(B, assumes(top_up('dan'), B), [~already_received('dan')])])
step(findall(A, rests_on(top_up('dan'), A), [household('dan', 3), applicant('dan'), income('dan', 2400)]), 'collected', {}, [])
step(findall(B, assumes(top_up('dan'), B), [~already_received('dan')]), 'collected', {}, [])
