witness('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')))
models('agatha', 4)
models('butler', 0)
models('charles', 0)
entailed(killed('agatha', 'agatha'))

clause(1, backward(model(Killer, world(Richer, Hates)), unify(Richer, richer(RA, RB, RC)), unify(Hates, hates(AA, AB, AC, BA, BB, BC, CA, CB, CC)), resident(Killer), hates(Hates, Killer, 'agatha', 'yes'), richer(Richer, Killer, 'no'), implies_not(AA, CA), implies_not(AB, CB), implies_not(AC, CC), unify(AA, 'yes'), unify(AC, 'yes'), unless(RA, BA), unless(RB, BB), unless(RC, BC), implies(AA, BA), implies(AB, BB), implies(AC, BC), label([RA, RB, RC, AA, AB, AC, BA, BB, BC, CA, CB, CC]), some_no(AA, AB, AC), some_no(BA, BB, BC), some_no(CA, CB, CC)))
clause(2, fact(resident('agatha')))
clause(3, fact(resident('butler')))
clause(4, fact(resident('charles')))
clause(5, fact(hates(hates(V, _0, _1, _2, _3, _4, _5, _6, _7), 'agatha', 'agatha', V)))
clause(14, fact(richer(richer(V, _0, _1), 'agatha', V)))
clause(17, fact(truth('yes')))
clause(18, fact(truth('no')))
clause(19, fact(label([])))
clause(20, backward(label([V, *Vs]), truth(V), label(Vs)))
clause(21, fact(implies('no', _0)))
clause(22, fact(implies('yes', 'yes')))
clause(23, fact(implies_not('no', _0)))
clause(24, fact(implies_not('yes', 'no')))
clause(25, fact(unless('yes', _0)))
clause(26, fact(unless('no', 'yes')))
clause(27, fact(some_no('no', _0, _1)))
clause(28, fact(some_no('yes', 'no', _0)))
clause(30, fact(count([], 0)))
clause(31, backward(count([_0, *Xs], N), count(Xs, M), is_(N, M + 1)))
clause(32, forward(models(Suspect, N), resident(Suspect), findall(W, model(Suspect, W), Ws), count(Ws, N)))
clause(33, forward(entailed(killed('agatha', 'agatha')), models('agatha', N), N > 0, models('butler', 0), models('charles', 0)))
clause(34, forward(witness(Killer, W), once(model(Killer, W))))

step(witness('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))), clause(34), {'Killer': 'agatha', 'W': world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))}, [once(model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))))])
step(once(model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')))), 'control', {}, [model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')))])
step(model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))), clause(1), {'Killer': 'agatha', 'Richer': richer('no', 'yes', 'yes'), 'Hates': hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), 'RA': 'no', 'RB': 'yes', 'RC': 'yes', 'AA': 'yes', 'AB': 'no', 'AC': 'yes', 'BA': 'yes', 'BB': 'no', 'BC': 'yes', 'CA': 'no', 'CB': 'yes', 'CC': 'no'}, [unify(richer('no', 'yes', 'yes'), richer('no', 'yes', 'yes')), unify(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), resident('agatha'), hates(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), 'agatha', 'agatha', 'yes'), richer(richer('no', 'yes', 'yes'), 'agatha', 'no'), implies_not('yes', 'no'), implies_not('no', 'yes'), implies_not('yes', 'no'), unify('yes', 'yes'), unify('yes', 'yes'), unless('no', 'yes'), unless('yes', 'no'), unless('yes', 'yes'), implies('yes', 'yes'), implies('no', 'no'), implies('yes', 'yes'), label(['no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), some_no('yes', 'no', 'yes'), some_no('yes', 'no', 'yes'), some_no('no', 'yes', 'no')])
step(unify(richer('no', 'yes', 'yes'), richer('no', 'yes', 'yes')), 'builtin', {}, [])
step(unify(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), 'builtin', {}, [])
step(resident('agatha'), clause(2), {}, [])
step(hates(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), 'agatha', 'agatha', 'yes'), clause(5), {'V': 'yes', '_0': 'no', '_1': 'yes', '_2': 'yes', '_3': 'no', '_4': 'yes', '_5': 'no', '_6': 'yes', '_7': 'no'}, [])
step(richer(richer('no', 'yes', 'yes'), 'agatha', 'no'), clause(14), {'V': 'no', '_0': 'yes', '_1': 'yes'}, [])
step(implies_not('yes', 'no'), clause(24), {}, [])
step(implies_not('no', 'yes'), clause(23), {'_0': 'yes'}, [])
step(unify('yes', 'yes'), 'builtin', {}, [])
step(unless('no', 'yes'), clause(26), {}, [])
step(unless('yes', 'no'), clause(25), {'_0': 'no'}, [])
step(unless('yes', 'yes'), clause(25), {'_0': 'yes'}, [])
step(implies('yes', 'yes'), clause(22), {}, [])
step(implies('no', 'no'), clause(21), {'_0': 'no'}, [])
step(label(['no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'no', 'Vs': ['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('no'), label(['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(truth('no'), clause(18), {}, [])
step(label(['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(truth('yes'), clause(17), {}, [])
step(label(['yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'no', 'Vs': ['yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('no'), label(['yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['yes', 'no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['no', 'yes', 'no', 'yes', 'no'])])
step(label(['no', 'yes', 'no', 'yes', 'no']), clause(20), {'V': 'no', 'Vs': ['yes', 'no', 'yes', 'no']}, [truth('no'), label(['yes', 'no', 'yes', 'no'])])
step(label(['yes', 'no', 'yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['no', 'yes', 'no']}, [truth('yes'), label(['no', 'yes', 'no'])])
step(label(['no', 'yes', 'no']), clause(20), {'V': 'no', 'Vs': ['yes', 'no']}, [truth('no'), label(['yes', 'no'])])
step(label(['yes', 'no']), clause(20), {'V': 'yes', 'Vs': ['no']}, [truth('yes'), label(['no'])])
step(label(['no']), clause(20), {'V': 'no', 'Vs': []}, [truth('no'), label([])])
step(label([]), clause(19), {}, [])
step(some_no('yes', 'no', 'yes'), clause(28), {'_0': 'yes'}, [])
step(some_no('no', 'yes', 'no'), clause(27), {'_0': 'yes', '_1': 'no'}, [])
step(models('agatha', 4), clause(32), {'Suspect': 'agatha', 'N': 4, 'W': A, 'Ws': [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))]}, [resident('agatha'), findall(A, model('agatha', A), [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))]), count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 4)])
step(findall(A, model('agatha', A), [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))]), 'collected', {}, [])
step(count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 4), clause(31), {'_0': world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), 'Xs': [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 'N': 4, 'M': 3}, [count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 3), is_(4, 3 + 1)])
step(count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 3), clause(31), {'_0': world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), 'Xs': [world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 'N': 3, 'M': 2}, [count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 2), is_(3, 2 + 1)])
step(count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 2), clause(31), {'_0': world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), 'Xs': [world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 'N': 2, 'M': 1}, [count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 1), is_(2, 1 + 1)])
step(count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 1), clause(31), {'_0': world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), 'Xs': [], 'N': 1, 'M': 0}, [count([], 0), is_(1, 0 + 1)])
step(count([], 0), clause(30), {}, [])
step(is_(1, 0 + 1), 'builtin', {}, [])
step(is_(2, 1 + 1), 'builtin', {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(is_(4, 3 + 1), 'builtin', {}, [])
step(models('butler', 0), clause(32), {'Suspect': 'butler', 'N': 0, 'W': A, 'Ws': []}, [resident('butler'), findall(A, model('butler', A), []), count([], 0)])
step(resident('butler'), clause(3), {}, [])
step(findall(A, model('butler', A), []), 'collected', {}, [])
step(models('charles', 0), clause(32), {'Suspect': 'charles', 'N': 0, 'W': A, 'Ws': []}, [resident('charles'), findall(A, model('charles', A), []), count([], 0)])
step(resident('charles'), clause(4), {}, [])
step(findall(A, model('charles', A), []), 'collected', {}, [])
step(entailed(killed('agatha', 'agatha')), clause(33), {'N': 4}, [models('agatha', 4), 4 > 0, models('butler', 0), models('charles', 0)])
step(4 > 0, 'builtin', {}, [])
