witness('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')))
models('agatha', 4)
models('butler', 0)
models('charles', 0)
entailed(killed('agatha', 'agatha'))

clause(1, backward(model(Killer, world(Richer, Hates)), unify(Richer, richer(RA, RB, RC)), unify(Hates, hates(AA, AB, AC, BA, BB, BC, CA, CB, CC)), resident(Killer), hates(Hates, Killer, 'agatha', 'yes'), richer(Richer, Killer, 'no'), implies_not(AA, CA), implies_not(AB, CB), implies_not(AC, CC), unify(AA, 'yes'), unify(AC, 'yes'), unless(RA, BA), unless(RB, BB), unless(RC, BC), implies(AA, BA), implies(AB, BB), implies(AC, BC), label([RA, RB, RC, AA, AB, AC, BA, BB, BC, CA, CB, CC]), some_no(AA, AB, AC), some_no(BA, BB, BC), some_no(CA, CB, CC)))
clause(2, fact(resident('agatha')))
clause(3, fact(resident('butler')))
clause(4, fact(resident('charles')))
clause(5, fact(hates(hates(V, __anon0, __anon1, __anon2, __anon3, __anon4, __anon5, __anon6, __anon7), 'agatha', 'agatha', V)))
clause(14, fact(richer(richer(V, __anon72, __anon73), 'agatha', V)))
clause(17, fact(truth('yes')))
clause(18, fact(truth('no')))
clause(19, fact(label([])))
clause(20, backward(label([V, *Vs]), truth(V), label(Vs)))
clause(21, fact(implies('no', __anon78)))
clause(22, fact(implies('yes', 'yes')))
clause(23, fact(implies_not('no', __anon79)))
clause(24, fact(implies_not('yes', 'no')))
clause(25, fact(unless('yes', __anon80)))
clause(26, fact(unless('no', 'yes')))
clause(27, fact(some_no('no', __anon81, __anon82)))
clause(28, fact(some_no('yes', 'no', __anon83)))
clause(30, fact(count([], 0)))
clause(31, backward(count([__anon84, *Xs], N), count(Xs, M), is_(N, M + 1)))
clause(32, forward(models(Suspect, N), resident(Suspect), findall(W, model(Suspect, W), Ws), count(Ws, N)))
clause(33, forward(entailed(killed('agatha', 'agatha')), models('agatha', N), N > 0, models('butler', 0), models('charles', 0)))
clause(34, forward(witness(Killer, W), once(model(Killer, W))))

step(witness('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))), rule(34), {'Killer': 'agatha', 'W': world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))}, [once(model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))))])
step(once(model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')))), 'control', {}, [model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')))])
step(model('agatha', world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'))), rule(1), {'Killer': 'agatha', 'Richer': richer('no', 'yes', 'yes'), 'Hates': hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), 'RA': 'no', 'RB': 'yes', 'RC': 'yes', 'AA': 'yes', 'AB': 'no', 'AC': 'yes', 'BA': 'yes', 'BB': 'no', 'BC': 'yes', 'CA': 'no', 'CB': 'yes', 'CC': 'no'}, [unify(richer('no', 'yes', 'yes'), richer('no', 'yes', 'yes')), unify(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), resident('agatha'), hates(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), 'agatha', 'agatha', 'yes'), richer(richer('no', 'yes', 'yes'), 'agatha', 'no'), implies_not('yes', 'no'), implies_not('no', 'yes'), implies_not('yes', 'no'), unify('yes', 'yes'), unify('yes', 'yes'), unless('no', 'yes'), unless('yes', 'no'), unless('yes', 'yes'), implies('yes', 'yes'), implies('no', 'no'), implies('yes', 'yes'), label(['no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), some_no('yes', 'no', 'yes'), some_no('yes', 'no', 'yes'), some_no('no', 'yes', 'no')])
step(unify(richer('no', 'yes', 'yes'), richer('no', 'yes', 'yes')), 'builtin', {}, [])
step(unify(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), 'builtin', {}, [])
step(resident('agatha'), fact(2), {}, [])
step(hates(hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'), 'agatha', 'agatha', 'yes'), fact(5), {'V': 'yes', '__anon0': 'no', '__anon1': 'yes', '__anon2': 'yes', '__anon3': 'no', '__anon4': 'yes', '__anon5': 'no', '__anon6': 'yes', '__anon7': 'no'}, [])
step(richer(richer('no', 'yes', 'yes'), 'agatha', 'no'), fact(14), {'V': 'no', '__anon72': 'yes', '__anon73': 'yes'}, [])
step(implies_not('yes', 'no'), fact(24), {}, [])
step(implies_not('no', 'yes'), fact(23), {'__anon79': 'yes'}, [])
step(unify('yes', 'yes'), 'builtin', {}, [])
step(unless('no', 'yes'), fact(26), {}, [])
step(unless('yes', 'no'), fact(25), {'__anon80': 'no'}, [])
step(unless('yes', 'yes'), fact(25), {'__anon80': 'yes'}, [])
step(implies('yes', 'yes'), fact(22), {}, [])
step(implies('no', 'no'), fact(21), {'__anon78': 'no'}, [])
step(label(['no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'no', 'Vs': ['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('no'), label(['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(truth('no'), fact(18), {}, [])
step(label(['yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(truth('yes'), fact(17), {}, [])
step(label(['yes', 'yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'no', 'Vs': ['yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('no'), label(['yes', 'yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['yes', 'yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['yes', 'no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['yes', 'no', 'yes', 'no', 'yes', 'no'])])
step(label(['yes', 'no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['no', 'yes', 'no', 'yes', 'no']}, [truth('yes'), label(['no', 'yes', 'no', 'yes', 'no'])])
step(label(['no', 'yes', 'no', 'yes', 'no']), rule(20), {'V': 'no', 'Vs': ['yes', 'no', 'yes', 'no']}, [truth('no'), label(['yes', 'no', 'yes', 'no'])])
step(label(['yes', 'no', 'yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['no', 'yes', 'no']}, [truth('yes'), label(['no', 'yes', 'no'])])
step(label(['no', 'yes', 'no']), rule(20), {'V': 'no', 'Vs': ['yes', 'no']}, [truth('no'), label(['yes', 'no'])])
step(label(['yes', 'no']), rule(20), {'V': 'yes', 'Vs': ['no']}, [truth('yes'), label(['no'])])
step(label(['no']), rule(20), {'V': 'no', 'Vs': []}, [truth('no'), label([])])
step(label([]), fact(19), {}, [])
step(some_no('yes', 'no', 'yes'), fact(28), {'__anon83': 'yes'}, [])
step(some_no('no', 'yes', 'no'), fact(27), {'__anon81': 'yes', '__anon82': 'no'}, [])
step(models('agatha', 4), rule(32), {'Suspect': 'agatha', 'N': 4, 'W': EYE_W_23_169, 'Ws': [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))]}, [resident('agatha'), findall(EYE_W_23_169, model('agatha', EYE_W_23_169), [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))]), count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 4)])
step(findall(EYE_W_23_169, model('agatha', EYE_W_23_169), [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))]), 'collected', {}, [])
step(count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 4), rule(31), {'__anon84': world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), 'Xs': [world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 'N': 4, 'M': 3}, [count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 3), is_(4, 3 + 1)])
step(count([world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 3), rule(31), {'__anon84': world(richer('no', 'yes', 'yes'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), 'Xs': [world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 'N': 3, 'M': 2}, [count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 2), is_(3, 2 + 1)])
step(count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 2), rule(31), {'__anon84': world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'no')), 'Xs': [world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 'N': 2, 'M': 1}, [count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 1), is_(2, 1 + 1)])
step(count([world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no'))], 1), rule(31), {'__anon84': world(richer('no', 'yes', 'no'), hates('yes', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'no', 'no')), 'Xs': [], 'N': 1, 'M': 0}, [count([], 0), is_(1, 0 + 1)])
step(count([], 0), fact(30), {}, [])
step(is_(1, 0 + 1), 'builtin', {}, [])
step(is_(2, 1 + 1), 'builtin', {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(is_(4, 3 + 1), 'builtin', {}, [])
step(models('butler', 0), rule(32), {'Suspect': 'butler', 'N': 0, 'W': EYE_W_23_169, 'Ws': []}, [resident('butler'), findall(EYE_W_23_169, model('butler', EYE_W_23_169), []), count([], 0)])
step(resident('butler'), fact(3), {}, [])
step(findall(EYE_W_23_169, model('butler', EYE_W_23_169), []), 'collected', {}, [])
step(models('charles', 0), rule(32), {'Suspect': 'charles', 'N': 0, 'W': EYE_W_23_169, 'Ws': []}, [resident('charles'), findall(EYE_W_23_169, model('charles', EYE_W_23_169), []), count([], 0)])
step(resident('charles'), fact(4), {}, [])
step(findall(EYE_W_23_169, model('charles', EYE_W_23_169), []), 'collected', {}, [])
step(entailed(killed('agatha', 'agatha')), rule(33), {'N': 4}, [models('agatha', 4), 4 > 0, models('butler', 0), models('charles', 0)])
step(4 > 0, 'builtin', {}, [])
