analysis('value_transparency', "knowing that and how one's data creates value, including in AI training", 'by interpretation', ['GDPR art. 13-15', 'AI Act art. 53(1)(d)'])
analysis('use_control', "deciding on the uses through which one's data creates value", 'by interpretation', ['GDPR art. 7(3)', 'GDPR art. 21'])
analysis('value_mobility', "taking one's data elsewhere, to have value created there", 'by interpretation', ['GDPR art. 20', 'DMA art. 6(9)'])
analysis('value_recognition', 'the law acknowledging that personal data has economic value', 'in existing law', ['Directive 2019/770 art. 3(1)'])
analysis('collective_exercise', 'exercising the right together, through an intermediary', 'by interpretation', ['DGA ch. III'])
analysis('individual_enforcement', 'enforcing the right oneself, before a court', 'in existing law', ['GDPR art. 79 and 82'])
analysis('value_share', "receiving a share of the value one's data creates", 'needs an autonomous right', [])
evaluation('interpret_existing_law', ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement'], [unaddressed('value_share')])
evaluation('extend_portability', ['value_mobility', 'value_transparency'], [unaddressed('use_control'), unaddressed('collective_exercise'), unaddressed('value_share')])
evaluation('data_dividend', ['value_share', 'collective_exercise'], [unaddressed('value_transparency'), unaddressed('use_control'), unaddressed('value_mobility'), 'gives the data subject no claim of their own'])
evaluation('data_ownership', ['value_share', 'use_control', 'value_mobility', 'individual_enforcement'], ['treats personal data as a commodity', unaddressed('value_transparency'), unaddressed('collective_exercise')])
evaluation('autonomous_right', ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement', 'value_share'], [])
recommended('autonomous_right')

clause(1, fact(component('value_transparency', "knowing that and how one's data creates value, including in AI training")))
clause(2, fact(component('use_control', "deciding on the uses through which one's data creates value")))
clause(3, fact(component('value_mobility', "taking one's data elsewhere, to have value created there")))
clause(4, fact(component('value_recognition', 'the law acknowledging that personal data has economic value')))
clause(5, fact(component('collective_exercise', 'exercising the right together, through an intermediary')))
clause(6, fact(component('individual_enforcement', 'enforcing the right oneself, before a court')))
clause(7, fact(component('value_share', "receiving a share of the value one's data creates")))
clause(8, fact(anchor('GDPR art. 13-15', 'value_transparency', 'partial', 'information on purposes and recipients, not on the value created')))
clause(10, fact(anchor('GDPR art. 7(3)', 'use_control', 'partial', 'consent can be withdrawn at any time, where processing rests on consent')))
clause(12, fact(anchor('GDPR art. 20', 'value_mobility', 'partial', 'portability of data the data subject provided, on consent or contract')))
clause(14, fact(anchor('Directive 2019/770 art. 3(1)', 'value_recognition', 'full', 'personal data recognized as what a consumer may provide in exchange for digital content')))
clause(15, fact(anchor('DGA ch. III', 'collective_exercise', 'partial', 'data intermediation services, without bargaining over value')))
clause(16, fact(anchor('GDPR art. 79 and 82', 'individual_enforcement', 'full', 'a judicial remedy and compensation for the data subject')))
clause(17, fact(option('interpret_existing_law', 'right')))
clause(18, fact(option('extend_portability', 'right')))
clause(21, fact(option('data_dividend', 'levy')))
clause(24, fact(option('data_ownership', 'property')))
clause(29, fact(option('autonomous_right', 'inalienable_right')))
clause(41, forward(anchored(C), anchor(P, C, D, W)))
clause(42, forward(fully_anchored(C), anchor(P, C, 'full', W)))
clause(43, forward(gap(C), component(C, Description), ~anchored(C)))
clause(44, forward(fit(C, 'in existing law'), fully_anchored(C)))
clause(45, forward(fit(C, 'by interpretation'), anchored(C), ~fully_anchored(C)))
clause(46, forward(fit(C, 'needs an autonomous right'), gap(C)))
clause(47, forward(analysis(C, Meaning, How, Provisions), component(C, Meaning), fit(C, How), findall(P, anchor(P, C, D, W), Provisions)))
clause(55, forward(recommended(O), option(O, F), ~objectionable(O)))
clause(56, forward(evaluation(O, Delivered, Objections), option(O, F), findall(C, delivers(O, C), Delivered), findall(Why, objection(O, Why), Objections)))

step(analysis('value_transparency', "knowing that and how one's data creates value, including in AI training", 'by interpretation', ['GDPR art. 13-15', 'AI Act art. 53(1)(d)']), rule(47), {'C': 'value_transparency', 'Meaning': "knowing that and how one's data creates value, including in AI training", 'How': 'by interpretation', 'Provisions': ['GDPR art. 13-15', 'AI Act art. 53(1)(d)'], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('value_transparency', "knowing that and how one's data creates value, including in AI training"), fit('value_transparency', 'by interpretation'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_transparency', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 13-15', 'AI Act art. 53(1)(d)'])])
step(component('value_transparency', "knowing that and how one's data creates value, including in AI training"), fact(1), {}, [])
step(fit('value_transparency', 'by interpretation'), rule(45), {'C': 'value_transparency'}, [anchored('value_transparency'), ~fully_anchored('value_transparency')])
step(anchored('value_transparency'), rule(41), {'C': 'value_transparency', 'P': 'GDPR art. 13-15', 'D': 'partial', 'W': 'information on purposes and recipients, not on the value created'}, [anchor('GDPR art. 13-15', 'value_transparency', 'partial', 'information on purposes and recipients, not on the value created')])
step(anchor('GDPR art. 13-15', 'value_transparency', 'partial', 'information on purposes and recipients, not on the value created'), fact(8), {}, [])
step(~fully_anchored('value_transparency'), 'absent', {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_transparency', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 13-15', 'AI Act art. 53(1)(d)']), 'collected', {}, [])
step(analysis('use_control', "deciding on the uses through which one's data creates value", 'by interpretation', ['GDPR art. 7(3)', 'GDPR art. 21']), rule(47), {'C': 'use_control', 'Meaning': "deciding on the uses through which one's data creates value", 'How': 'by interpretation', 'Provisions': ['GDPR art. 7(3)', 'GDPR art. 21'], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('use_control', "deciding on the uses through which one's data creates value"), fit('use_control', 'by interpretation'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'use_control', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 7(3)', 'GDPR art. 21'])])
step(component('use_control', "deciding on the uses through which one's data creates value"), fact(2), {}, [])
step(fit('use_control', 'by interpretation'), rule(45), {'C': 'use_control'}, [anchored('use_control'), ~fully_anchored('use_control')])
step(anchored('use_control'), rule(41), {'C': 'use_control', 'P': 'GDPR art. 7(3)', 'D': 'partial', 'W': 'consent can be withdrawn at any time, where processing rests on consent'}, [anchor('GDPR art. 7(3)', 'use_control', 'partial', 'consent can be withdrawn at any time, where processing rests on consent')])
step(anchor('GDPR art. 7(3)', 'use_control', 'partial', 'consent can be withdrawn at any time, where processing rests on consent'), fact(10), {}, [])
step(~fully_anchored('use_control'), 'absent', {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'use_control', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 7(3)', 'GDPR art. 21']), 'collected', {}, [])
step(analysis('value_mobility', "taking one's data elsewhere, to have value created there", 'by interpretation', ['GDPR art. 20', 'DMA art. 6(9)']), rule(47), {'C': 'value_mobility', 'Meaning': "taking one's data elsewhere, to have value created there", 'How': 'by interpretation', 'Provisions': ['GDPR art. 20', 'DMA art. 6(9)'], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('value_mobility', "taking one's data elsewhere, to have value created there"), fit('value_mobility', 'by interpretation'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_mobility', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 20', 'DMA art. 6(9)'])])
step(component('value_mobility', "taking one's data elsewhere, to have value created there"), fact(3), {}, [])
step(fit('value_mobility', 'by interpretation'), rule(45), {'C': 'value_mobility'}, [anchored('value_mobility'), ~fully_anchored('value_mobility')])
step(anchored('value_mobility'), rule(41), {'C': 'value_mobility', 'P': 'GDPR art. 20', 'D': 'partial', 'W': 'portability of data the data subject provided, on consent or contract'}, [anchor('GDPR art. 20', 'value_mobility', 'partial', 'portability of data the data subject provided, on consent or contract')])
step(anchor('GDPR art. 20', 'value_mobility', 'partial', 'portability of data the data subject provided, on consent or contract'), fact(12), {}, [])
step(~fully_anchored('value_mobility'), 'absent', {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_mobility', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 20', 'DMA art. 6(9)']), 'collected', {}, [])
step(analysis('value_recognition', 'the law acknowledging that personal data has economic value', 'in existing law', ['Directive 2019/770 art. 3(1)']), rule(47), {'C': 'value_recognition', 'Meaning': 'the law acknowledging that personal data has economic value', 'How': 'in existing law', 'Provisions': ['Directive 2019/770 art. 3(1)'], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('value_recognition', 'the law acknowledging that personal data has economic value'), fit('value_recognition', 'in existing law'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_recognition', EYE_D_23_55, EYE_W_23_55), ['Directive 2019/770 art. 3(1)'])])
step(component('value_recognition', 'the law acknowledging that personal data has economic value'), fact(4), {}, [])
step(fit('value_recognition', 'in existing law'), rule(44), {'C': 'value_recognition'}, [fully_anchored('value_recognition')])
step(fully_anchored('value_recognition'), rule(42), {'C': 'value_recognition', 'P': 'Directive 2019/770 art. 3(1)', 'W': 'personal data recognized as what a consumer may provide in exchange for digital content'}, [anchor('Directive 2019/770 art. 3(1)', 'value_recognition', 'full', 'personal data recognized as what a consumer may provide in exchange for digital content')])
step(anchor('Directive 2019/770 art. 3(1)', 'value_recognition', 'full', 'personal data recognized as what a consumer may provide in exchange for digital content'), fact(14), {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_recognition', EYE_D_23_55, EYE_W_23_55), ['Directive 2019/770 art. 3(1)']), 'collected', {}, [])
step(analysis('collective_exercise', 'exercising the right together, through an intermediary', 'by interpretation', ['DGA ch. III']), rule(47), {'C': 'collective_exercise', 'Meaning': 'exercising the right together, through an intermediary', 'How': 'by interpretation', 'Provisions': ['DGA ch. III'], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('collective_exercise', 'exercising the right together, through an intermediary'), fit('collective_exercise', 'by interpretation'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'collective_exercise', EYE_D_23_55, EYE_W_23_55), ['DGA ch. III'])])
step(component('collective_exercise', 'exercising the right together, through an intermediary'), fact(5), {}, [])
step(fit('collective_exercise', 'by interpretation'), rule(45), {'C': 'collective_exercise'}, [anchored('collective_exercise'), ~fully_anchored('collective_exercise')])
step(anchored('collective_exercise'), rule(41), {'C': 'collective_exercise', 'P': 'DGA ch. III', 'D': 'partial', 'W': 'data intermediation services, without bargaining over value'}, [anchor('DGA ch. III', 'collective_exercise', 'partial', 'data intermediation services, without bargaining over value')])
step(anchor('DGA ch. III', 'collective_exercise', 'partial', 'data intermediation services, without bargaining over value'), fact(15), {}, [])
step(~fully_anchored('collective_exercise'), 'absent', {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'collective_exercise', EYE_D_23_55, EYE_W_23_55), ['DGA ch. III']), 'collected', {}, [])
step(analysis('individual_enforcement', 'enforcing the right oneself, before a court', 'in existing law', ['GDPR art. 79 and 82']), rule(47), {'C': 'individual_enforcement', 'Meaning': 'enforcing the right oneself, before a court', 'How': 'in existing law', 'Provisions': ['GDPR art. 79 and 82'], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('individual_enforcement', 'enforcing the right oneself, before a court'), fit('individual_enforcement', 'in existing law'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'individual_enforcement', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 79 and 82'])])
step(component('individual_enforcement', 'enforcing the right oneself, before a court'), fact(6), {}, [])
step(fit('individual_enforcement', 'in existing law'), rule(44), {'C': 'individual_enforcement'}, [fully_anchored('individual_enforcement')])
step(fully_anchored('individual_enforcement'), rule(42), {'C': 'individual_enforcement', 'P': 'GDPR art. 79 and 82', 'W': 'a judicial remedy and compensation for the data subject'}, [anchor('GDPR art. 79 and 82', 'individual_enforcement', 'full', 'a judicial remedy and compensation for the data subject')])
step(anchor('GDPR art. 79 and 82', 'individual_enforcement', 'full', 'a judicial remedy and compensation for the data subject'), fact(16), {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'individual_enforcement', EYE_D_23_55, EYE_W_23_55), ['GDPR art. 79 and 82']), 'collected', {}, [])
step(analysis('value_share', "receiving a share of the value one's data creates", 'needs an autonomous right', []), rule(47), {'C': 'value_share', 'Meaning': "receiving a share of the value one's data creates", 'How': 'needs an autonomous right', 'Provisions': [], 'P': EYE_P_23_55, 'D': EYE_D_23_55, 'W': EYE_W_23_55}, [component('value_share', "receiving a share of the value one's data creates"), fit('value_share', 'needs an autonomous right'), findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_share', EYE_D_23_55, EYE_W_23_55), [])])
step(component('value_share', "receiving a share of the value one's data creates"), fact(7), {}, [])
step(fit('value_share', 'needs an autonomous right'), rule(46), {'C': 'value_share'}, [gap('value_share')])
step(gap('value_share'), rule(43), {'C': 'value_share', 'Description': "receiving a share of the value one's data creates"}, [component('value_share', "receiving a share of the value one's data creates"), ~anchored('value_share')])
step(~anchored('value_share'), 'absent', {}, [])
step(findall(EYE_P_23_55, anchor(EYE_P_23_55, 'value_share', EYE_D_23_55, EYE_W_23_55), []), 'collected', {}, [])
step(evaluation('interpret_existing_law', ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement'], [unaddressed('value_share')]), rule(56), {'O': 'interpret_existing_law', 'Delivered': ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement'], 'Objections': [unaddressed('value_share')], 'F': 'right', 'C': EYE_C_23_253, 'Why': EYE_Why_23_253}, [option('interpret_existing_law', 'right'), findall(EYE_C_23_253, delivers('interpret_existing_law', EYE_C_23_253), ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement']), findall(EYE_Why_23_253, objection('interpret_existing_law', EYE_Why_23_253), [unaddressed('value_share')])])
step(option('interpret_existing_law', 'right'), fact(17), {}, [])
step(findall(EYE_C_23_253, delivers('interpret_existing_law', EYE_C_23_253), ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement']), 'collected', {}, [])
step(findall(EYE_Why_23_253, objection('interpret_existing_law', EYE_Why_23_253), [unaddressed('value_share')]), 'collected', {}, [])
step(evaluation('extend_portability', ['value_mobility', 'value_transparency'], [unaddressed('use_control'), unaddressed('collective_exercise'), unaddressed('value_share')]), rule(56), {'O': 'extend_portability', 'Delivered': ['value_mobility', 'value_transparency'], 'Objections': [unaddressed('use_control'), unaddressed('collective_exercise'), unaddressed('value_share')], 'F': 'right', 'C': EYE_C_23_253, 'Why': EYE_Why_23_253}, [option('extend_portability', 'right'), findall(EYE_C_23_253, delivers('extend_portability', EYE_C_23_253), ['value_mobility', 'value_transparency']), findall(EYE_Why_23_253, objection('extend_portability', EYE_Why_23_253), [unaddressed('use_control'), unaddressed('collective_exercise'), unaddressed('value_share')])])
step(option('extend_portability', 'right'), fact(18), {}, [])
step(findall(EYE_C_23_253, delivers('extend_portability', EYE_C_23_253), ['value_mobility', 'value_transparency']), 'collected', {}, [])
step(findall(EYE_Why_23_253, objection('extend_portability', EYE_Why_23_253), [unaddressed('use_control'), unaddressed('collective_exercise'), unaddressed('value_share')]), 'collected', {}, [])
step(evaluation('data_dividend', ['value_share', 'collective_exercise'], [unaddressed('value_transparency'), unaddressed('use_control'), unaddressed('value_mobility'), 'gives the data subject no claim of their own']), rule(56), {'O': 'data_dividend', 'Delivered': ['value_share', 'collective_exercise'], 'Objections': [unaddressed('value_transparency'), unaddressed('use_control'), unaddressed('value_mobility'), 'gives the data subject no claim of their own'], 'F': 'levy', 'C': EYE_C_23_253, 'Why': EYE_Why_23_253}, [option('data_dividend', 'levy'), findall(EYE_C_23_253, delivers('data_dividend', EYE_C_23_253), ['value_share', 'collective_exercise']), findall(EYE_Why_23_253, objection('data_dividend', EYE_Why_23_253), [unaddressed('value_transparency'), unaddressed('use_control'), unaddressed('value_mobility'), 'gives the data subject no claim of their own'])])
step(option('data_dividend', 'levy'), fact(21), {}, [])
step(findall(EYE_C_23_253, delivers('data_dividend', EYE_C_23_253), ['value_share', 'collective_exercise']), 'collected', {}, [])
step(findall(EYE_Why_23_253, objection('data_dividend', EYE_Why_23_253), [unaddressed('value_transparency'), unaddressed('use_control'), unaddressed('value_mobility'), 'gives the data subject no claim of their own']), 'collected', {}, [])
step(evaluation('data_ownership', ['value_share', 'use_control', 'value_mobility', 'individual_enforcement'], ['treats personal data as a commodity', unaddressed('value_transparency'), unaddressed('collective_exercise')]), rule(56), {'O': 'data_ownership', 'Delivered': ['value_share', 'use_control', 'value_mobility', 'individual_enforcement'], 'Objections': ['treats personal data as a commodity', unaddressed('value_transparency'), unaddressed('collective_exercise')], 'F': 'property', 'C': EYE_C_23_253, 'Why': EYE_Why_23_253}, [option('data_ownership', 'property'), findall(EYE_C_23_253, delivers('data_ownership', EYE_C_23_253), ['value_share', 'use_control', 'value_mobility', 'individual_enforcement']), findall(EYE_Why_23_253, objection('data_ownership', EYE_Why_23_253), ['treats personal data as a commodity', unaddressed('value_transparency'), unaddressed('collective_exercise')])])
step(option('data_ownership', 'property'), fact(24), {}, [])
step(findall(EYE_C_23_253, delivers('data_ownership', EYE_C_23_253), ['value_share', 'use_control', 'value_mobility', 'individual_enforcement']), 'collected', {}, [])
step(findall(EYE_Why_23_253, objection('data_ownership', EYE_Why_23_253), ['treats personal data as a commodity', unaddressed('value_transparency'), unaddressed('collective_exercise')]), 'collected', {}, [])
step(evaluation('autonomous_right', ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement', 'value_share'], []), rule(56), {'O': 'autonomous_right', 'Delivered': ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement', 'value_share'], 'Objections': [], 'F': 'inalienable_right', 'C': EYE_C_23_253, 'Why': EYE_Why_23_253}, [option('autonomous_right', 'inalienable_right'), findall(EYE_C_23_253, delivers('autonomous_right', EYE_C_23_253), ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement', 'value_share']), findall(EYE_Why_23_253, objection('autonomous_right', EYE_Why_23_253), [])])
step(option('autonomous_right', 'inalienable_right'), fact(29), {}, [])
step(findall(EYE_C_23_253, delivers('autonomous_right', EYE_C_23_253), ['value_transparency', 'use_control', 'value_mobility', 'value_recognition', 'collective_exercise', 'individual_enforcement', 'value_share']), 'collected', {}, [])
step(findall(EYE_Why_23_253, objection('autonomous_right', EYE_Why_23_253), []), 'collected', {}, [])
step(recommended('autonomous_right'), rule(55), {'O': 'autonomous_right', 'F': 'inalienable_right'}, [option('autonomous_right', 'inalienable_right'), ~objectionable('autonomous_right')])
step(~objectionable('autonomous_right'), 'absent', {}, [])
