type('ind', 'n10')

clause(1, fact(type('ind', 'n0')))
clause(2, backward(type(X, 'n1'), type(X, 'n0')))
clause(5, backward(type(X, 'n2'), type(X, 'n1')))
clause(8, backward(type(X, 'n3'), type(X, 'n2')))
clause(11, backward(type(X, 'n4'), type(X, 'n3')))
clause(14, backward(type(X, 'n5'), type(X, 'n4')))
clause(17, backward(type(X, 'n6'), type(X, 'n5')))
clause(20, backward(type(X, 'n7'), type(X, 'n6')))
clause(23, backward(type(X, 'n8'), type(X, 'n7')))
clause(26, backward(type(X, 'n9'), type(X, 'n8')))
clause(29, backward(type(X, 'n10'), type(X, 'n9')))

step(type('ind', 'n10'), clause(29), {'X': 'ind'}, [type('ind', 'n9')])
step(type('ind', 'n9'), clause(26), {'X': 'ind'}, [type('ind', 'n8')])
step(type('ind', 'n8'), clause(23), {'X': 'ind'}, [type('ind', 'n7')])
step(type('ind', 'n7'), clause(20), {'X': 'ind'}, [type('ind', 'n6')])
step(type('ind', 'n6'), clause(17), {'X': 'ind'}, [type('ind', 'n5')])
step(type('ind', 'n5'), clause(14), {'X': 'ind'}, [type('ind', 'n4')])
step(type('ind', 'n4'), clause(11), {'X': 'ind'}, [type('ind', 'n3')])
step(type('ind', 'n3'), clause(8), {'X': 'ind'}, [type('ind', 'n2')])
step(type('ind', 'n2'), clause(5), {'X': 'ind'}, [type('ind', 'n1')])
step(type('ind', 'n1'), clause(2), {'X': 'ind'}, [type('ind', 'n0')])
step(type('ind', 'n0'), clause(1), {}, [])
