type('ind', 'n100')

clause(1, fact(type('ind', 'n0')))
clause(2, implied_by(type(X, 'n1'), type(X, 'n0')))
clause(5, implied_by(type(X, 'n2'), type(X, 'n1')))
clause(8, implied_by(type(X, 'n3'), type(X, 'n2')))
clause(11, implied_by(type(X, 'n4'), type(X, 'n3')))
clause(14, implied_by(type(X, 'n5'), type(X, 'n4')))
clause(17, implied_by(type(X, 'n6'), type(X, 'n5')))
clause(20, implied_by(type(X, 'n7'), type(X, 'n6')))
clause(23, implied_by(type(X, 'n8'), type(X, 'n7')))
clause(26, implied_by(type(X, 'n9'), type(X, 'n8')))
clause(29, implied_by(type(X, 'n10'), type(X, 'n9')))
clause(32, implied_by(type(X, 'n11'), type(X, 'n10')))
clause(35, implied_by(type(X, 'n12'), type(X, 'n11')))
clause(38, implied_by(type(X, 'n13'), type(X, 'n12')))
clause(41, implied_by(type(X, 'n14'), type(X, 'n13')))
clause(44, implied_by(type(X, 'n15'), type(X, 'n14')))
clause(47, implied_by(type(X, 'n16'), type(X, 'n15')))
clause(50, implied_by(type(X, 'n17'), type(X, 'n16')))
clause(53, implied_by(type(X, 'n18'), type(X, 'n17')))
clause(56, implied_by(type(X, 'n19'), type(X, 'n18')))
clause(59, implied_by(type(X, 'n20'), type(X, 'n19')))
clause(62, implied_by(type(X, 'n21'), type(X, 'n20')))
clause(65, implied_by(type(X, 'n22'), type(X, 'n21')))
clause(68, implied_by(type(X, 'n23'), type(X, 'n22')))
clause(71, implied_by(type(X, 'n24'), type(X, 'n23')))
clause(74, implied_by(type(X, 'n25'), type(X, 'n24')))
clause(77, implied_by(type(X, 'n26'), type(X, 'n25')))
clause(80, implied_by(type(X, 'n27'), type(X, 'n26')))
clause(83, implied_by(type(X, 'n28'), type(X, 'n27')))
clause(86, implied_by(type(X, 'n29'), type(X, 'n28')))
clause(89, implied_by(type(X, 'n30'), type(X, 'n29')))
clause(92, implied_by(type(X, 'n31'), type(X, 'n30')))
clause(95, implied_by(type(X, 'n32'), type(X, 'n31')))
clause(98, implied_by(type(X, 'n33'), type(X, 'n32')))
clause(101, implied_by(type(X, 'n34'), type(X, 'n33')))
clause(104, implied_by(type(X, 'n35'), type(X, 'n34')))
clause(107, implied_by(type(X, 'n36'), type(X, 'n35')))
clause(110, implied_by(type(X, 'n37'), type(X, 'n36')))
clause(113, implied_by(type(X, 'n38'), type(X, 'n37')))
clause(116, implied_by(type(X, 'n39'), type(X, 'n38')))
clause(119, implied_by(type(X, 'n40'), type(X, 'n39')))
clause(122, implied_by(type(X, 'n41'), type(X, 'n40')))
clause(125, implied_by(type(X, 'n42'), type(X, 'n41')))
clause(128, implied_by(type(X, 'n43'), type(X, 'n42')))
clause(131, implied_by(type(X, 'n44'), type(X, 'n43')))
clause(134, implied_by(type(X, 'n45'), type(X, 'n44')))
clause(137, implied_by(type(X, 'n46'), type(X, 'n45')))
clause(140, implied_by(type(X, 'n47'), type(X, 'n46')))
clause(143, implied_by(type(X, 'n48'), type(X, 'n47')))
clause(146, implied_by(type(X, 'n49'), type(X, 'n48')))
clause(149, implied_by(type(X, 'n50'), type(X, 'n49')))
clause(152, implied_by(type(X, 'n51'), type(X, 'n50')))
clause(155, implied_by(type(X, 'n52'), type(X, 'n51')))
clause(158, implied_by(type(X, 'n53'), type(X, 'n52')))
clause(161, implied_by(type(X, 'n54'), type(X, 'n53')))
clause(164, implied_by(type(X, 'n55'), type(X, 'n54')))
clause(167, implied_by(type(X, 'n56'), type(X, 'n55')))
clause(170, implied_by(type(X, 'n57'), type(X, 'n56')))
clause(173, implied_by(type(X, 'n58'), type(X, 'n57')))
clause(176, implied_by(type(X, 'n59'), type(X, 'n58')))
clause(179, implied_by(type(X, 'n60'), type(X, 'n59')))
clause(182, implied_by(type(X, 'n61'), type(X, 'n60')))
clause(185, implied_by(type(X, 'n62'), type(X, 'n61')))
clause(188, implied_by(type(X, 'n63'), type(X, 'n62')))
clause(191, implied_by(type(X, 'n64'), type(X, 'n63')))
clause(194, implied_by(type(X, 'n65'), type(X, 'n64')))
clause(197, implied_by(type(X, 'n66'), type(X, 'n65')))
clause(200, implied_by(type(X, 'n67'), type(X, 'n66')))
clause(203, implied_by(type(X, 'n68'), type(X, 'n67')))
clause(206, implied_by(type(X, 'n69'), type(X, 'n68')))
clause(209, implied_by(type(X, 'n70'), type(X, 'n69')))
clause(212, implied_by(type(X, 'n71'), type(X, 'n70')))
clause(215, implied_by(type(X, 'n72'), type(X, 'n71')))
clause(218, implied_by(type(X, 'n73'), type(X, 'n72')))
clause(221, implied_by(type(X, 'n74'), type(X, 'n73')))
clause(224, implied_by(type(X, 'n75'), type(X, 'n74')))
clause(227, implied_by(type(X, 'n76'), type(X, 'n75')))
clause(230, implied_by(type(X, 'n77'), type(X, 'n76')))
clause(233, implied_by(type(X, 'n78'), type(X, 'n77')))
clause(236, implied_by(type(X, 'n79'), type(X, 'n78')))
clause(239, implied_by(type(X, 'n80'), type(X, 'n79')))
clause(242, implied_by(type(X, 'n81'), type(X, 'n80')))
clause(245, implied_by(type(X, 'n82'), type(X, 'n81')))
clause(248, implied_by(type(X, 'n83'), type(X, 'n82')))
clause(251, implied_by(type(X, 'n84'), type(X, 'n83')))
clause(254, implied_by(type(X, 'n85'), type(X, 'n84')))
clause(257, implied_by(type(X, 'n86'), type(X, 'n85')))
clause(260, implied_by(type(X, 'n87'), type(X, 'n86')))
clause(263, implied_by(type(X, 'n88'), type(X, 'n87')))
clause(266, implied_by(type(X, 'n89'), type(X, 'n88')))
clause(269, implied_by(type(X, 'n90'), type(X, 'n89')))
clause(272, implied_by(type(X, 'n91'), type(X, 'n90')))
clause(275, implied_by(type(X, 'n92'), type(X, 'n91')))
clause(278, implied_by(type(X, 'n93'), type(X, 'n92')))
clause(281, implied_by(type(X, 'n94'), type(X, 'n93')))
clause(284, implied_by(type(X, 'n95'), type(X, 'n94')))
clause(287, implied_by(type(X, 'n96'), type(X, 'n95')))
clause(290, implied_by(type(X, 'n97'), type(X, 'n96')))
clause(293, implied_by(type(X, 'n98'), type(X, 'n97')))
clause(296, implied_by(type(X, 'n99'), type(X, 'n98')))
clause(299, implied_by(type(X, 'n100'), type(X, 'n99')))

step(type('ind', 'n100'), clause(299), {'X': 'ind'}, [type('ind', 'n99')])
step(type('ind', 'n99'), clause(296), {'X': 'ind'}, [type('ind', 'n98')])
step(type('ind', 'n98'), clause(293), {'X': 'ind'}, [type('ind', 'n97')])
step(type('ind', 'n97'), clause(290), {'X': 'ind'}, [type('ind', 'n96')])
step(type('ind', 'n96'), clause(287), {'X': 'ind'}, [type('ind', 'n95')])
step(type('ind', 'n95'), clause(284), {'X': 'ind'}, [type('ind', 'n94')])
step(type('ind', 'n94'), clause(281), {'X': 'ind'}, [type('ind', 'n93')])
step(type('ind', 'n93'), clause(278), {'X': 'ind'}, [type('ind', 'n92')])
step(type('ind', 'n92'), clause(275), {'X': 'ind'}, [type('ind', 'n91')])
step(type('ind', 'n91'), clause(272), {'X': 'ind'}, [type('ind', 'n90')])
step(type('ind', 'n90'), clause(269), {'X': 'ind'}, [type('ind', 'n89')])
step(type('ind', 'n89'), clause(266), {'X': 'ind'}, [type('ind', 'n88')])
step(type('ind', 'n88'), clause(263), {'X': 'ind'}, [type('ind', 'n87')])
step(type('ind', 'n87'), clause(260), {'X': 'ind'}, [type('ind', 'n86')])
step(type('ind', 'n86'), clause(257), {'X': 'ind'}, [type('ind', 'n85')])
step(type('ind', 'n85'), clause(254), {'X': 'ind'}, [type('ind', 'n84')])
step(type('ind', 'n84'), clause(251), {'X': 'ind'}, [type('ind', 'n83')])
step(type('ind', 'n83'), clause(248), {'X': 'ind'}, [type('ind', 'n82')])
step(type('ind', 'n82'), clause(245), {'X': 'ind'}, [type('ind', 'n81')])
step(type('ind', 'n81'), clause(242), {'X': 'ind'}, [type('ind', 'n80')])
step(type('ind', 'n80'), clause(239), {'X': 'ind'}, [type('ind', 'n79')])
step(type('ind', 'n79'), clause(236), {'X': 'ind'}, [type('ind', 'n78')])
step(type('ind', 'n78'), clause(233), {'X': 'ind'}, [type('ind', 'n77')])
step(type('ind', 'n77'), clause(230), {'X': 'ind'}, [type('ind', 'n76')])
step(type('ind', 'n76'), clause(227), {'X': 'ind'}, [type('ind', 'n75')])
step(type('ind', 'n75'), clause(224), {'X': 'ind'}, [type('ind', 'n74')])
step(type('ind', 'n74'), clause(221), {'X': 'ind'}, [type('ind', 'n73')])
step(type('ind', 'n73'), clause(218), {'X': 'ind'}, [type('ind', 'n72')])
step(type('ind', 'n72'), clause(215), {'X': 'ind'}, [type('ind', 'n71')])
step(type('ind', 'n71'), clause(212), {'X': 'ind'}, [type('ind', 'n70')])
step(type('ind', 'n70'), clause(209), {'X': 'ind'}, [type('ind', 'n69')])
step(type('ind', 'n69'), clause(206), {'X': 'ind'}, [type('ind', 'n68')])
step(type('ind', 'n68'), clause(203), {'X': 'ind'}, [type('ind', 'n67')])
step(type('ind', 'n67'), clause(200), {'X': 'ind'}, [type('ind', 'n66')])
step(type('ind', 'n66'), clause(197), {'X': 'ind'}, [type('ind', 'n65')])
step(type('ind', 'n65'), clause(194), {'X': 'ind'}, [type('ind', 'n64')])
step(type('ind', 'n64'), clause(191), {'X': 'ind'}, [type('ind', 'n63')])
step(type('ind', 'n63'), clause(188), {'X': 'ind'}, [type('ind', 'n62')])
step(type('ind', 'n62'), clause(185), {'X': 'ind'}, [type('ind', 'n61')])
step(type('ind', 'n61'), clause(182), {'X': 'ind'}, [type('ind', 'n60')])
step(type('ind', 'n60'), clause(179), {'X': 'ind'}, [type('ind', 'n59')])
step(type('ind', 'n59'), clause(176), {'X': 'ind'}, [type('ind', 'n58')])
step(type('ind', 'n58'), clause(173), {'X': 'ind'}, [type('ind', 'n57')])
step(type('ind', 'n57'), clause(170), {'X': 'ind'}, [type('ind', 'n56')])
step(type('ind', 'n56'), clause(167), {'X': 'ind'}, [type('ind', 'n55')])
step(type('ind', 'n55'), clause(164), {'X': 'ind'}, [type('ind', 'n54')])
step(type('ind', 'n54'), clause(161), {'X': 'ind'}, [type('ind', 'n53')])
step(type('ind', 'n53'), clause(158), {'X': 'ind'}, [type('ind', 'n52')])
step(type('ind', 'n52'), clause(155), {'X': 'ind'}, [type('ind', 'n51')])
step(type('ind', 'n51'), clause(152), {'X': 'ind'}, [type('ind', 'n50')])
step(type('ind', 'n50'), clause(149), {'X': 'ind'}, [type('ind', 'n49')])
step(type('ind', 'n49'), clause(146), {'X': 'ind'}, [type('ind', 'n48')])
step(type('ind', 'n48'), clause(143), {'X': 'ind'}, [type('ind', 'n47')])
step(type('ind', 'n47'), clause(140), {'X': 'ind'}, [type('ind', 'n46')])
step(type('ind', 'n46'), clause(137), {'X': 'ind'}, [type('ind', 'n45')])
step(type('ind', 'n45'), clause(134), {'X': 'ind'}, [type('ind', 'n44')])
step(type('ind', 'n44'), clause(131), {'X': 'ind'}, [type('ind', 'n43')])
step(type('ind', 'n43'), clause(128), {'X': 'ind'}, [type('ind', 'n42')])
step(type('ind', 'n42'), clause(125), {'X': 'ind'}, [type('ind', 'n41')])
step(type('ind', 'n41'), clause(122), {'X': 'ind'}, [type('ind', 'n40')])
step(type('ind', 'n40'), clause(119), {'X': 'ind'}, [type('ind', 'n39')])
step(type('ind', 'n39'), clause(116), {'X': 'ind'}, [type('ind', 'n38')])
step(type('ind', 'n38'), clause(113), {'X': 'ind'}, [type('ind', 'n37')])
step(type('ind', 'n37'), clause(110), {'X': 'ind'}, [type('ind', 'n36')])
step(type('ind', 'n36'), clause(107), {'X': 'ind'}, [type('ind', 'n35')])
step(type('ind', 'n35'), clause(104), {'X': 'ind'}, [type('ind', 'n34')])
step(type('ind', 'n34'), clause(101), {'X': 'ind'}, [type('ind', 'n33')])
step(type('ind', 'n33'), clause(98), {'X': 'ind'}, [type('ind', 'n32')])
step(type('ind', 'n32'), clause(95), {'X': 'ind'}, [type('ind', 'n31')])
step(type('ind', 'n31'), clause(92), {'X': 'ind'}, [type('ind', 'n30')])
step(type('ind', 'n30'), clause(89), {'X': 'ind'}, [type('ind', 'n29')])
step(type('ind', 'n29'), clause(86), {'X': 'ind'}, [type('ind', 'n28')])
step(type('ind', 'n28'), clause(83), {'X': 'ind'}, [type('ind', 'n27')])
step(type('ind', 'n27'), clause(80), {'X': 'ind'}, [type('ind', 'n26')])
step(type('ind', 'n26'), clause(77), {'X': 'ind'}, [type('ind', 'n25')])
step(type('ind', 'n25'), clause(74), {'X': 'ind'}, [type('ind', 'n24')])
step(type('ind', 'n24'), clause(71), {'X': 'ind'}, [type('ind', 'n23')])
step(type('ind', 'n23'), clause(68), {'X': 'ind'}, [type('ind', 'n22')])
step(type('ind', 'n22'), clause(65), {'X': 'ind'}, [type('ind', 'n21')])
step(type('ind', 'n21'), clause(62), {'X': 'ind'}, [type('ind', 'n20')])
step(type('ind', 'n20'), clause(59), {'X': 'ind'}, [type('ind', 'n19')])
step(type('ind', 'n19'), clause(56), {'X': 'ind'}, [type('ind', 'n18')])
step(type('ind', 'n18'), clause(53), {'X': 'ind'}, [type('ind', 'n17')])
step(type('ind', 'n17'), clause(50), {'X': 'ind'}, [type('ind', 'n16')])
step(type('ind', 'n16'), clause(47), {'X': 'ind'}, [type('ind', 'n15')])
step(type('ind', 'n15'), clause(44), {'X': 'ind'}, [type('ind', 'n14')])
step(type('ind', 'n14'), clause(41), {'X': 'ind'}, [type('ind', 'n13')])
step(type('ind', 'n13'), clause(38), {'X': 'ind'}, [type('ind', 'n12')])
step(type('ind', 'n12'), clause(35), {'X': 'ind'}, [type('ind', 'n11')])
step(type('ind', 'n11'), clause(32), {'X': 'ind'}, [type('ind', 'n10')])
step(type('ind', 'n10'), clause(29), {'X': 'ind'}, [type('ind', 'n9')])
step(type('ind', 'n9'), clause(26), {'X': 'ind'}, [type('ind', 'n8')])
step(type('ind', 'n8'), clause(23), {'X': 'ind'}, [type('ind', 'n7')])
step(type('ind', 'n7'), clause(20), {'X': 'ind'}, [type('ind', 'n6')])
step(type('ind', 'n6'), clause(17), {'X': 'ind'}, [type('ind', 'n5')])
step(type('ind', 'n5'), clause(14), {'X': 'ind'}, [type('ind', 'n4')])
step(type('ind', 'n4'), clause(11), {'X': 'ind'}, [type('ind', 'n3')])
step(type('ind', 'n3'), clause(8), {'X': 'ind'}, [type('ind', 'n2')])
step(type('ind', 'n2'), clause(5), {'X': 'ind'}, [type('ind', 'n1')])
step(type('ind', 'n1'), clause(2), {'X': 'ind'}, [type('ind', 'n0')])
step(type('ind', 'n0'), clause(1), {}, [])
