dog_count('alice', 5)
dog_count('bob', 2)
requires('alice', 'dog_license')

clause(8, fact(owner('alice')))
clause(9, fact(owner('bob')))
clause(10, fact(length([], 0)))
clause(11, backward(length([__anon0, *Xs], N), length(Xs, Before), is_(N, Before + 1)))
clause(12, forward(dog_count(Owner, N), owner(Owner), findall(Dog, owns(Owner, Dog), Dogs), length(Dogs, N)))
clause(13, forward(requires(Owner, 'dog_license'), dog_count(Owner, N), N > 4))

step(dog_count('alice', 5), rule(12), {'Owner': 'alice', 'N': 5, 'Dog': EYE_Dog_23_1, 'Dogs': ['dog1', 'dog2', 'dog3', 'dog4', 'dog5']}, [owner('alice'), findall(EYE_Dog_23_1, owns('alice', EYE_Dog_23_1), ['dog1', 'dog2', 'dog3', 'dog4', 'dog5']), length(['dog1', 'dog2', 'dog3', 'dog4', 'dog5'], 5)])
step(owner('alice'), fact(8), {}, [])
step(findall(EYE_Dog_23_1, owns('alice', EYE_Dog_23_1), ['dog1', 'dog2', 'dog3', 'dog4', 'dog5']), 'collected', {}, [])
step(length(['dog1', 'dog2', 'dog3', 'dog4', 'dog5'], 5), rule(11), {'__anon0': 'dog1', 'Xs': ['dog2', 'dog3', 'dog4', 'dog5'], 'N': 5, 'Before': 4}, [length(['dog2', 'dog3', 'dog4', 'dog5'], 4), is_(5, 4 + 1)])
step(length(['dog2', 'dog3', 'dog4', 'dog5'], 4), rule(11), {'__anon0': 'dog2', 'Xs': ['dog3', 'dog4', 'dog5'], 'N': 4, 'Before': 3}, [length(['dog3', 'dog4', 'dog5'], 3), is_(4, 3 + 1)])
step(length(['dog3', 'dog4', 'dog5'], 3), rule(11), {'__anon0': 'dog3', 'Xs': ['dog4', 'dog5'], 'N': 3, 'Before': 2}, [length(['dog4', 'dog5'], 2), is_(3, 2 + 1)])
step(length(['dog4', 'dog5'], 2), rule(11), {'__anon0': 'dog4', 'Xs': ['dog5'], 'N': 2, 'Before': 1}, [length(['dog5'], 1), is_(2, 1 + 1)])
step(length(['dog5'], 1), rule(11), {'__anon0': 'dog5', 'Xs': [], 'N': 1, 'Before': 0}, [length([], 0), is_(1, 0 + 1)])
step(length([], 0), fact(10), {}, [])
step(is_(1, 0 + 1), 'builtin', {}, [])
step(is_(2, 1 + 1), 'builtin', {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(is_(4, 3 + 1), 'builtin', {}, [])
step(is_(5, 4 + 1), 'builtin', {}, [])
step(dog_count('bob', 2), rule(12), {'Owner': 'bob', 'N': 2, 'Dog': EYE_Dog_23_1, 'Dogs': ['dog6', 'dog7']}, [owner('bob'), findall(EYE_Dog_23_1, owns('bob', EYE_Dog_23_1), ['dog6', 'dog7']), length(['dog6', 'dog7'], 2)])
step(owner('bob'), fact(9), {}, [])
step(findall(EYE_Dog_23_1, owns('bob', EYE_Dog_23_1), ['dog6', 'dog7']), 'collected', {}, [])
step(length(['dog6', 'dog7'], 2), rule(11), {'__anon0': 'dog6', 'Xs': ['dog7'], 'N': 2, 'Before': 1}, [length(['dog7'], 1), is_(2, 1 + 1)])
step(length(['dog7'], 1), rule(11), {'__anon0': 'dog7', 'Xs': [], 'N': 1, 'Before': 0}, [length([], 0), is_(1, 0 + 1)])
step(requires('alice', 'dog_license'), rule(13), {'Owner': 'alice', 'N': 5}, [dog_count('alice', 5), 5 > 4])
step(5 > 4, 'builtin', {}, [])
