has_parent('ann', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_0')
has_parent('bob', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_1')
sibling('dan', 'fay')
sibling('fay', 'dan')
invoice_for('carl', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_2')
invoice_for('dora', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_3')
sent('https://eyereasoner.github.io/.well-known/genid/examples#sk_2')
sent('https://eyereasoner.github.io/.well-known/genid/examples#sk_3')
meeting('https://eyereasoner.github.io/.well-known/genid/examples#sk_4')
attends('https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'ann')
attends('https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'dora')

clause(1, fact(person('ann')))
clause(2, fact(person('bob')))
clause(3, implies(person(X), has_parent(X, P)))
clause(4, fact(has_parent('dan', 'eve')))
clause(5, fact(has_parent('fay', 'eve')))
clause(6, implies(has_parent(X, P) & has_parent(Y, P) & not_identical(X, Y), sibling(X, Y)))
clause(7, fact(ordered('carl', 'lamp')))
clause(9, fact(ordered('dora', 'chair')))
clause(10, implies(ordered(C, Item), invoice_for(C, I)))
clause(11, implies(invoice_for(C, I), sent(I)))
clause(12, fact(colleagues('ann', 'dora')))
clause(13, implies(colleagues(X, Y), meeting(M) & attends(M, X) & attends(M, Y)))

step(has_parent('ann', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_0'), clause(3), {'X': 'ann', 'P': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_0'}, [person('ann')])
step(person('ann'), clause(1), {}, [])
step(has_parent('bob', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_1'), clause(3), {'X': 'bob', 'P': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_1'}, [person('bob')])
step(person('bob'), clause(2), {}, [])
step(sibling('dan', 'fay'), clause(6), {'X': 'dan', 'Y': 'fay', 'P': 'eve'}, [has_parent('dan', 'eve'), has_parent('fay', 'eve'), not_identical('dan', 'fay')])
step(has_parent('dan', 'eve'), clause(4), {}, [])
step(has_parent('fay', 'eve'), clause(5), {}, [])
step(not_identical('dan', 'fay'), 'builtin', {}, [])
step(sibling('fay', 'dan'), clause(6), {'X': 'fay', 'Y': 'dan', 'P': 'eve'}, [has_parent('fay', 'eve'), has_parent('dan', 'eve'), not_identical('fay', 'dan')])
step(not_identical('fay', 'dan'), 'builtin', {}, [])
step(invoice_for('carl', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_2'), clause(10), {'C': 'carl', 'I': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_2', 'Item': 'lamp'}, [ordered('carl', 'lamp')])
step(ordered('carl', 'lamp'), clause(7), {}, [])
step(invoice_for('dora', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_3'), clause(10), {'C': 'dora', 'I': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_3', 'Item': 'chair'}, [ordered('dora', 'chair')])
step(ordered('dora', 'chair'), clause(9), {}, [])
step(sent('https://eyereasoner.github.io/.well-known/genid/examples#sk_2'), clause(11), {'I': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_2', 'C': 'carl'}, [invoice_for('carl', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_2')])
step(sent('https://eyereasoner.github.io/.well-known/genid/examples#sk_3'), clause(11), {'I': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_3', 'C': 'dora'}, [invoice_for('dora', 'https://eyereasoner.github.io/.well-known/genid/examples#sk_3')])
step(meeting('https://eyereasoner.github.io/.well-known/genid/examples#sk_4'), clause(13), {'M': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'X': 'ann', 'Y': 'dora'}, [colleagues('ann', 'dora')])
step(colleagues('ann', 'dora'), clause(12), {}, [])
step(attends('https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'ann'), clause(13), {'M': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'X': 'ann', 'Y': 'dora'}, [colleagues('ann', 'dora')])
step(attends('https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'dora'), clause(13), {'M': 'https://eyereasoner.github.io/.well-known/genid/examples#sk_4', 'X': 'ann', 'Y': 'dora'}, [colleagues('ann', 'dora')])
