generation('bob', 1)
generation('carol', 1)
branch('heidi', 'b')
branch('ivan', 'b')
branch('judy', 'c')
generation('dave', 2)
generation('eve', 2)
generation('frank', 2)
generation('grace', 2)
cousin('dave', 'frank')
cousin('dave', 'grace')
cousin('eve', 'frank')
cousin('eve', 'grace')
cousin('frank', 'dave')
cousin('frank', 'eve')
cousin('grace', 'dave')
cousin('grace', 'eve')
generation('heidi', 3)
generation('ivan', 3)
generation('judy', 3)
cousin('heidi', 'judy')
cousin('ivan', 'judy')
cousin('judy', 'heidi')
cousin('judy', 'ivan')

clause(1, fact(parent('adam', 'bob')))
clause(2, fact(parent('adam', 'carol')))
clause(3, fact(parent('bob', 'dave')))
clause(4, fact(parent('bob', 'eve')))
clause(5, fact(parent('carol', 'frank')))
clause(6, fact(parent('carol', 'grace')))
clause(7, fact(parent('dave', 'heidi')))
clause(8, fact(parent('eve', 'ivan')))
clause(9, fact(parent('frank', 'judy')))
clause(10, fact(generation('adam', 0)))
clause(11, fact(branch('dave', 'b')))
clause(12, fact(branch('eve', 'b')))
clause(13, fact(branch('frank', 'c')))
clause(14, fact(branch('grace', 'c')))
clause(15, forward(generation(Child, Next), parent(Parent, Child), generation(Parent, N), is_(Next, N + 1)))
clause(16, forward(branch(Child, Branch), parent(Parent, Child), branch(Parent, Branch)))
clause(17, forward(cousin(X, Y), generation(X, N), generation(Y, N), branch(X, A), branch(Y, B), not_unify(A, B)))

step(generation('bob', 1), rule(15), {'Child': 'bob', 'Next': 1, 'Parent': 'adam', 'N': 0}, [parent('adam', 'bob'), generation('adam', 0), is_(1, 0 + 1)])
step(parent('adam', 'bob'), fact(1), {}, [])
step(generation('adam', 0), fact(10), {}, [])
step(is_(1, 0 + 1), 'builtin', {}, [])
step(generation('carol', 1), rule(15), {'Child': 'carol', 'Next': 1, 'Parent': 'adam', 'N': 0}, [parent('adam', 'carol'), generation('adam', 0), is_(1, 0 + 1)])
step(parent('adam', 'carol'), fact(2), {}, [])
step(branch('heidi', 'b'), rule(16), {'Child': 'heidi', 'Branch': 'b', 'Parent': 'dave'}, [parent('dave', 'heidi'), branch('dave', 'b')])
step(parent('dave', 'heidi'), fact(7), {}, [])
step(branch('dave', 'b'), fact(11), {}, [])
step(branch('ivan', 'b'), rule(16), {'Child': 'ivan', 'Branch': 'b', 'Parent': 'eve'}, [parent('eve', 'ivan'), branch('eve', 'b')])
step(parent('eve', 'ivan'), fact(8), {}, [])
step(branch('eve', 'b'), fact(12), {}, [])
step(branch('judy', 'c'), rule(16), {'Child': 'judy', 'Branch': 'c', 'Parent': 'frank'}, [parent('frank', 'judy'), branch('frank', 'c')])
step(parent('frank', 'judy'), fact(9), {}, [])
step(branch('frank', 'c'), fact(13), {}, [])
step(generation('dave', 2), rule(15), {'Child': 'dave', 'Next': 2, 'Parent': 'bob', 'N': 1}, [parent('bob', 'dave'), generation('bob', 1), is_(2, 1 + 1)])
step(parent('bob', 'dave'), fact(3), {}, [])
step(is_(2, 1 + 1), 'builtin', {}, [])
step(generation('eve', 2), rule(15), {'Child': 'eve', 'Next': 2, 'Parent': 'bob', 'N': 1}, [parent('bob', 'eve'), generation('bob', 1), is_(2, 1 + 1)])
step(parent('bob', 'eve'), fact(4), {}, [])
step(generation('frank', 2), rule(15), {'Child': 'frank', 'Next': 2, 'Parent': 'carol', 'N': 1}, [parent('carol', 'frank'), generation('carol', 1), is_(2, 1 + 1)])
step(parent('carol', 'frank'), fact(5), {}, [])
step(generation('grace', 2), rule(15), {'Child': 'grace', 'Next': 2, 'Parent': 'carol', 'N': 1}, [parent('carol', 'grace'), generation('carol', 1), is_(2, 1 + 1)])
step(parent('carol', 'grace'), fact(6), {}, [])
step(cousin('dave', 'frank'), rule(17), {'X': 'dave', 'Y': 'frank', 'N': 2, 'A': 'b', 'B': 'c'}, [generation('dave', 2), generation('frank', 2), branch('dave', 'b'), branch('frank', 'c'), not_unify('b', 'c')])
step(not_unify('b', 'c'), 'builtin', {}, [])
step(cousin('dave', 'grace'), rule(17), {'X': 'dave', 'Y': 'grace', 'N': 2, 'A': 'b', 'B': 'c'}, [generation('dave', 2), generation('grace', 2), branch('dave', 'b'), branch('grace', 'c'), not_unify('b', 'c')])
step(branch('grace', 'c'), fact(14), {}, [])
step(cousin('eve', 'frank'), rule(17), {'X': 'eve', 'Y': 'frank', 'N': 2, 'A': 'b', 'B': 'c'}, [generation('eve', 2), generation('frank', 2), branch('eve', 'b'), branch('frank', 'c'), not_unify('b', 'c')])
step(cousin('eve', 'grace'), rule(17), {'X': 'eve', 'Y': 'grace', 'N': 2, 'A': 'b', 'B': 'c'}, [generation('eve', 2), generation('grace', 2), branch('eve', 'b'), branch('grace', 'c'), not_unify('b', 'c')])
step(cousin('frank', 'dave'), rule(17), {'X': 'frank', 'Y': 'dave', 'N': 2, 'A': 'c', 'B': 'b'}, [generation('frank', 2), generation('dave', 2), branch('frank', 'c'), branch('dave', 'b'), not_unify('c', 'b')])
step(not_unify('c', 'b'), 'builtin', {}, [])
step(cousin('frank', 'eve'), rule(17), {'X': 'frank', 'Y': 'eve', 'N': 2, 'A': 'c', 'B': 'b'}, [generation('frank', 2), generation('eve', 2), branch('frank', 'c'), branch('eve', 'b'), not_unify('c', 'b')])
step(cousin('grace', 'dave'), rule(17), {'X': 'grace', 'Y': 'dave', 'N': 2, 'A': 'c', 'B': 'b'}, [generation('grace', 2), generation('dave', 2), branch('grace', 'c'), branch('dave', 'b'), not_unify('c', 'b')])
step(cousin('grace', 'eve'), rule(17), {'X': 'grace', 'Y': 'eve', 'N': 2, 'A': 'c', 'B': 'b'}, [generation('grace', 2), generation('eve', 2), branch('grace', 'c'), branch('eve', 'b'), not_unify('c', 'b')])
step(generation('heidi', 3), rule(15), {'Child': 'heidi', 'Next': 3, 'Parent': 'dave', 'N': 2}, [parent('dave', 'heidi'), generation('dave', 2), is_(3, 2 + 1)])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(generation('ivan', 3), rule(15), {'Child': 'ivan', 'Next': 3, 'Parent': 'eve', 'N': 2}, [parent('eve', 'ivan'), generation('eve', 2), is_(3, 2 + 1)])
step(generation('judy', 3), rule(15), {'Child': 'judy', 'Next': 3, 'Parent': 'frank', 'N': 2}, [parent('frank', 'judy'), generation('frank', 2), is_(3, 2 + 1)])
step(cousin('heidi', 'judy'), rule(17), {'X': 'heidi', 'Y': 'judy', 'N': 3, 'A': 'b', 'B': 'c'}, [generation('heidi', 3), generation('judy', 3), branch('heidi', 'b'), branch('judy', 'c'), not_unify('b', 'c')])
step(cousin('ivan', 'judy'), rule(17), {'X': 'ivan', 'Y': 'judy', 'N': 3, 'A': 'b', 'B': 'c'}, [generation('ivan', 3), generation('judy', 3), branch('ivan', 'b'), branch('judy', 'c'), not_unify('b', 'c')])
step(cousin('judy', 'heidi'), rule(17), {'X': 'judy', 'Y': 'heidi', 'N': 3, 'A': 'c', 'B': 'b'}, [generation('judy', 3), generation('heidi', 3), branch('judy', 'c'), branch('heidi', 'b'), not_unify('c', 'b')])
step(cousin('judy', 'ivan'), rule(17), {'X': 'judy', 'Y': 'ivan', 'N': 3, 'A': 'c', 'B': 'b'}, [generation('judy', 3), generation('ivan', 3), branch('judy', 'c'), branch('ivan', 'b'), not_unify('c', 'b')])
