flat_map(['s1', 's2', 's3'], 'p1', ['o1', 'o2', 'o3', 'o4'])
flat_map(['missing'], 'p1', [])
flat_map(['s1'], 'p2', [])

clause(5, fact(append([], Ys, Ys)))
clause(6, backward(append([X, *Xs], Ys, [X, *Zs]), append(Xs, Ys, Zs)))
clause(7, fact(flat_map([], __anon0, [])))
clause(8, backward(flat_map([S, *Subjects], P, Objects), findall(O, t(S, P, O), Here), flat_map(Subjects, P, Rest), append(Here, Rest, Objects)))

step(flat_map(['s1', 's2', 's3'], 'p1', ['o1', 'o2', 'o3', 'o4']), clause(8), {'S': 's1', 'Subjects': ['s2', 's3'], 'P': 'p1', 'Objects': ['o1', 'o2', 'o3', 'o4'], 'O': VAR_O_23_3, 'Here': ['o1'], 'Rest': ['o2', 'o3', 'o4']}, [findall(VAR_O_23_3, t('s1', 'p1', VAR_O_23_3), ['o1']), flat_map(['s2', 's3'], 'p1', ['o2', 'o3', 'o4']), append(['o1'], ['o2', 'o3', 'o4'], ['o1', 'o2', 'o3', 'o4'])])
step(findall(VAR_O_23_3, t('s1', 'p1', VAR_O_23_3), ['o1']), 'collected', {}, [])
step(flat_map(['s2', 's3'], 'p1', ['o2', 'o3', 'o4']), clause(8), {'S': 's2', 'Subjects': ['s3'], 'P': 'p1', 'Objects': ['o2', 'o3', 'o4'], 'O': VAR_O_23_7, 'Here': ['o2'], 'Rest': ['o3', 'o4']}, [findall(VAR_O_23_7, t('s2', 'p1', VAR_O_23_7), ['o2']), flat_map(['s3'], 'p1', ['o3', 'o4']), append(['o2'], ['o3', 'o4'], ['o2', 'o3', 'o4'])])
step(findall(VAR_O_23_7, t('s2', 'p1', VAR_O_23_7), ['o2']), 'collected', {}, [])
step(flat_map(['s3'], 'p1', ['o3', 'o4']), clause(8), {'S': 's3', 'Subjects': [], 'P': 'p1', 'Objects': ['o3', 'o4'], 'O': VAR_O_23_11, 'Here': ['o3', 'o4'], 'Rest': []}, [findall(VAR_O_23_11, t('s3', 'p1', VAR_O_23_11), ['o3', 'o4']), flat_map([], 'p1', []), append(['o3', 'o4'], [], ['o3', 'o4'])])
step(findall(VAR_O_23_11, t('s3', 'p1', VAR_O_23_11), ['o3', 'o4']), 'collected', {}, [])
step(flat_map([], 'p1', []), clause(7), {'__anon0': 'p1'}, [])
step(append(['o3', 'o4'], [], ['o3', 'o4']), clause(6), {'X': 'o3', 'Xs': ['o4'], 'Ys': [], 'Zs': ['o4']}, [append(['o4'], [], ['o4'])])
step(append(['o4'], [], ['o4']), clause(6), {'X': 'o4', 'Xs': [], 'Ys': [], 'Zs': []}, [append([], [], [])])
step(append([], [], []), clause(5), {'Ys': []}, [])
step(append(['o2'], ['o3', 'o4'], ['o2', 'o3', 'o4']), clause(6), {'X': 'o2', 'Xs': [], 'Ys': ['o3', 'o4'], 'Zs': ['o3', 'o4']}, [append([], ['o3', 'o4'], ['o3', 'o4'])])
step(append([], ['o3', 'o4'], ['o3', 'o4']), clause(5), {'Ys': ['o3', 'o4']}, [])
step(append(['o1'], ['o2', 'o3', 'o4'], ['o1', 'o2', 'o3', 'o4']), clause(6), {'X': 'o1', 'Xs': [], 'Ys': ['o2', 'o3', 'o4'], 'Zs': ['o2', 'o3', 'o4']}, [append([], ['o2', 'o3', 'o4'], ['o2', 'o3', 'o4'])])
step(append([], ['o2', 'o3', 'o4'], ['o2', 'o3', 'o4']), clause(5), {'Ys': ['o2', 'o3', 'o4']}, [])
step(flat_map(['missing'], 'p1', []), clause(8), {'S': 'missing', 'Subjects': [], 'P': 'p1', 'Objects': [], 'O': VAR_O_23_34, 'Here': [], 'Rest': []}, [findall(VAR_O_23_34, t('missing', 'p1', VAR_O_23_34), []), flat_map([], 'p1', []), append([], [], [])])
step(findall(VAR_O_23_34, t('missing', 'p1', VAR_O_23_34), []), 'collected', {}, [])
step(flat_map(['s1'], 'p2', []), clause(8), {'S': 's1', 'Subjects': [], 'P': 'p2', 'Objects': [], 'O': VAR_O_23_41, 'Here': [], 'Rest': []}, [findall(VAR_O_23_41, t('s1', 'p2', VAR_O_23_41), []), flat_map([], 'p2', []), append([], [], [])])
step(findall(VAR_O_23_41, t('s1', 'p2', VAR_O_23_41), []), 'collected', {}, [])
step(flat_map([], 'p2', []), clause(7), {'__anon0': 'p2'}, [])
