flat_map(['s1', 's2', 's3'], 'p1', ['o1', 'o2', 'o3', 'o4'])
flat_map(['missing'], 'p1', [])
flat_map(['s1'], 'p2', [])

clause(5, fact(append([], Ys, Ys)))
clause(6, implied_by(append([X, *Xs], Ys, [X, *Zs]), append(Xs, Ys, Zs)))
clause(7, fact(flat_map([], _0, [])))
clause(8, implied_by(flat_map([S, *Subjects], P, Objects), findall(O, t(S, P, O), Here) & flat_map(Subjects, P, Rest) & append(Here, Rest, Objects)))

step(flat_map(['s1', 's2', 's3'], 'p1', ['o1', 'o2', 'o3', 'o4']), clause(8), {'S': 's1', 'Subjects': ['s2', 's3'], 'P': 'p1', 'Objects': ['o1', 'o2', 'o3', 'o4'], 'O': A, 'Here': ['o1'], 'Rest': ['o2', 'o3', 'o4']}, [findall(A, t('s1', 'p1', A), ['o1']), flat_map(['s2', 's3'], 'p1', ['o2', 'o3', 'o4']), append(['o1'], ['o2', 'o3', 'o4'], ['o1', 'o2', 'o3', 'o4'])])
step(findall(A, t('s1', 'p1', A), ['o1']), 'collected', {}, [])
step(flat_map(['s2', 's3'], 'p1', ['o2', 'o3', 'o4']), clause(8), {'S': 's2', 'Subjects': ['s3'], 'P': 'p1', 'Objects': ['o2', 'o3', 'o4'], 'O': B, 'Here': ['o2'], 'Rest': ['o3', 'o4']}, [findall(B, t('s2', 'p1', B), ['o2']), flat_map(['s3'], 'p1', ['o3', 'o4']), append(['o2'], ['o3', 'o4'], ['o2', 'o3', 'o4'])])
step(findall(B, t('s2', 'p1', B), ['o2']), 'collected', {}, [])
step(flat_map(['s3'], 'p1', ['o3', 'o4']), clause(8), {'S': 's3', 'Subjects': [], 'P': 'p1', 'Objects': ['o3', 'o4'], 'O': C, 'Here': ['o3', 'o4'], 'Rest': []}, [findall(C, t('s3', 'p1', C), ['o3', 'o4']), flat_map([], 'p1', []), append(['o3', 'o4'], [], ['o3', 'o4'])])
step(findall(C, t('s3', 'p1', C), ['o3', 'o4']), 'collected', {}, [])
step(flat_map([], 'p1', []), clause(7), {'_0': 'p1'}, [])
step(append(['o3', 'o4'], [], ['o3', 'o4']), clause(6), {'X': 'o3', 'Xs': ['o4'], 'Ys': [], 'Zs': ['o4']}, [append(['o4'], [], ['o4'])])
step(append(['o4'], [], ['o4']), clause(6), {'X': 'o4', 'Xs': [], 'Ys': [], 'Zs': []}, [append([], [], [])])
step(append([], [], []), clause(5), {'Ys': []}, [])
step(append(['o2'], ['o3', 'o4'], ['o2', 'o3', 'o4']), clause(6), {'X': 'o2', 'Xs': [], 'Ys': ['o3', 'o4'], 'Zs': ['o3', 'o4']}, [append([], ['o3', 'o4'], ['o3', 'o4'])])
step(append([], ['o3', 'o4'], ['o3', 'o4']), clause(5), {'Ys': ['o3', 'o4']}, [])
step(append(['o1'], ['o2', 'o3', 'o4'], ['o1', 'o2', 'o3', 'o4']), clause(6), {'X': 'o1', 'Xs': [], 'Ys': ['o2', 'o3', 'o4'], 'Zs': ['o2', 'o3', 'o4']}, [append([], ['o2', 'o3', 'o4'], ['o2', 'o3', 'o4'])])
step(append([], ['o2', 'o3', 'o4'], ['o2', 'o3', 'o4']), clause(5), {'Ys': ['o2', 'o3', 'o4']}, [])
step(flat_map(['missing'], 'p1', []), clause(8), {'S': 'missing', 'Subjects': [], 'P': 'p1', 'Objects': [], 'O': D, 'Here': [], 'Rest': []}, [findall(D, t('missing', 'p1', D), []), flat_map([], 'p1', []), append([], [], [])])
step(findall(D, t('missing', 'p1', D), []), 'collected', {}, [])
step(flat_map(['s1'], 'p2', []), clause(8), {'S': 's1', 'Subjects': [], 'P': 'p2', 'Objects': [], 'O': E, 'Here': [], 'Rest': []}, [findall(E, t('s1', 'p2', E), []), flat_map([], 'p2', []), append([], [], [])])
step(findall(E, t('s1', 'p2', E), []), 'collected', {}, [])
step(flat_map([], 'p2', []), clause(7), {'_0': 'p2'}, [])
