t('bob', 'child_of', 'alice')
t('carol', 'child_of', 'alice')
allowed('carol')
children('alice', ['bob', 'carol'])

clause(1, fact(base('alice', 'parent_of', 'bob')))
clause(2, fact(base('alice', 'parent_of', 'carol')))
clause(4, backward(t(S, P, O), base(S, P, O)))
clause(5, forward(t(C, 'child_of', P), t(P, 'parent_of', C)))
clause(6, forward(allowed(C), t(C, 'child_of', 'alice'), ~t(C, 'blocked', 'true')))
clause(7, forward(children(P, Children), base(P, 'parent_of', _0), findall(C, t(C, 'child_of', P), Children)))

step(t('bob', 'child_of', 'alice'), clause(5), {'C': 'bob', 'P': 'alice'}, [t('alice', 'parent_of', 'bob')])
step(t('alice', 'parent_of', 'bob'), clause(4), {'S': 'alice', 'P': 'parent_of', 'O': 'bob'}, [base('alice', 'parent_of', 'bob')])
step(base('alice', 'parent_of', 'bob'), clause(1), {}, [])
step(t('carol', 'child_of', 'alice'), clause(5), {'C': 'carol', 'P': 'alice'}, [t('alice', 'parent_of', 'carol')])
step(t('alice', 'parent_of', 'carol'), clause(4), {'S': 'alice', 'P': 'parent_of', 'O': 'carol'}, [base('alice', 'parent_of', 'carol')])
step(base('alice', 'parent_of', 'carol'), clause(2), {}, [])
step(allowed('carol'), clause(6), {'C': 'carol'}, [t('carol', 'child_of', 'alice'), ~t('carol', 'blocked', 'true')])
step(~t('carol', 'blocked', 'true'), 'absent', {}, [])
step(children('alice', ['bob', 'carol']), clause(7), {'P': 'alice', 'Children': ['bob', 'carol'], '_0': 'bob', 'C': A}, [base('alice', 'parent_of', 'bob'), findall(A, t(A, 'child_of', 'alice'), ['bob', 'carol'])])
step(findall(A, t(A, 'child_of', 'alice'), ['bob', 'carol']), 'collected', {}, [])
