append(['a', 'b'], ['c', 'd'], ['a', 'b', 'c', 'd'])
squares([1, 2, 3, 4], [1, 4, 9, 16])
sum([1, 2, 3, 4], 10)

clause(1, fact(append([], Ys, Ys)))
clause(2, backward(append([X, *Xs], Ys, [X, *Zs]), append(Xs, Ys, Zs)))
clause(3, fact(squares([], [])))
clause(4, backward(squares([X, *Xs], [Y, *Ys]), is_(Y, X * X), squares(Xs, Ys)))
clause(5, fact(sum([], 0)))
clause(6, backward(sum([X, *Xs], Total), sum(Xs, Rest), is_(Total, X + Rest)))

step(append(['a', 'b'], ['c', 'd'], ['a', 'b', 'c', 'd']), clause(2), {'X': 'a', 'Xs': ['b'], 'Ys': ['c', 'd'], 'Zs': ['b', 'c', 'd']}, [append(['b'], ['c', 'd'], ['b', 'c', 'd'])])
step(append(['b'], ['c', 'd'], ['b', 'c', 'd']), clause(2), {'X': 'b', 'Xs': [], 'Ys': ['c', 'd'], 'Zs': ['c', 'd']}, [append([], ['c', 'd'], ['c', 'd'])])
step(append([], ['c', 'd'], ['c', 'd']), clause(1), {'Ys': ['c', 'd']}, [])
step(squares([1, 2, 3, 4], [1, 4, 9, 16]), clause(4), {'X': 1, 'Xs': [2, 3, 4], 'Y': 1, 'Ys': [4, 9, 16]}, [is_(1, 1 * 1), squares([2, 3, 4], [4, 9, 16])])
step(is_(1, 1 * 1), 'builtin', {}, [])
step(squares([2, 3, 4], [4, 9, 16]), clause(4), {'X': 2, 'Xs': [3, 4], 'Y': 4, 'Ys': [9, 16]}, [is_(4, 2 * 2), squares([3, 4], [9, 16])])
step(is_(4, 2 * 2), 'builtin', {}, [])
step(squares([3, 4], [9, 16]), clause(4), {'X': 3, 'Xs': [4], 'Y': 9, 'Ys': [16]}, [is_(9, 3 * 3), squares([4], [16])])
step(is_(9, 3 * 3), 'builtin', {}, [])
step(squares([4], [16]), clause(4), {'X': 4, 'Xs': [], 'Y': 16, 'Ys': []}, [is_(16, 4 * 4), squares([], [])])
step(is_(16, 4 * 4), 'builtin', {}, [])
step(squares([], []), clause(3), {}, [])
step(sum([1, 2, 3, 4], 10), clause(6), {'X': 1, 'Xs': [2, 3, 4], 'Total': 10, 'Rest': 9}, [sum([2, 3, 4], 9), is_(10, 1 + 9)])
step(sum([2, 3, 4], 9), clause(6), {'X': 2, 'Xs': [3, 4], 'Total': 9, 'Rest': 7}, [sum([3, 4], 7), is_(9, 2 + 7)])
step(sum([3, 4], 7), clause(6), {'X': 3, 'Xs': [4], 'Total': 7, 'Rest': 4}, [sum([4], 4), is_(7, 3 + 4)])
step(sum([4], 4), clause(6), {'X': 4, 'Xs': [], 'Total': 4, 'Rest': 0}, [sum([], 0), is_(4, 4 + 0)])
step(sum([], 0), clause(5), {}, [])
step(is_(4, 4 + 0), 'builtin', {}, [])
step(is_(7, 3 + 4), 'builtin', {}, [])
step(is_(9, 2 + 7), 'builtin', {}, [])
step(is_(10, 1 + 9), 'builtin', {}, [])
