plan([go('loc3'), push('loc1'), 'climb_on', 'grab'])
plan([go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab'])
plan([go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off'])
plan([go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab'])

clause(1, backward(reaches_goal(Moves), initial_state(I), goal_state(G), reachable(I, Moves, G)))
clause(2, fact(reachable(S, [], S)))
clause(3, backward(reachable(S1, [M, *Rest], S3), legal_move(S1, M, S2), reachable(S2, Rest, S3)))
clause(4, fact(initial_state(['loc1', 'loc2', 'loc3', 'n', 'n'])))
clause(5, fact(goal_state([__anon0, __anon1, __anon2, __anon3, 'y'])))
clause(6, fact(legal_move([B, M, M, 'n', H], 'climb_on', [B, M, M, 'y', H])))
clause(7, fact(legal_move([B, M, M, 'y', H], 'climb_off', [B, M, M, 'n', H])))
clause(8, fact(legal_move([B, B, B, 'y', 'n'], 'grab', [B, B, B, 'y', 'y'])))
clause(9, backward(legal_move([B, M, M, 'n', H], push(X), [B, X, X, 'n', H]), location(X), not_unify(X, M)))
clause(10, backward(legal_move([B, M, L, 'n', H], go(X), [B, X, L, 'n', H]), location(X), not_unify(X, M)))
clause(11, fact(location('loc1')))
clause(12, fact(location('loc2')))
clause(13, fact(location('loc3')))
clause(14, fact(moves(0, [])))
clause(15, backward(moves(N, [__anon4, *Rest]), N > 0, is_(M, N - 1), moves(M, Rest)))
clause(16, backward(in_range(Low, High, Low), Low <= High))
clause(17, backward(in_range(Low, High, N), Low < High, is_(Next, Low + 1), in_range(Next, High, N)))
clause(18, forward(plan(Moves), in_range(1, 5, N), moves(N, Moves), reaches_goal(Moves)))

step(plan([go('loc3'), push('loc1'), 'climb_on', 'grab']), clause(18), {'Moves': [go('loc3'), push('loc1'), 'climb_on', 'grab'], 'N': 4}, [in_range(1, 5, 4), moves(4, [go('loc3'), push('loc1'), 'climb_on', 'grab']), reaches_goal([go('loc3'), push('loc1'), 'climb_on', 'grab'])])
step(in_range(1, 5, 4), clause(17), {'Low': 1, 'High': 5, 'N': 4, 'Next': 2}, [1 < 5, is_(2, 1 + 1), in_range(2, 5, 4)])
step(1 < 5, 'builtin', {}, [])
step(is_(2, 1 + 1), 'builtin', {}, [])
step(in_range(2, 5, 4), clause(17), {'Low': 2, 'High': 5, 'N': 4, 'Next': 3}, [2 < 5, is_(3, 2 + 1), in_range(3, 5, 4)])
step(2 < 5, 'builtin', {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(in_range(3, 5, 4), clause(17), {'Low': 3, 'High': 5, 'N': 4, 'Next': 4}, [3 < 5, is_(4, 3 + 1), in_range(4, 5, 4)])
step(3 < 5, 'builtin', {}, [])
step(is_(4, 3 + 1), 'builtin', {}, [])
step(in_range(4, 5, 4), clause(16), {'Low': 4, 'High': 5}, [4 <= 5])
step(4 <= 5, 'builtin', {}, [])
step(moves(4, [go('loc3'), push('loc1'), 'climb_on', 'grab']), clause(15), {'N': 4, '__anon4': go('loc3'), 'Rest': [push('loc1'), 'climb_on', 'grab'], 'M': 3}, [4 > 0, is_(3, 4 - 1), moves(3, [push('loc1'), 'climb_on', 'grab'])])
step(4 > 0, 'builtin', {}, [])
step(is_(3, 4 - 1), 'builtin', {}, [])
step(moves(3, [push('loc1'), 'climb_on', 'grab']), clause(15), {'N': 3, '__anon4': push('loc1'), 'Rest': ['climb_on', 'grab'], 'M': 2}, [3 > 0, is_(2, 3 - 1), moves(2, ['climb_on', 'grab'])])
step(3 > 0, 'builtin', {}, [])
step(is_(2, 3 - 1), 'builtin', {}, [])
step(moves(2, ['climb_on', 'grab']), clause(15), {'N': 2, '__anon4': 'climb_on', 'Rest': ['grab'], 'M': 1}, [2 > 0, is_(1, 2 - 1), moves(1, ['grab'])])
step(2 > 0, 'builtin', {}, [])
step(is_(1, 2 - 1), 'builtin', {}, [])
step(moves(1, ['grab']), clause(15), {'N': 1, '__anon4': 'grab', 'Rest': [], 'M': 0}, [1 > 0, is_(0, 1 - 1), moves(0, [])])
step(1 > 0, 'builtin', {}, [])
step(is_(0, 1 - 1), 'builtin', {}, [])
step(moves(0, []), clause(14), {}, [])
step(reaches_goal([go('loc3'), push('loc1'), 'climb_on', 'grab']), clause(1), {'Moves': [go('loc3'), push('loc1'), 'climb_on', 'grab'], 'I': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'G': ['loc1', 'loc1', 'loc1', 'y', 'y']}, [initial_state(['loc1', 'loc2', 'loc3', 'n', 'n']), goal_state(['loc1', 'loc1', 'loc1', 'y', 'y']), reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc3'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(initial_state(['loc1', 'loc2', 'loc3', 'n', 'n']), clause(4), {}, [])
step(goal_state(['loc1', 'loc1', 'loc1', 'y', 'y']), clause(5), {'__anon0': 'loc1', '__anon1': 'loc1', '__anon2': 'loc1', '__anon3': 'y'}, [])
step(reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc3'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'M': go('loc3'), 'Rest': [push('loc1'), 'climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc3', 'loc3', 'n', 'n']}, [legal_move(['loc1', 'loc2', 'loc3', 'n', 'n'], go('loc3'), ['loc1', 'loc3', 'loc3', 'n', 'n']), reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc2', 'loc3', 'n', 'n'], go('loc3'), ['loc1', 'loc3', 'loc3', 'n', 'n']), clause(10), {'B': 'loc1', 'M': 'loc2', 'L': 'loc3', 'H': 'n', 'X': 'loc3'}, [location('loc3'), not_unify('loc3', 'loc2')])
step(location('loc3'), clause(13), {}, [])
step(not_unify('loc3', 'loc2'), 'builtin', {}, [])
step(reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc3', 'loc3', 'n', 'n'], 'M': push('loc1'), 'Rest': ['climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'n', 'n']}, [legal_move(['loc1', 'loc3', 'loc3', 'n', 'n'], push('loc1'), ['loc1', 'loc1', 'loc1', 'n', 'n']), reachable(['loc1', 'loc1', 'loc1', 'n', 'n'], ['climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc3', 'loc3', 'n', 'n'], push('loc1'), ['loc1', 'loc1', 'loc1', 'n', 'n']), clause(9), {'B': 'loc1', 'M': 'loc3', 'H': 'n', 'X': 'loc1'}, [location('loc1'), not_unify('loc1', 'loc3')])
step(location('loc1'), clause(11), {}, [])
step(not_unify('loc1', 'loc3'), 'builtin', {}, [])
step(reachable(['loc1', 'loc1', 'loc1', 'n', 'n'], ['climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc1', 'loc1', 'n', 'n'], 'M': 'climb_on', 'Rest': ['grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'y', 'n']}, [legal_move(['loc1', 'loc1', 'loc1', 'n', 'n'], 'climb_on', ['loc1', 'loc1', 'loc1', 'y', 'n']), reachable(['loc1', 'loc1', 'loc1', 'y', 'n'], ['grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc1', 'loc1', 'n', 'n'], 'climb_on', ['loc1', 'loc1', 'loc1', 'y', 'n']), clause(6), {'B': 'loc1', 'M': 'loc1', 'H': 'n'}, [])
step(reachable(['loc1', 'loc1', 'loc1', 'y', 'n'], ['grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc1', 'loc1', 'y', 'n'], 'M': 'grab', 'Rest': [], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'y', 'y']}, [legal_move(['loc1', 'loc1', 'loc1', 'y', 'n'], 'grab', ['loc1', 'loc1', 'loc1', 'y', 'y']), reachable(['loc1', 'loc1', 'loc1', 'y', 'y'], [], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc1', 'loc1', 'y', 'n'], 'grab', ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(8), {'B': 'loc1'}, [])
step(reachable(['loc1', 'loc1', 'loc1', 'y', 'y'], [], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(2), {'S': ['loc1', 'loc1', 'loc1', 'y', 'y']}, [])
step(plan([go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab']), clause(18), {'Moves': [go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab'], 'N': 5}, [in_range(1, 5, 5), moves(5, [go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab']), reaches_goal([go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab'])])
step(in_range(1, 5, 5), clause(17), {'Low': 1, 'High': 5, 'N': 5, 'Next': 2}, [1 < 5, is_(2, 1 + 1), in_range(2, 5, 5)])
step(in_range(2, 5, 5), clause(17), {'Low': 2, 'High': 5, 'N': 5, 'Next': 3}, [2 < 5, is_(3, 2 + 1), in_range(3, 5, 5)])
step(in_range(3, 5, 5), clause(17), {'Low': 3, 'High': 5, 'N': 5, 'Next': 4}, [3 < 5, is_(4, 3 + 1), in_range(4, 5, 5)])
step(in_range(4, 5, 5), clause(17), {'Low': 4, 'High': 5, 'N': 5, 'Next': 5}, [4 < 5, is_(5, 4 + 1), in_range(5, 5, 5)])
step(4 < 5, 'builtin', {}, [])
step(is_(5, 4 + 1), 'builtin', {}, [])
step(in_range(5, 5, 5), clause(16), {'Low': 5, 'High': 5}, [5 <= 5])
step(5 <= 5, 'builtin', {}, [])
step(moves(5, [go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab']), clause(15), {'N': 5, '__anon4': go('loc1'), 'Rest': [go('loc3'), push('loc1'), 'climb_on', 'grab'], 'M': 4}, [5 > 0, is_(4, 5 - 1), moves(4, [go('loc3'), push('loc1'), 'climb_on', 'grab'])])
step(5 > 0, 'builtin', {}, [])
step(is_(4, 5 - 1), 'builtin', {}, [])
step(reaches_goal([go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab']), clause(1), {'Moves': [go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab'], 'I': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'G': ['loc1', 'loc1', 'loc1', 'y', 'y']}, [initial_state(['loc1', 'loc2', 'loc3', 'n', 'n']), goal_state(['loc1', 'loc1', 'loc1', 'y', 'y']), reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc1'), go('loc3'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'M': go('loc1'), 'Rest': [go('loc3'), push('loc1'), 'climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc1', 'loc3', 'n', 'n']}, [legal_move(['loc1', 'loc2', 'loc3', 'n', 'n'], go('loc1'), ['loc1', 'loc1', 'loc3', 'n', 'n']), reachable(['loc1', 'loc1', 'loc3', 'n', 'n'], [go('loc3'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc2', 'loc3', 'n', 'n'], go('loc1'), ['loc1', 'loc1', 'loc3', 'n', 'n']), clause(10), {'B': 'loc1', 'M': 'loc2', 'L': 'loc3', 'H': 'n', 'X': 'loc1'}, [location('loc1'), not_unify('loc1', 'loc2')])
step(not_unify('loc1', 'loc2'), 'builtin', {}, [])
step(reachable(['loc1', 'loc1', 'loc3', 'n', 'n'], [go('loc3'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc1', 'loc3', 'n', 'n'], 'M': go('loc3'), 'Rest': [push('loc1'), 'climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc3', 'loc3', 'n', 'n']}, [legal_move(['loc1', 'loc1', 'loc3', 'n', 'n'], go('loc3'), ['loc1', 'loc3', 'loc3', 'n', 'n']), reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc1', 'loc3', 'n', 'n'], go('loc3'), ['loc1', 'loc3', 'loc3', 'n', 'n']), clause(10), {'B': 'loc1', 'M': 'loc1', 'L': 'loc3', 'H': 'n', 'X': 'loc3'}, [location('loc3'), not_unify('loc3', 'loc1')])
step(not_unify('loc3', 'loc1'), 'builtin', {}, [])
step(plan([go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off']), clause(18), {'Moves': [go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off'], 'N': 5}, [in_range(1, 5, 5), moves(5, [go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off']), reaches_goal([go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off'])])
step(moves(5, [go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off']), clause(15), {'N': 5, '__anon4': go('loc3'), 'Rest': [push('loc1'), 'climb_on', 'grab', 'climb_off'], 'M': 4}, [5 > 0, is_(4, 5 - 1), moves(4, [push('loc1'), 'climb_on', 'grab', 'climb_off'])])
step(moves(4, [push('loc1'), 'climb_on', 'grab', 'climb_off']), clause(15), {'N': 4, '__anon4': push('loc1'), 'Rest': ['climb_on', 'grab', 'climb_off'], 'M': 3}, [4 > 0, is_(3, 4 - 1), moves(3, ['climb_on', 'grab', 'climb_off'])])
step(moves(3, ['climb_on', 'grab', 'climb_off']), clause(15), {'N': 3, '__anon4': 'climb_on', 'Rest': ['grab', 'climb_off'], 'M': 2}, [3 > 0, is_(2, 3 - 1), moves(2, ['grab', 'climb_off'])])
step(moves(2, ['grab', 'climb_off']), clause(15), {'N': 2, '__anon4': 'grab', 'Rest': ['climb_off'], 'M': 1}, [2 > 0, is_(1, 2 - 1), moves(1, ['climb_off'])])
step(moves(1, ['climb_off']), clause(15), {'N': 1, '__anon4': 'climb_off', 'Rest': [], 'M': 0}, [1 > 0, is_(0, 1 - 1), moves(0, [])])
step(reaches_goal([go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off']), clause(1), {'Moves': [go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off'], 'I': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'G': ['loc1', 'loc1', 'loc1', 'n', 'y']}, [initial_state(['loc1', 'loc2', 'loc3', 'n', 'n']), goal_state(['loc1', 'loc1', 'loc1', 'n', 'y']), reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y'])])
step(goal_state(['loc1', 'loc1', 'loc1', 'n', 'y']), clause(5), {'__anon0': 'loc1', '__anon1': 'loc1', '__anon2': 'loc1', '__anon3': 'n'}, [])
step(reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc3'), push('loc1'), 'climb_on', 'grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(3), {'S1': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'M': go('loc3'), 'Rest': [push('loc1'), 'climb_on', 'grab', 'climb_off'], 'S3': ['loc1', 'loc1', 'loc1', 'n', 'y'], 'S2': ['loc1', 'loc3', 'loc3', 'n', 'n']}, [legal_move(['loc1', 'loc2', 'loc3', 'n', 'n'], go('loc3'), ['loc1', 'loc3', 'loc3', 'n', 'n']), reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc1'), 'climb_on', 'grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y'])])
step(reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc1'), 'climb_on', 'grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(3), {'S1': ['loc1', 'loc3', 'loc3', 'n', 'n'], 'M': push('loc1'), 'Rest': ['climb_on', 'grab', 'climb_off'], 'S3': ['loc1', 'loc1', 'loc1', 'n', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'n', 'n']}, [legal_move(['loc1', 'loc3', 'loc3', 'n', 'n'], push('loc1'), ['loc1', 'loc1', 'loc1', 'n', 'n']), reachable(['loc1', 'loc1', 'loc1', 'n', 'n'], ['climb_on', 'grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y'])])
step(reachable(['loc1', 'loc1', 'loc1', 'n', 'n'], ['climb_on', 'grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(3), {'S1': ['loc1', 'loc1', 'loc1', 'n', 'n'], 'M': 'climb_on', 'Rest': ['grab', 'climb_off'], 'S3': ['loc1', 'loc1', 'loc1', 'n', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'y', 'n']}, [legal_move(['loc1', 'loc1', 'loc1', 'n', 'n'], 'climb_on', ['loc1', 'loc1', 'loc1', 'y', 'n']), reachable(['loc1', 'loc1', 'loc1', 'y', 'n'], ['grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y'])])
step(reachable(['loc1', 'loc1', 'loc1', 'y', 'n'], ['grab', 'climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(3), {'S1': ['loc1', 'loc1', 'loc1', 'y', 'n'], 'M': 'grab', 'Rest': ['climb_off'], 'S3': ['loc1', 'loc1', 'loc1', 'n', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'y', 'y']}, [legal_move(['loc1', 'loc1', 'loc1', 'y', 'n'], 'grab', ['loc1', 'loc1', 'loc1', 'y', 'y']), reachable(['loc1', 'loc1', 'loc1', 'y', 'y'], ['climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y'])])
step(reachable(['loc1', 'loc1', 'loc1', 'y', 'y'], ['climb_off'], ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(3), {'S1': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'M': 'climb_off', 'Rest': [], 'S3': ['loc1', 'loc1', 'loc1', 'n', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'n', 'y']}, [legal_move(['loc1', 'loc1', 'loc1', 'y', 'y'], 'climb_off', ['loc1', 'loc1', 'loc1', 'n', 'y']), reachable(['loc1', 'loc1', 'loc1', 'n', 'y'], [], ['loc1', 'loc1', 'loc1', 'n', 'y'])])
step(legal_move(['loc1', 'loc1', 'loc1', 'y', 'y'], 'climb_off', ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(7), {'B': 'loc1', 'M': 'loc1', 'H': 'y'}, [])
step(reachable(['loc1', 'loc1', 'loc1', 'n', 'y'], [], ['loc1', 'loc1', 'loc1', 'n', 'y']), clause(2), {'S': ['loc1', 'loc1', 'loc1', 'n', 'y']}, [])
step(plan([go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab']), clause(18), {'Moves': [go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab'], 'N': 5}, [in_range(1, 5, 5), moves(5, [go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab']), reaches_goal([go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab'])])
step(moves(5, [go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab']), clause(15), {'N': 5, '__anon4': go('loc3'), 'Rest': [push('loc2'), push('loc1'), 'climb_on', 'grab'], 'M': 4}, [5 > 0, is_(4, 5 - 1), moves(4, [push('loc2'), push('loc1'), 'climb_on', 'grab'])])
step(moves(4, [push('loc2'), push('loc1'), 'climb_on', 'grab']), clause(15), {'N': 4, '__anon4': push('loc2'), 'Rest': [push('loc1'), 'climb_on', 'grab'], 'M': 3}, [4 > 0, is_(3, 4 - 1), moves(3, [push('loc1'), 'climb_on', 'grab'])])
step(reaches_goal([go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab']), clause(1), {'Moves': [go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab'], 'I': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'G': ['loc1', 'loc1', 'loc1', 'y', 'y']}, [initial_state(['loc1', 'loc2', 'loc3', 'n', 'n']), goal_state(['loc1', 'loc1', 'loc1', 'y', 'y']), reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(reachable(['loc1', 'loc2', 'loc3', 'n', 'n'], [go('loc3'), push('loc2'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc2', 'loc3', 'n', 'n'], 'M': go('loc3'), 'Rest': [push('loc2'), push('loc1'), 'climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc3', 'loc3', 'n', 'n']}, [legal_move(['loc1', 'loc2', 'loc3', 'n', 'n'], go('loc3'), ['loc1', 'loc3', 'loc3', 'n', 'n']), reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc2'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(reachable(['loc1', 'loc3', 'loc3', 'n', 'n'], [push('loc2'), push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc3', 'loc3', 'n', 'n'], 'M': push('loc2'), 'Rest': [push('loc1'), 'climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc2', 'loc2', 'n', 'n']}, [legal_move(['loc1', 'loc3', 'loc3', 'n', 'n'], push('loc2'), ['loc1', 'loc2', 'loc2', 'n', 'n']), reachable(['loc1', 'loc2', 'loc2', 'n', 'n'], [push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc3', 'loc3', 'n', 'n'], push('loc2'), ['loc1', 'loc2', 'loc2', 'n', 'n']), clause(9), {'B': 'loc1', 'M': 'loc3', 'H': 'n', 'X': 'loc2'}, [location('loc2'), not_unify('loc2', 'loc3')])
step(location('loc2'), clause(12), {}, [])
step(not_unify('loc2', 'loc3'), 'builtin', {}, [])
step(reachable(['loc1', 'loc2', 'loc2', 'n', 'n'], [push('loc1'), 'climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y']), clause(3), {'S1': ['loc1', 'loc2', 'loc2', 'n', 'n'], 'M': push('loc1'), 'Rest': ['climb_on', 'grab'], 'S3': ['loc1', 'loc1', 'loc1', 'y', 'y'], 'S2': ['loc1', 'loc1', 'loc1', 'n', 'n']}, [legal_move(['loc1', 'loc2', 'loc2', 'n', 'n'], push('loc1'), ['loc1', 'loc1', 'loc1', 'n', 'n']), reachable(['loc1', 'loc1', 'loc1', 'n', 'n'], ['climb_on', 'grab'], ['loc1', 'loc1', 'loc1', 'y', 'y'])])
step(legal_move(['loc1', 'loc2', 'loc2', 'n', 'n'], push('loc1'), ['loc1', 'loc1', 'loc1', 'n', 'n']), clause(9), {'B': 'loc1', 'M': 'loc2', 'H': 'n', 'X': 'loc1'}, [location('loc1'), not_unify('loc1', 'loc2')])
