flies('tweety', 'true')
flies('falco', 'true')
flies('mythic', 'true')
wings('tweety', 'true')
wings('falco', 'true')
wings('mythic', 'true')
flies('tweety', 'false')
flies('opus', 'false')
wings('batsy', 'false')
flies('batsy', 'true')
wings('batsy', 'true')
swims('nemo', 'true')
wings('nemo', 'false')
flies('mythic', 'false')
flight_status('tweety', 'both')
flight_status('mythic', 'both')
wing_status('batsy', 'both')
inconsistent('tweety', 'flies')
needs_review('tweety', 'flies')
inconsistent('mythic', 'flies')
needs_review('mythic', 'flies')
inconsistent('batsy', 'wings')
needs_review('batsy', 'wings')
flies_safely('tweety', 'undecided')
flies_safely('mythic', 'undecided')
wings_safely('batsy', 'undecided')
moves_by('tweety', 'unknown')
migrates('tweety', 'undecided')
moves_by('mythic', 'unknown')
migrates('mythic', 'undecided')
flight_status('falco', 'true_only')
flight_status('batsy', 'true_only')
flight_status('opus', 'false_only')
wing_status('tweety', 'true_only')
wing_status('falco', 'true_only')
wing_status('mythic', 'true_only')
wing_status('nemo', 'false_only')
flies_safely('falco', 'true')
flies_safely('batsy', 'true')
flies_safely('opus', 'false')
wings_safely('tweety', 'true')
wings_safely('falco', 'true')
wings_safely('mythic', 'true')
wings_safely('nemo', 'false')
moves_by('falco', 'flying')
migrates('falco', 'true')
moves_by('batsy', 'flying')
migrates('batsy', 'true')
moves_by('opus', 'walking')
migrates('opus', 'false')

clause(1, fact(bird('tweety')))
clause(2, fact(penguin('tweety')))
clause(3, fact(bird('falco')))
clause(4, fact(penguin('opus')))
clause(5, fact(mammal('batsy')))
clause(6, fact(bat('batsy')))
clause(7, fact(fish('nemo')))
clause(8, fact(bird('mythic')))
clause(9, fact(observed('mythic', 'flies', 'false')))
clause(10, forward(flies(X, 'true'), bird(X)))
clause(11, forward(wings(X, 'true'), bird(X)))
clause(12, forward(flies(X, 'false'), penguin(X)))
clause(13, forward(wings(X, 'false'), mammal(X)))
clause(14, forward(flies(X, 'true') & wings(X, 'true'), bat(X)))
clause(15, forward(swims(X, 'true') & wings(X, 'false'), fish(X)))
clause(16, forward(flies(X, Value), observed(X, 'flies', Value)))
clause(17, forward(flight_status(X, 'both'), flies(X, 'true'), flies(X, 'false')))
clause(18, forward(flight_status(X, 'true_only'), flies(X, 'true'), ~flies(X, 'false')))
clause(19, forward(flight_status(X, 'false_only'), flies(X, 'false'), ~flies(X, 'true')))
clause(20, forward(wing_status(X, 'both'), wings(X, 'true'), wings(X, 'false')))
clause(21, forward(wing_status(X, 'true_only'), wings(X, 'true'), ~wings(X, 'false')))
clause(22, forward(wing_status(X, 'false_only'), wings(X, 'false'), ~wings(X, 'true')))
clause(23, forward(inconsistent(X, 'flies') & needs_review(X, 'flies'), flight_status(X, 'both')))
clause(24, forward(inconsistent(X, 'wings') & needs_review(X, 'wings'), wing_status(X, 'both')))
clause(25, forward(flies_safely(X, 'true'), flight_status(X, 'true_only')))
clause(26, forward(flies_safely(X, 'false'), flight_status(X, 'false_only')))
clause(27, forward(flies_safely(X, 'undecided'), flight_status(X, 'both')))
clause(28, forward(wings_safely(X, 'true'), wing_status(X, 'true_only')))
clause(29, forward(wings_safely(X, 'false'), wing_status(X, 'false_only')))
clause(30, forward(wings_safely(X, 'undecided'), wing_status(X, 'both')))
clause(31, forward(moves_by(X, 'flying') & migrates(X, 'true'), flight_status(X, 'true_only')))
clause(32, forward(moves_by(X, 'walking') & migrates(X, 'false'), flight_status(X, 'false_only')))
clause(33, forward(moves_by(X, 'unknown') & migrates(X, 'undecided'), flight_status(X, 'both')))

step(flies('tweety', 'true'), rule(10), {'X': 'tweety'}, [bird('tweety')])
step(bird('tweety'), fact(1), {}, [])
step(flies('falco', 'true'), rule(10), {'X': 'falco'}, [bird('falco')])
step(bird('falco'), fact(3), {}, [])
step(flies('mythic', 'true'), rule(10), {'X': 'mythic'}, [bird('mythic')])
step(bird('mythic'), fact(8), {}, [])
step(wings('tweety', 'true'), rule(11), {'X': 'tweety'}, [bird('tweety')])
step(wings('falco', 'true'), rule(11), {'X': 'falco'}, [bird('falco')])
step(wings('mythic', 'true'), rule(11), {'X': 'mythic'}, [bird('mythic')])
step(flies('tweety', 'false'), rule(12), {'X': 'tweety'}, [penguin('tweety')])
step(penguin('tweety'), fact(2), {}, [])
step(flies('opus', 'false'), rule(12), {'X': 'opus'}, [penguin('opus')])
step(penguin('opus'), fact(4), {}, [])
step(wings('batsy', 'false'), rule(13), {'X': 'batsy'}, [mammal('batsy')])
step(mammal('batsy'), fact(5), {}, [])
step(flies('batsy', 'true'), rule(14), {'X': 'batsy'}, [bat('batsy')])
step(bat('batsy'), fact(6), {}, [])
step(wings('batsy', 'true'), rule(14), {'X': 'batsy'}, [bat('batsy')])
step(swims('nemo', 'true'), rule(15), {'X': 'nemo'}, [fish('nemo')])
step(fish('nemo'), fact(7), {}, [])
step(wings('nemo', 'false'), rule(15), {'X': 'nemo'}, [fish('nemo')])
step(flies('mythic', 'false'), rule(16), {'X': 'mythic', 'Value': 'false'}, [observed('mythic', 'flies', 'false')])
step(observed('mythic', 'flies', 'false'), fact(9), {}, [])
step(flight_status('tweety', 'both'), rule(17), {'X': 'tweety'}, [flies('tweety', 'true'), flies('tweety', 'false')])
step(flight_status('mythic', 'both'), rule(17), {'X': 'mythic'}, [flies('mythic', 'true'), flies('mythic', 'false')])
step(wing_status('batsy', 'both'), rule(20), {'X': 'batsy'}, [wings('batsy', 'true'), wings('batsy', 'false')])
step(inconsistent('tweety', 'flies'), rule(23), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(needs_review('tweety', 'flies'), rule(23), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(inconsistent('mythic', 'flies'), rule(23), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(needs_review('mythic', 'flies'), rule(23), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(inconsistent('batsy', 'wings'), rule(24), {'X': 'batsy'}, [wing_status('batsy', 'both')])
step(needs_review('batsy', 'wings'), rule(24), {'X': 'batsy'}, [wing_status('batsy', 'both')])
step(flies_safely('tweety', 'undecided'), rule(27), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(flies_safely('mythic', 'undecided'), rule(27), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(wings_safely('batsy', 'undecided'), rule(30), {'X': 'batsy'}, [wing_status('batsy', 'both')])
step(moves_by('tweety', 'unknown'), rule(33), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(migrates('tweety', 'undecided'), rule(33), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(moves_by('mythic', 'unknown'), rule(33), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(migrates('mythic', 'undecided'), rule(33), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(flight_status('falco', 'true_only'), rule(18), {'X': 'falco'}, [flies('falco', 'true'), ~flies('falco', 'false')])
step(~flies('falco', 'false'), 'absent', {}, [])
step(flight_status('batsy', 'true_only'), rule(18), {'X': 'batsy'}, [flies('batsy', 'true'), ~flies('batsy', 'false')])
step(~flies('batsy', 'false'), 'absent', {}, [])
step(flight_status('opus', 'false_only'), rule(19), {'X': 'opus'}, [flies('opus', 'false'), ~flies('opus', 'true')])
step(~flies('opus', 'true'), 'absent', {}, [])
step(wing_status('tweety', 'true_only'), rule(21), {'X': 'tweety'}, [wings('tweety', 'true'), ~wings('tweety', 'false')])
step(~wings('tweety', 'false'), 'absent', {}, [])
step(wing_status('falco', 'true_only'), rule(21), {'X': 'falco'}, [wings('falco', 'true'), ~wings('falco', 'false')])
step(~wings('falco', 'false'), 'absent', {}, [])
step(wing_status('mythic', 'true_only'), rule(21), {'X': 'mythic'}, [wings('mythic', 'true'), ~wings('mythic', 'false')])
step(~wings('mythic', 'false'), 'absent', {}, [])
step(wing_status('nemo', 'false_only'), rule(22), {'X': 'nemo'}, [wings('nemo', 'false'), ~wings('nemo', 'true')])
step(~wings('nemo', 'true'), 'absent', {}, [])
step(flies_safely('falco', 'true'), rule(25), {'X': 'falco'}, [flight_status('falco', 'true_only')])
step(flies_safely('batsy', 'true'), rule(25), {'X': 'batsy'}, [flight_status('batsy', 'true_only')])
step(flies_safely('opus', 'false'), rule(26), {'X': 'opus'}, [flight_status('opus', 'false_only')])
step(wings_safely('tweety', 'true'), rule(28), {'X': 'tweety'}, [wing_status('tweety', 'true_only')])
step(wings_safely('falco', 'true'), rule(28), {'X': 'falco'}, [wing_status('falco', 'true_only')])
step(wings_safely('mythic', 'true'), rule(28), {'X': 'mythic'}, [wing_status('mythic', 'true_only')])
step(wings_safely('nemo', 'false'), rule(29), {'X': 'nemo'}, [wing_status('nemo', 'false_only')])
step(moves_by('falco', 'flying'), rule(31), {'X': 'falco'}, [flight_status('falco', 'true_only')])
step(migrates('falco', 'true'), rule(31), {'X': 'falco'}, [flight_status('falco', 'true_only')])
step(moves_by('batsy', 'flying'), rule(31), {'X': 'batsy'}, [flight_status('batsy', 'true_only')])
step(migrates('batsy', 'true'), rule(31), {'X': 'batsy'}, [flight_status('batsy', 'true_only')])
step(moves_by('opus', 'walking'), rule(32), {'X': 'opus'}, [flight_status('opus', 'false_only')])
step(migrates('opus', 'false'), rule(32), {'X': 'opus'}, [flight_status('opus', 'false_only')])
