flies('tweety', 'true')
flies('falco', 'true')
flies('mythic', 'true')
wings('tweety', 'true')
wings('falco', 'true')
wings('mythic', 'true')
flies('tweety', 'false')
flies('opus', 'false')
wings('batsy', 'false')
flies('batsy', 'true')
wings('batsy', 'true')
swims('nemo', 'true')
wings('nemo', 'false')
flies('mythic', 'false')
flight_status('tweety', 'both')
flight_status('mythic', 'both')
wing_status('batsy', 'both')
inconsistent('tweety', 'flies')
needs_review('tweety', 'flies')
inconsistent('mythic', 'flies')
needs_review('mythic', 'flies')
inconsistent('batsy', 'wings')
needs_review('batsy', 'wings')
flies_safely('tweety', 'undecided')
flies_safely('mythic', 'undecided')
wings_safely('batsy', 'undecided')
moves_by('tweety', 'unknown')
migrates('tweety', 'undecided')
moves_by('mythic', 'unknown')
migrates('mythic', 'undecided')
flight_status('falco', 'true_only')
flight_status('batsy', 'true_only')
flight_status('opus', 'false_only')
wing_status('tweety', 'true_only')
wing_status('falco', 'true_only')
wing_status('mythic', 'true_only')
wing_status('nemo', 'false_only')
flies_safely('falco', 'true')
flies_safely('batsy', 'true')
flies_safely('opus', 'false')
wings_safely('tweety', 'true')
wings_safely('falco', 'true')
wings_safely('mythic', 'true')
wings_safely('nemo', 'false')
moves_by('falco', 'flying')
migrates('falco', 'true')
moves_by('batsy', 'flying')
migrates('batsy', 'true')
moves_by('opus', 'walking')
migrates('opus', 'false')

clause(1, fact(bird('tweety')))
clause(2, fact(penguin('tweety')))
clause(3, fact(bird('falco')))
clause(4, fact(penguin('opus')))
clause(5, fact(mammal('batsy')))
clause(6, fact(bat('batsy')))
clause(7, fact(fish('nemo')))
clause(8, fact(bird('mythic')))
clause(9, fact(observed('mythic', 'flies', 'false')))
clause(10, implies(bird(X), flies(X, 'true')))
clause(11, implies(bird(X), wings(X, 'true')))
clause(12, implies(penguin(X), flies(X, 'false')))
clause(13, implies(mammal(X), wings(X, 'false')))
clause(14, implies(bat(X), flies(X, 'true') & wings(X, 'true')))
clause(15, implies(fish(X), swims(X, 'true') & wings(X, 'false')))
clause(16, implies(observed(X, 'flies', Value), flies(X, Value)))
clause(17, implies(flies(X, 'true') & flies(X, 'false'), flight_status(X, 'both')))
clause(18, implies(flies(X, 'true') & ~flies(X, 'false'), flight_status(X, 'true_only')))
clause(19, implies(flies(X, 'false') & ~flies(X, 'true'), flight_status(X, 'false_only')))
clause(20, implies(wings(X, 'true') & wings(X, 'false'), wing_status(X, 'both')))
clause(21, implies(wings(X, 'true') & ~wings(X, 'false'), wing_status(X, 'true_only')))
clause(22, implies(wings(X, 'false') & ~wings(X, 'true'), wing_status(X, 'false_only')))
clause(23, implies(flight_status(X, 'both'), inconsistent(X, 'flies') & needs_review(X, 'flies')))
clause(24, implies(wing_status(X, 'both'), inconsistent(X, 'wings') & needs_review(X, 'wings')))
clause(25, implies(flight_status(X, 'true_only'), flies_safely(X, 'true')))
clause(26, implies(flight_status(X, 'false_only'), flies_safely(X, 'false')))
clause(27, implies(flight_status(X, 'both'), flies_safely(X, 'undecided')))
clause(28, implies(wing_status(X, 'true_only'), wings_safely(X, 'true')))
clause(29, implies(wing_status(X, 'false_only'), wings_safely(X, 'false')))
clause(30, implies(wing_status(X, 'both'), wings_safely(X, 'undecided')))
clause(31, implies(flight_status(X, 'true_only'), moves_by(X, 'flying') & migrates(X, 'true')))
clause(32, implies(flight_status(X, 'false_only'), moves_by(X, 'walking') & migrates(X, 'false')))
clause(33, implies(flight_status(X, 'both'), moves_by(X, 'unknown') & migrates(X, 'undecided')))

step(flies('tweety', 'true'), clause(10), {'X': 'tweety'}, [bird('tweety')])
step(bird('tweety'), clause(1), {}, [])
step(flies('falco', 'true'), clause(10), {'X': 'falco'}, [bird('falco')])
step(bird('falco'), clause(3), {}, [])
step(flies('mythic', 'true'), clause(10), {'X': 'mythic'}, [bird('mythic')])
step(bird('mythic'), clause(8), {}, [])
step(wings('tweety', 'true'), clause(11), {'X': 'tweety'}, [bird('tweety')])
step(wings('falco', 'true'), clause(11), {'X': 'falco'}, [bird('falco')])
step(wings('mythic', 'true'), clause(11), {'X': 'mythic'}, [bird('mythic')])
step(flies('tweety', 'false'), clause(12), {'X': 'tweety'}, [penguin('tweety')])
step(penguin('tweety'), clause(2), {}, [])
step(flies('opus', 'false'), clause(12), {'X': 'opus'}, [penguin('opus')])
step(penguin('opus'), clause(4), {}, [])
step(wings('batsy', 'false'), clause(13), {'X': 'batsy'}, [mammal('batsy')])
step(mammal('batsy'), clause(5), {}, [])
step(flies('batsy', 'true'), clause(14), {'X': 'batsy'}, [bat('batsy')])
step(bat('batsy'), clause(6), {}, [])
step(wings('batsy', 'true'), clause(14), {'X': 'batsy'}, [bat('batsy')])
step(swims('nemo', 'true'), clause(15), {'X': 'nemo'}, [fish('nemo')])
step(fish('nemo'), clause(7), {}, [])
step(wings('nemo', 'false'), clause(15), {'X': 'nemo'}, [fish('nemo')])
step(flies('mythic', 'false'), clause(16), {'X': 'mythic', 'Value': 'false'}, [observed('mythic', 'flies', 'false')])
step(observed('mythic', 'flies', 'false'), clause(9), {}, [])
step(flight_status('tweety', 'both'), clause(17), {'X': 'tweety'}, [flies('tweety', 'true'), flies('tweety', 'false')])
step(flight_status('mythic', 'both'), clause(17), {'X': 'mythic'}, [flies('mythic', 'true'), flies('mythic', 'false')])
step(wing_status('batsy', 'both'), clause(20), {'X': 'batsy'}, [wings('batsy', 'true'), wings('batsy', 'false')])
step(inconsistent('tweety', 'flies'), clause(23), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(needs_review('tweety', 'flies'), clause(23), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(inconsistent('mythic', 'flies'), clause(23), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(needs_review('mythic', 'flies'), clause(23), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(inconsistent('batsy', 'wings'), clause(24), {'X': 'batsy'}, [wing_status('batsy', 'both')])
step(needs_review('batsy', 'wings'), clause(24), {'X': 'batsy'}, [wing_status('batsy', 'both')])
step(flies_safely('tweety', 'undecided'), clause(27), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(flies_safely('mythic', 'undecided'), clause(27), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(wings_safely('batsy', 'undecided'), clause(30), {'X': 'batsy'}, [wing_status('batsy', 'both')])
step(moves_by('tweety', 'unknown'), clause(33), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(migrates('tweety', 'undecided'), clause(33), {'X': 'tweety'}, [flight_status('tweety', 'both')])
step(moves_by('mythic', 'unknown'), clause(33), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(migrates('mythic', 'undecided'), clause(33), {'X': 'mythic'}, [flight_status('mythic', 'both')])
step(flight_status('falco', 'true_only'), clause(18), {'X': 'falco'}, [flies('falco', 'true'), ~flies('falco', 'false')])
step(~flies('falco', 'false'), 'absent', {}, [])
step(flight_status('batsy', 'true_only'), clause(18), {'X': 'batsy'}, [flies('batsy', 'true'), ~flies('batsy', 'false')])
step(~flies('batsy', 'false'), 'absent', {}, [])
step(flight_status('opus', 'false_only'), clause(19), {'X': 'opus'}, [flies('opus', 'false'), ~flies('opus', 'true')])
step(~flies('opus', 'true'), 'absent', {}, [])
step(wing_status('tweety', 'true_only'), clause(21), {'X': 'tweety'}, [wings('tweety', 'true'), ~wings('tweety', 'false')])
step(~wings('tweety', 'false'), 'absent', {}, [])
step(wing_status('falco', 'true_only'), clause(21), {'X': 'falco'}, [wings('falco', 'true'), ~wings('falco', 'false')])
step(~wings('falco', 'false'), 'absent', {}, [])
step(wing_status('mythic', 'true_only'), clause(21), {'X': 'mythic'}, [wings('mythic', 'true'), ~wings('mythic', 'false')])
step(~wings('mythic', 'false'), 'absent', {}, [])
step(wing_status('nemo', 'false_only'), clause(22), {'X': 'nemo'}, [wings('nemo', 'false'), ~wings('nemo', 'true')])
step(~wings('nemo', 'true'), 'absent', {}, [])
step(flies_safely('falco', 'true'), clause(25), {'X': 'falco'}, [flight_status('falco', 'true_only')])
step(flies_safely('batsy', 'true'), clause(25), {'X': 'batsy'}, [flight_status('batsy', 'true_only')])
step(flies_safely('opus', 'false'), clause(26), {'X': 'opus'}, [flight_status('opus', 'false_only')])
step(wings_safely('tweety', 'true'), clause(28), {'X': 'tweety'}, [wing_status('tweety', 'true_only')])
step(wings_safely('falco', 'true'), clause(28), {'X': 'falco'}, [wing_status('falco', 'true_only')])
step(wings_safely('mythic', 'true'), clause(28), {'X': 'mythic'}, [wing_status('mythic', 'true_only')])
step(wings_safely('nemo', 'false'), clause(29), {'X': 'nemo'}, [wing_status('nemo', 'false_only')])
step(moves_by('falco', 'flying'), clause(31), {'X': 'falco'}, [flight_status('falco', 'true_only')])
step(migrates('falco', 'true'), clause(31), {'X': 'falco'}, [flight_status('falco', 'true_only')])
step(moves_by('batsy', 'flying'), clause(31), {'X': 'batsy'}, [flight_status('batsy', 'true_only')])
step(migrates('batsy', 'true'), clause(31), {'X': 'batsy'}, [flight_status('batsy', 'true_only')])
step(moves_by('opus', 'walking'), clause(32), {'X': 'opus'}, [flight_status('opus', 'false_only')])
step(migrates('opus', 'false'), clause(32), {'X': 'opus'}, [flight_status('opus', 'false_only')])
