allowed('alice', 'read')
allowed('alice', 'write')
allowed('bob', 'read')

clause(1, fact(role('alice', 'editor')))
clause(2, fact(role('bob', 'viewer')))
clause(4, fact(permits('editor', 'read')))
clause(5, fact(permits('editor', 'write')))
clause(6, fact(permits('viewer', 'read')))
clause(8, forward(candidate(User, Action), role(User, Role), permits(Role, Action)))
clause(9, forward(allowed(User, Action), candidate(User, Action), ~suspended(User)))

step(allowed('alice', 'read'), clause(9), {'User': 'alice', 'Action': 'read'}, [candidate('alice', 'read'), ~suspended('alice')])
step(candidate('alice', 'read'), clause(8), {'User': 'alice', 'Action': 'read', 'Role': 'editor'}, [role('alice', 'editor'), permits('editor', 'read')])
step(role('alice', 'editor'), clause(1), {}, [])
step(permits('editor', 'read'), clause(4), {}, [])
step(~suspended('alice'), 'absent', {}, [])
step(allowed('alice', 'write'), clause(9), {'User': 'alice', 'Action': 'write'}, [candidate('alice', 'write'), ~suspended('alice')])
step(candidate('alice', 'write'), clause(8), {'User': 'alice', 'Action': 'write', 'Role': 'editor'}, [role('alice', 'editor'), permits('editor', 'write')])
step(permits('editor', 'write'), clause(5), {}, [])
step(allowed('bob', 'read'), clause(9), {'User': 'bob', 'Action': 'read'}, [candidate('bob', 'read'), ~suspended('bob')])
step(candidate('bob', 'read'), clause(8), {'User': 'bob', 'Action': 'read', 'Role': 'viewer'}, [role('bob', 'viewer'), permits('viewer', 'read')])
step(role('bob', 'viewer'), clause(2), {}, [])
step(permits('viewer', 'read'), clause(6), {}, [])
step(~suspended('bob'), 'absent', {}, [])
