report(1, 'c1', 100, 'high', 'no_removal_safeguards', 'add_notice_and_inform')
report(3, 'c2', 85, 'high', short_notice(3, 14), increase_notice(14))
report(4, 'c4', 70, 'moderate', 'export_prohibited', 'permit_export')
report(2, 'c3', 97, 'high', 'sharing_without_consent', 'require_consent')

clause(1, fact(permission('c1', 'remove_account')))
clause(2, fact(permission('c2', 'change_terms')))
clause(3, fact(permission('c3', 'share_data')))
clause(4, fact(prohibition('c4', 'export_data')))
clause(5, fact(notice_days('c2', 3)))
clause(10, fact(importance('retention', 20)))
clause(11, fact(importance('prior_notice', 15)))
clause(12, fact(importance('consent', 12)))
clause(13, fact(importance('portability', 10)))
clause(14, fact(required_notice(14)))
clause(16, forward(finding(Clause, Raw, 'no_removal_safeguards', 'add_notice_and_inform'), permission(Clause, 'remove_account'), importance('retention', Weight), ~has_notice(Clause), ~safeguard(Clause, 'inform'), is_(Raw, 90 + Weight)))
clause(17, forward(finding(Clause, Raw, short_notice(Days, Required), increase_notice(Required)), permission(Clause, 'change_terms'), notice_days(Clause, Days), required_notice(Required), Days < Required, importance('prior_notice', Weight), is_(Raw, 70 + Weight)))
clause(18, forward(finding(Clause, Raw, 'sharing_without_consent', 'require_consent'), permission(Clause, 'share_data'), ~safeguard(Clause, 'consent'), importance('consent', Weight), is_(Raw, 85 + Weight)))
clause(19, forward(finding(Clause, Raw, 'export_prohibited', 'permit_export'), prohibition(Clause, 'export_data'), importance('portability', Weight), is_(Raw, 60 + Weight)))
clause(20, forward(score(Clause, 100), finding(Clause, Raw, Why, Fix), Raw > 100))
clause(21, forward(score(Clause, Raw), finding(Clause, Raw, Why, Fix), Raw <= 100))
clause(22, backward(severity(Score, 'high'), Score >= 80))
clause(23, backward(severity(Score, 'moderate'), Score >= 50, Score < 80))
clause(26, fact(count([], 0)))
clause(27, backward(count([_0, *Rest], N), count(Rest, Before), is_(N, Before + 1)))
clause(28, forward(report(Rank, Clause, Score, Severity, Why, Fix), score(Clause, Score), finding(Clause, Raw, Why, Fix), severity(Score, Severity), findall(Other, higher(Score, Other), Higher), count(Higher, Count), is_(Rank, Count + 1)))

step(report(1, 'c1', 100, 'high', 'no_removal_safeguards', 'add_notice_and_inform'), clause(28), {'Rank': 1, 'Clause': 'c1', 'Score': 100, 'Severity': 'high', 'Why': 'no_removal_safeguards', 'Fix': 'add_notice_and_inform', 'Raw': 110, 'Other': A, 'Higher': [], 'Count': 0}, [score('c1', 100), finding('c1', 110, 'no_removal_safeguards', 'add_notice_and_inform'), severity(100, 'high'), findall(A, higher(100, A), []), count([], 0), is_(1, 0 + 1)])
step(score('c1', 100), clause(20), {'Clause': 'c1', 'Raw': 110, 'Why': 'no_removal_safeguards', 'Fix': 'add_notice_and_inform'}, [finding('c1', 110, 'no_removal_safeguards', 'add_notice_and_inform'), 110 > 100])
step(finding('c1', 110, 'no_removal_safeguards', 'add_notice_and_inform'), clause(16), {'Clause': 'c1', 'Raw': 110, 'Weight': 20}, [permission('c1', 'remove_account'), importance('retention', 20), ~has_notice('c1'), ~safeguard('c1', 'inform'), is_(110, 90 + 20)])
step(permission('c1', 'remove_account'), clause(1), {}, [])
step(importance('retention', 20), clause(10), {}, [])
step(~has_notice('c1'), 'absent', {}, [])
step(~safeguard('c1', 'inform'), 'absent', {}, [])
step(is_(110, 90 + 20), 'builtin', {}, [])
step(110 > 100, 'builtin', {}, [])
step(severity(100, 'high'), clause(22), {'Score': 100}, [100 >= 80])
step(100 >= 80, 'builtin', {}, [])
step(findall(A, higher(100, A), []), 'collected', {}, [])
step(count([], 0), clause(26), {}, [])
step(is_(1, 0 + 1), 'builtin', {}, [])
step(report(3, 'c2', 85, 'high', short_notice(3, 14), increase_notice(14)), clause(28), {'Rank': 3, 'Clause': 'c2', 'Score': 85, 'Severity': 'high', 'Why': short_notice(3, 14), 'Fix': increase_notice(14), 'Raw': 85, 'Other': A, 'Higher': [100, 97], 'Count': 2}, [score('c2', 85), finding('c2', 85, short_notice(3, 14), increase_notice(14)), severity(85, 'high'), findall(A, higher(85, A), [100, 97]), count([100, 97], 2), is_(3, 2 + 1)])
step(score('c2', 85), clause(21), {'Clause': 'c2', 'Raw': 85, 'Why': short_notice(3, 14), 'Fix': increase_notice(14)}, [finding('c2', 85, short_notice(3, 14), increase_notice(14)), 85 <= 100])
step(finding('c2', 85, short_notice(3, 14), increase_notice(14)), clause(17), {'Clause': 'c2', 'Raw': 85, 'Days': 3, 'Required': 14, 'Weight': 15}, [permission('c2', 'change_terms'), notice_days('c2', 3), required_notice(14), 3 < 14, importance('prior_notice', 15), is_(85, 70 + 15)])
step(permission('c2', 'change_terms'), clause(2), {}, [])
step(notice_days('c2', 3), clause(5), {}, [])
step(required_notice(14), clause(14), {}, [])
step(3 < 14, 'builtin', {}, [])
step(importance('prior_notice', 15), clause(11), {}, [])
step(is_(85, 70 + 15), 'builtin', {}, [])
step(85 <= 100, 'builtin', {}, [])
step(severity(85, 'high'), clause(22), {'Score': 85}, [85 >= 80])
step(85 >= 80, 'builtin', {}, [])
step(findall(A, higher(85, A), [100, 97]), 'collected', {}, [])
step(count([100, 97], 2), clause(27), {'_0': 100, 'Rest': [97], 'N': 2, 'Before': 1}, [count([97], 1), is_(2, 1 + 1)])
step(count([97], 1), clause(27), {'_0': 97, 'Rest': [], 'N': 1, 'Before': 0}, [count([], 0), is_(1, 0 + 1)])
step(is_(2, 1 + 1), 'builtin', {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(report(4, 'c4', 70, 'moderate', 'export_prohibited', 'permit_export'), clause(28), {'Rank': 4, 'Clause': 'c4', 'Score': 70, 'Severity': 'moderate', 'Why': 'export_prohibited', 'Fix': 'permit_export', 'Raw': 70, 'Other': A, 'Higher': [100, 85, 97], 'Count': 3}, [score('c4', 70), finding('c4', 70, 'export_prohibited', 'permit_export'), severity(70, 'moderate'), findall(A, higher(70, A), [100, 85, 97]), count([100, 85, 97], 3), is_(4, 3 + 1)])
step(score('c4', 70), clause(21), {'Clause': 'c4', 'Raw': 70, 'Why': 'export_prohibited', 'Fix': 'permit_export'}, [finding('c4', 70, 'export_prohibited', 'permit_export'), 70 <= 100])
step(finding('c4', 70, 'export_prohibited', 'permit_export'), clause(19), {'Clause': 'c4', 'Raw': 70, 'Weight': 10}, [prohibition('c4', 'export_data'), importance('portability', 10), is_(70, 60 + 10)])
step(prohibition('c4', 'export_data'), clause(4), {}, [])
step(importance('portability', 10), clause(13), {}, [])
step(is_(70, 60 + 10), 'builtin', {}, [])
step(70 <= 100, 'builtin', {}, [])
step(severity(70, 'moderate'), clause(23), {'Score': 70}, [70 >= 50, 70 < 80])
step(70 >= 50, 'builtin', {}, [])
step(70 < 80, 'builtin', {}, [])
step(findall(A, higher(70, A), [100, 85, 97]), 'collected', {}, [])
step(count([100, 85, 97], 3), clause(27), {'_0': 100, 'Rest': [85, 97], 'N': 3, 'Before': 2}, [count([85, 97], 2), is_(3, 2 + 1)])
step(count([85, 97], 2), clause(27), {'_0': 85, 'Rest': [97], 'N': 2, 'Before': 1}, [count([97], 1), is_(2, 1 + 1)])
step(is_(4, 3 + 1), 'builtin', {}, [])
step(report(2, 'c3', 97, 'high', 'sharing_without_consent', 'require_consent'), clause(28), {'Rank': 2, 'Clause': 'c3', 'Score': 97, 'Severity': 'high', 'Why': 'sharing_without_consent', 'Fix': 'require_consent', 'Raw': 97, 'Other': A, 'Higher': [100], 'Count': 1}, [score('c3', 97), finding('c3', 97, 'sharing_without_consent', 'require_consent'), severity(97, 'high'), findall(A, higher(97, A), [100]), count([100], 1), is_(2, 1 + 1)])
step(score('c3', 97), clause(21), {'Clause': 'c3', 'Raw': 97, 'Why': 'sharing_without_consent', 'Fix': 'require_consent'}, [finding('c3', 97, 'sharing_without_consent', 'require_consent'), 97 <= 100])
step(finding('c3', 97, 'sharing_without_consent', 'require_consent'), clause(18), {'Clause': 'c3', 'Raw': 97, 'Weight': 12}, [permission('c3', 'share_data'), ~safeguard('c3', 'consent'), importance('consent', 12), is_(97, 85 + 12)])
step(permission('c3', 'share_data'), clause(3), {}, [])
step(~safeguard('c3', 'consent'), 'absent', {}, [])
step(importance('consent', 12), clause(12), {}, [])
step(is_(97, 85 + 12), 'builtin', {}, [])
step(97 <= 100, 'builtin', {}, [])
step(severity(97, 'high'), clause(22), {'Score': 97}, [97 >= 80])
step(97 >= 80, 'builtin', {}, [])
step(findall(A, higher(97, A), [100]), 'collected', {}, [])
step(count([100], 1), clause(27), {'_0': 100, 'Rest': [], 'N': 1, 'Before': 0}, [count([], 0), is_(1, 0 + 1)])
