reachable('a', 'b')
reachable('b', 'c')
reachable('c', 'a')
reachable('c', 'd')
reachable('a', 'c')
reachable('b', 'a')
reachable('b', 'd')
reachable('c', 'b')
reachable('a', 'a')
reachable('a', 'd')
reachable('b', 'b')
reachable('c', 'c')

clause(1, fact(edge('a', 'b')))
clause(2, fact(edge('b', 'c')))
clause(3, fact(edge('c', 'a')))
clause(4, fact(edge('c', 'd')))
clause(5, forward(reachable(X, Y), edge(X, Y)))
clause(6, forward(reachable(X, Z), reachable(X, Y), edge(Y, Z)))

step(reachable('a', 'b'), rule(5), {'X': 'a', 'Y': 'b'}, [edge('a', 'b')])
step(edge('a', 'b'), fact(1), {}, [])
step(reachable('b', 'c'), rule(5), {'X': 'b', 'Y': 'c'}, [edge('b', 'c')])
step(edge('b', 'c'), fact(2), {}, [])
step(reachable('c', 'a'), rule(5), {'X': 'c', 'Y': 'a'}, [edge('c', 'a')])
step(edge('c', 'a'), fact(3), {}, [])
step(reachable('c', 'd'), rule(5), {'X': 'c', 'Y': 'd'}, [edge('c', 'd')])
step(edge('c', 'd'), fact(4), {}, [])
step(reachable('a', 'c'), rule(6), {'X': 'a', 'Z': 'c', 'Y': 'b'}, [reachable('a', 'b'), edge('b', 'c')])
step(reachable('b', 'a'), rule(6), {'X': 'b', 'Z': 'a', 'Y': 'c'}, [reachable('b', 'c'), edge('c', 'a')])
step(reachable('b', 'd'), rule(6), {'X': 'b', 'Z': 'd', 'Y': 'c'}, [reachable('b', 'c'), edge('c', 'd')])
step(reachable('c', 'b'), rule(6), {'X': 'c', 'Z': 'b', 'Y': 'a'}, [reachable('c', 'a'), edge('a', 'b')])
step(reachable('a', 'a'), rule(6), {'X': 'a', 'Z': 'a', 'Y': 'c'}, [reachable('a', 'c'), edge('c', 'a')])
step(reachable('a', 'd'), rule(6), {'X': 'a', 'Z': 'd', 'Y': 'c'}, [reachable('a', 'c'), edge('c', 'd')])
step(reachable('b', 'b'), rule(6), {'X': 'b', 'Z': 'b', 'Y': 'a'}, [reachable('b', 'a'), edge('a', 'b')])
step(reachable('c', 'c'), rule(6), {'X': 'c', 'Z': 'c', 'Y': 'b'}, [reachable('c', 'b'), edge('b', 'c')])
