subclass('cat', 'animal')
type('koko', 'animal')
type('koko', 'mammal')
triple('alice', 'related_to', 'bob')
type('alice', 'person')
type('bob', 'person')

clause(1, fact(subclass('cat', 'mammal')))
clause(2, fact(subclass('mammal', 'animal')))
clause(3, fact(subproperty('parent_of', 'related_to')))
clause(4, fact(domain('parent_of', 'person')))
clause(5, fact(codomain('parent_of', 'person')))
clause(6, fact(type('koko', 'cat')))
clause(7, fact(triple('alice', 'parent_of', 'bob')))
clause(8, forward(subclass(A, C), subclass(A, B), subclass(B, C)))
clause(9, forward(type(X, B), type(X, A), subclass(A, B)))
clause(10, forward(triple(S, Q, O), triple(S, P, O), subproperty(P, Q)))
clause(11, forward(type(S, Class), triple(S, P, _0), domain(P, Class)))
clause(12, forward(type(O, Class), triple(_0, P, O), codomain(P, Class)))

step(subclass('cat', 'animal'), clause(8), {'A': 'cat', 'C': 'animal', 'B': 'mammal'}, [subclass('cat', 'mammal'), subclass('mammal', 'animal')])
step(subclass('cat', 'mammal'), clause(1), {}, [])
step(subclass('mammal', 'animal'), clause(2), {}, [])
step(type('koko', 'animal'), clause(9), {'X': 'koko', 'B': 'animal', 'A': 'cat'}, [type('koko', 'cat'), subclass('cat', 'animal')])
step(type('koko', 'cat'), clause(6), {}, [])
step(type('koko', 'mammal'), clause(9), {'X': 'koko', 'B': 'mammal', 'A': 'cat'}, [type('koko', 'cat'), subclass('cat', 'mammal')])
step(triple('alice', 'related_to', 'bob'), clause(10), {'S': 'alice', 'Q': 'related_to', 'O': 'bob', 'P': 'parent_of'}, [triple('alice', 'parent_of', 'bob'), subproperty('parent_of', 'related_to')])
step(triple('alice', 'parent_of', 'bob'), clause(7), {}, [])
step(subproperty('parent_of', 'related_to'), clause(3), {}, [])
step(type('alice', 'person'), clause(11), {'S': 'alice', 'Class': 'person', 'P': 'parent_of', '_0': 'bob'}, [triple('alice', 'parent_of', 'bob'), domain('parent_of', 'person')])
step(domain('parent_of', 'person'), clause(4), {}, [])
step(type('bob', 'person'), clause(12), {'O': 'bob', 'Class': 'person', '_0': 'alice', 'P': 'parent_of'}, [triple('alice', 'parent_of', 'bob'), codomain('parent_of', 'person')])
step(codomain('parent_of', 'person'), clause(5), {}, [])
