consented('approved', 'alice')
needs_review('incomplete', 'bob')

clause(1, fact(context('approved', graph([triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')]))))
clause(2, fact(context('incomplete', graph([triple('bob', 'role', 'editor')]))))
clause(3, fact(member(X, [X, *__anon0])))
clause(4, backward(member(X, [__anon1, *Xs]), member(X, Xs)))
clause(5, backward(includes(graph(Triples), Triple), member(Triple, Triples)))
clause(6, forward(consented(Context, Person), context(Context, Graph), includes(Graph, triple(Person, 'consent', 'yes'))))
clause(7, forward(needs_review(Context, Person), context(Context, Graph), includes(Graph, triple(Person, 'role', 'editor')), ~includes(Graph, triple(Person, 'consent', 'yes'))))

step(consented('approved', 'alice'), rule(6), {'Context': 'approved', 'Person': 'alice', 'Graph': graph([triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')])}, [context('approved', graph([triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')])), includes(graph([triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')]), triple('alice', 'consent', 'yes'))])
step(context('approved', graph([triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')])), fact(1), {}, [])
step(includes(graph([triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')]), triple('alice', 'consent', 'yes')), rule(5), {'Triples': [triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')], 'Triple': triple('alice', 'consent', 'yes')}, [member(triple('alice', 'consent', 'yes'), [triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')])])
step(member(triple('alice', 'consent', 'yes'), [triple('alice', 'role', 'editor'), triple('alice', 'consent', 'yes')]), rule(4), {'X': triple('alice', 'consent', 'yes'), '__anon1': triple('alice', 'role', 'editor'), 'Xs': [triple('alice', 'consent', 'yes')]}, [member(triple('alice', 'consent', 'yes'), [triple('alice', 'consent', 'yes')])])
step(member(triple('alice', 'consent', 'yes'), [triple('alice', 'consent', 'yes')]), fact(3), {'X': triple('alice', 'consent', 'yes'), '__anon0': []}, [])
step(needs_review('incomplete', 'bob'), rule(7), {'Context': 'incomplete', 'Person': 'bob', 'Graph': graph([triple('bob', 'role', 'editor')])}, [context('incomplete', graph([triple('bob', 'role', 'editor')])), includes(graph([triple('bob', 'role', 'editor')]), triple('bob', 'role', 'editor')), ~includes(graph([triple('bob', 'role', 'editor')]), triple('bob', 'consent', 'yes'))])
step(context('incomplete', graph([triple('bob', 'role', 'editor')])), fact(2), {}, [])
step(includes(graph([triple('bob', 'role', 'editor')]), triple('bob', 'role', 'editor')), rule(5), {'Triples': [triple('bob', 'role', 'editor')], 'Triple': triple('bob', 'role', 'editor')}, [member(triple('bob', 'role', 'editor'), [triple('bob', 'role', 'editor')])])
step(member(triple('bob', 'role', 'editor'), [triple('bob', 'role', 'editor')]), fact(3), {'X': triple('bob', 'role', 'editor'), '__anon0': []}, [])
step(~includes(graph([triple('bob', 'role', 'editor')]), triple('bob', 'consent', 'yes')), 'absent', {}, [])
