shortest('a', 'd', 6)

clause(2, fact(edge('a', 'c', 2)))
clause(3, fact(edge('c', 'b', 1)))
clause(4, fact(edge('b', 'd', 3)))
clause(6, implies(edge(X, Y, Cost), path(X, Y, Cost)))
clause(7, implies(path(X, Y, Before) & edge(Y, Z, Weight) & is_(Cost, Before + Weight), path(X, Z, Cost)))
clause(9, implies(path(X, Y, Cost) & ~cheaper(X, Y, Cost), shortest(X, Y, Cost)))

step(shortest('a', 'd', 6), clause(9), {'X': 'a', 'Y': 'd', 'Cost': 6}, [path('a', 'd', 6), ~cheaper('a', 'd', 6)])
step(path('a', 'd', 6), clause(7), {'X': 'a', 'Y': 'b', 'Before': 3, 'Z': 'd', 'Weight': 3, 'Cost': 6}, [path('a', 'b', 3), edge('b', 'd', 3), is_(6, 3 + 3)])
step(path('a', 'b', 3), clause(7), {'X': 'a', 'Y': 'c', 'Before': 2, 'Z': 'b', 'Weight': 1, 'Cost': 3}, [path('a', 'c', 2), edge('c', 'b', 1), is_(3, 2 + 1)])
step(path('a', 'c', 2), clause(6), {'X': 'a', 'Y': 'c', 'Cost': 2}, [edge('a', 'c', 2)])
step(edge('a', 'c', 2), clause(2), {}, [])
step(edge('c', 'b', 1), clause(3), {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(edge('b', 'd', 3), clause(4), {}, [])
step(is_(6, 3 + 3), 'builtin', {}, [])
step(~cheaper('a', 'd', 6), 'absent', {}, [])
