shortest('a', 'd', 6)

clause(2, fact(edge('a', 'c', 2)))
clause(3, fact(edge('c', 'b', 1)))
clause(4, fact(edge('b', 'd', 3)))
clause(6, forward(path(X, Y, Cost), edge(X, Y, Cost)))
clause(7, forward(path(X, Z, Cost), path(X, Y, Before), edge(Y, Z, Weight), is_(Cost, Before + Weight)))
clause(9, forward(shortest(X, Y, Cost), path(X, Y, Cost), ~cheaper(X, Y, Cost)))

step(shortest('a', 'd', 6), rule(9), {'X': 'a', 'Y': 'd', 'Cost': 6}, [path('a', 'd', 6), ~cheaper('a', 'd', 6)])
step(path('a', 'd', 6), rule(7), {'X': 'a', 'Z': 'd', 'Cost': 6, 'Y': 'b', 'Before': 3, 'Weight': 3}, [path('a', 'b', 3), edge('b', 'd', 3), is_(6, 3 + 3)])
step(path('a', 'b', 3), rule(7), {'X': 'a', 'Z': 'b', 'Cost': 3, 'Y': 'c', 'Before': 2, 'Weight': 1}, [path('a', 'c', 2), edge('c', 'b', 1), is_(3, 2 + 1)])
step(path('a', 'c', 2), rule(6), {'X': 'a', 'Y': 'c', 'Cost': 2}, [edge('a', 'c', 2)])
step(edge('a', 'c', 2), fact(2), {}, [])
step(edge('c', 'b', 1), fact(3), {}, [])
step(is_(3, 2 + 1), 'builtin', {}, [])
step(edge('b', 'd', 3), fact(4), {}, [])
step(is_(6, 3 + 3), 'builtin', {}, [])
step(~cheaper('a', 'd', 6), 'absent', {}, [])
