label('alice', 'hello_alice')
characters('café', ['c', 'a', 'f', 'é'], 4)
unicode_codes('😀', [128512])

clause(1, backward(label(Name, Label), atom_concat('hello_', Name, Label)))
clause(2, backward(characters(Text, Chars, Length), atom_chars(Text, Chars), atom_length(Text, Length)))
clause(3, backward(unicode_codes(Text, Codes), atom_codes(Text, Codes)))

step(label('alice', 'hello_alice'), clause(1), {'Name': 'alice', 'Label': 'hello_alice'}, [atom_concat('hello_', 'alice', 'hello_alice')])
step(atom_concat('hello_', 'alice', 'hello_alice'), 'builtin', {}, [])
step(characters('café', ['c', 'a', 'f', 'é'], 4), clause(2), {'Text': 'café', 'Chars': ['c', 'a', 'f', 'é'], 'Length': 4}, [atom_chars('café', ['c', 'a', 'f', 'é']), atom_length('café', 4)])
step(atom_chars('café', ['c', 'a', 'f', 'é']), 'builtin', {}, [])
step(atom_length('café', 4), 'builtin', {}, [])
step(unicode_codes('😀', [128512]), clause(3), {'Text': '😀', 'Codes': [128512]}, [atom_codes('😀', [128512])])
step(atom_codes('😀', [128512]), 'builtin', {}, [])
