sdcoding(0, 0)
sdcoding(1, 1)
sdcoding(2, 2)
sdcoding(3, 3)

clause(29, fact(message(0)))
clause(30, fact(message(1)))
clause(31, fact(message(2)))
clause(32, fact(message(3)))
clause(33, fact(odd([_0])))
clause(35, forward(sdcoding(N, M), message(N), message(M), findall(Path, path(N, M, Path), Paths), odd(Paths)))

step(sdcoding(0, 0), clause(35), {'N': 0, 'M': 0, 'Path': A, 'Paths': [['true', 'true', 'true']]}, [message(0), message(0), findall(A, path(0, 0, A), [['true', 'true', 'true']]), odd([['true', 'true', 'true']])])
step(message(0), clause(29), {}, [])
step(findall(A, path(0, 0, A), [['true', 'true', 'true']]), 'collected', {}, [])
step(odd([['true', 'true', 'true']]), clause(33), {'_0': ['true', 'true', 'true']}, [])
step(sdcoding(1, 1), clause(35), {'N': 1, 'M': 1, 'Path': A, 'Paths': [['false', 'false', 'true']]}, [message(1), message(1), findall(A, path(1, 1, A), [['false', 'false', 'true']]), odd([['false', 'false', 'true']])])
step(message(1), clause(30), {}, [])
step(findall(A, path(1, 1, A), [['false', 'false', 'true']]), 'collected', {}, [])
step(odd([['false', 'false', 'true']]), clause(33), {'_0': ['false', 'false', 'true']}, [])
step(sdcoding(2, 2), clause(35), {'N': 2, 'M': 2, 'Path': A, 'Paths': [['true', 'true', 'false']]}, [message(2), message(2), findall(A, path(2, 2, A), [['true', 'true', 'false']]), odd([['true', 'true', 'false']])])
step(message(2), clause(31), {}, [])
step(findall(A, path(2, 2, A), [['true', 'true', 'false']]), 'collected', {}, [])
step(odd([['true', 'true', 'false']]), clause(33), {'_0': ['true', 'true', 'false']}, [])
step(sdcoding(3, 3), clause(35), {'N': 3, 'M': 3, 'Path': A, 'Paths': [['false', 'false', 'false']]}, [message(3), message(3), findall(A, path(3, 3, A), [['false', 'false', 'false']]), odd([['false', 'false', 'false']])])
step(message(3), clause(32), {}, [])
step(findall(A, path(3, 3, A), [['false', 'false', 'false']]), 'collected', {}, [])
step(odd([['false', 'false', 'false']]), clause(33), {'_0': ['false', 'false', 'false']}, [])
