teleported('zero', 0, ['false'])
teleported('zero', 1, ['false'])
teleported('zero', 2, ['false'])
teleported('zero', 3, ['false'])
teleported('one', 0, ['true'])
teleported('one', 1, ['true'])
teleported('one', 2, ['true'])
teleported('one', 3, ['true'])
teleported('plus', 0, ['false', 'true'])
teleported('plus', 1, ['false', 'true'])
teleported('plus', 2, ['false', 'true'])
teleported('plus', 3, ['false', 'true'])

clause(5, fact(name('zero')))
clause(6, fact(name('one')))
clause(7, fact(name('plus')))
clause(29, fact(outcome(0)))
clause(30, fact(outcome(1)))
clause(31, fact(outcome(2)))
clause(32, fact(outcome(3)))
clause(37, forward(teleported(S, M, Received), name(S), outcome(M), findall(Z, received(S, M, Z), Received)))

step(teleported('zero', 0, ['false']), clause(37), {'S': 'zero', 'M': 0, 'Received': ['false'], 'Z': VAR_Z_23_1}, [name('zero'), outcome(0), findall(VAR_Z_23_1, received('zero', 0, VAR_Z_23_1), ['false'])])
step(name('zero'), clause(5), {}, [])
step(outcome(0), clause(29), {}, [])
step(findall(VAR_Z_23_1, received('zero', 0, VAR_Z_23_1), ['false']), 'collected', {}, [])
step(teleported('zero', 1, ['false']), clause(37), {'S': 'zero', 'M': 1, 'Received': ['false'], 'Z': VAR_Z_23_1}, [name('zero'), outcome(1), findall(VAR_Z_23_1, received('zero', 1, VAR_Z_23_1), ['false'])])
step(outcome(1), clause(30), {}, [])
step(findall(VAR_Z_23_1, received('zero', 1, VAR_Z_23_1), ['false']), 'collected', {}, [])
step(teleported('zero', 2, ['false']), clause(37), {'S': 'zero', 'M': 2, 'Received': ['false'], 'Z': VAR_Z_23_1}, [name('zero'), outcome(2), findall(VAR_Z_23_1, received('zero', 2, VAR_Z_23_1), ['false'])])
step(outcome(2), clause(31), {}, [])
step(findall(VAR_Z_23_1, received('zero', 2, VAR_Z_23_1), ['false']), 'collected', {}, [])
step(teleported('zero', 3, ['false']), clause(37), {'S': 'zero', 'M': 3, 'Received': ['false'], 'Z': VAR_Z_23_1}, [name('zero'), outcome(3), findall(VAR_Z_23_1, received('zero', 3, VAR_Z_23_1), ['false'])])
step(outcome(3), clause(32), {}, [])
step(findall(VAR_Z_23_1, received('zero', 3, VAR_Z_23_1), ['false']), 'collected', {}, [])
step(teleported('one', 0, ['true']), clause(37), {'S': 'one', 'M': 0, 'Received': ['true'], 'Z': VAR_Z_23_1}, [name('one'), outcome(0), findall(VAR_Z_23_1, received('one', 0, VAR_Z_23_1), ['true'])])
step(name('one'), clause(6), {}, [])
step(findall(VAR_Z_23_1, received('one', 0, VAR_Z_23_1), ['true']), 'collected', {}, [])
step(teleported('one', 1, ['true']), clause(37), {'S': 'one', 'M': 1, 'Received': ['true'], 'Z': VAR_Z_23_1}, [name('one'), outcome(1), findall(VAR_Z_23_1, received('one', 1, VAR_Z_23_1), ['true'])])
step(findall(VAR_Z_23_1, received('one', 1, VAR_Z_23_1), ['true']), 'collected', {}, [])
step(teleported('one', 2, ['true']), clause(37), {'S': 'one', 'M': 2, 'Received': ['true'], 'Z': VAR_Z_23_1}, [name('one'), outcome(2), findall(VAR_Z_23_1, received('one', 2, VAR_Z_23_1), ['true'])])
step(findall(VAR_Z_23_1, received('one', 2, VAR_Z_23_1), ['true']), 'collected', {}, [])
step(teleported('one', 3, ['true']), clause(37), {'S': 'one', 'M': 3, 'Received': ['true'], 'Z': VAR_Z_23_1}, [name('one'), outcome(3), findall(VAR_Z_23_1, received('one', 3, VAR_Z_23_1), ['true'])])
step(findall(VAR_Z_23_1, received('one', 3, VAR_Z_23_1), ['true']), 'collected', {}, [])
step(teleported('plus', 0, ['false', 'true']), clause(37), {'S': 'plus', 'M': 0, 'Received': ['false', 'true'], 'Z': VAR_Z_23_1}, [name('plus'), outcome(0), findall(VAR_Z_23_1, received('plus', 0, VAR_Z_23_1), ['false', 'true'])])
step(name('plus'), clause(7), {}, [])
step(findall(VAR_Z_23_1, received('plus', 0, VAR_Z_23_1), ['false', 'true']), 'collected', {}, [])
step(teleported('plus', 1, ['false', 'true']), clause(37), {'S': 'plus', 'M': 1, 'Received': ['false', 'true'], 'Z': VAR_Z_23_1}, [name('plus'), outcome(1), findall(VAR_Z_23_1, received('plus', 1, VAR_Z_23_1), ['false', 'true'])])
step(findall(VAR_Z_23_1, received('plus', 1, VAR_Z_23_1), ['false', 'true']), 'collected', {}, [])
step(teleported('plus', 2, ['false', 'true']), clause(37), {'S': 'plus', 'M': 2, 'Received': ['false', 'true'], 'Z': VAR_Z_23_1}, [name('plus'), outcome(2), findall(VAR_Z_23_1, received('plus', 2, VAR_Z_23_1), ['false', 'true'])])
step(findall(VAR_Z_23_1, received('plus', 2, VAR_Z_23_1), ['false', 'true']), 'collected', {}, [])
step(teleported('plus', 3, ['false', 'true']), clause(37), {'S': 'plus', 'M': 3, 'Received': ['false', 'true'], 'Z': VAR_Z_23_1}, [name('plus'), outcome(3), findall(VAR_Z_23_1, received('plus', 3, VAR_Z_23_1), ['false', 'true'])])
step(findall(VAR_Z_23_1, received('plus', 3, VAR_Z_23_1), ['false', 'true']), 'collected', {}, [])
