wolf_goat_cabbage_verified(7)
shortest_crossing(['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'])
shortest_crossing(['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat'])

clause(1, fact(solution(['e', 'e', 'e', 'e'], [])))
clause(2, backward(solution(State, [Move, *Rest]), move(State, Move, Next), safe(Next), solution(Next, Rest)))
clause(3, backward(move([X, X, Goat, Cabbage], 'wolf', [Y, Y, Goat, Cabbage]), change(X, Y)))
clause(4, backward(move([X, Wolf, X, Cabbage], 'goat', [Y, Wolf, Y, Cabbage]), change(X, Y)))
clause(5, backward(move([X, Wolf, Goat, X], 'cabbage', [Y, Wolf, Goat, Y]), change(X, Y)))
clause(6, backward(move([X, Wolf, Goat, Cabbage], 'nothing', [Y, Wolf, Goat, Cabbage]), change(X, Y)))
clause(7, fact(change('e', 'w')))
clause(8, fact(change('w', 'e')))
clause(9, backward(safe([Farmer, Wolf, Goat, Cabbage]), one_eq(Farmer, Goat, Wolf), one_eq(Farmer, Goat, Cabbage)))
clause(10, fact(one_eq(X, X, __anon0)))
clause(11, fact(one_eq(X, __anon1, X)))
clause(12, fact(moves(0, [])))
clause(13, backward(moves(N, [__anon2, *Rest]), N > 0, is_(M, N - 1), moves(M, Rest)))
clause(17, backward(wolf_goat_cabbage_verified(7), ~'shorter_solution', moves(7, Plan), once(solution(['w', 'w', 'w', 'w'], Plan))))
clause(18, backward(shortest_crossing(Plan), ~'shorter_solution', moves(7, Plan), solution(['w', 'w', 'w', 'w'], Plan)))

step(wolf_goat_cabbage_verified(7), rule(17), {'Plan': ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']}, [~'shorter_solution', moves(7, ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), once(solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']))])
step(~'shorter_solution', 'absent', {}, [])
step(moves(7, ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(13), {'N': 7, '__anon2': 'goat', 'Rest': ['nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'], 'M': 6}, [7 > 0, is_(6, 7 - 1), moves(6, ['nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'])])
step(7 > 0, 'builtin', {}, [])
step(is_(6, 7 - 1), 'builtin', {}, [])
step(moves(6, ['nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(13), {'N': 6, '__anon2': 'nothing', 'Rest': ['wolf', 'goat', 'cabbage', 'nothing', 'goat'], 'M': 5}, [6 > 0, is_(5, 6 - 1), moves(5, ['wolf', 'goat', 'cabbage', 'nothing', 'goat'])])
step(6 > 0, 'builtin', {}, [])
step(is_(5, 6 - 1), 'builtin', {}, [])
step(moves(5, ['wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(13), {'N': 5, '__anon2': 'wolf', 'Rest': ['goat', 'cabbage', 'nothing', 'goat'], 'M': 4}, [5 > 0, is_(4, 5 - 1), moves(4, ['goat', 'cabbage', 'nothing', 'goat'])])
step(5 > 0, 'builtin', {}, [])
step(is_(4, 5 - 1), 'builtin', {}, [])
step(moves(4, ['goat', 'cabbage', 'nothing', 'goat']), rule(13), {'N': 4, '__anon2': 'goat', 'Rest': ['cabbage', 'nothing', 'goat'], 'M': 3}, [4 > 0, is_(3, 4 - 1), moves(3, ['cabbage', 'nothing', 'goat'])])
step(4 > 0, 'builtin', {}, [])
step(is_(3, 4 - 1), 'builtin', {}, [])
step(moves(3, ['cabbage', 'nothing', 'goat']), rule(13), {'N': 3, '__anon2': 'cabbage', 'Rest': ['nothing', 'goat'], 'M': 2}, [3 > 0, is_(2, 3 - 1), moves(2, ['nothing', 'goat'])])
step(3 > 0, 'builtin', {}, [])
step(is_(2, 3 - 1), 'builtin', {}, [])
step(moves(2, ['nothing', 'goat']), rule(13), {'N': 2, '__anon2': 'nothing', 'Rest': ['goat'], 'M': 1}, [2 > 0, is_(1, 2 - 1), moves(1, ['goat'])])
step(2 > 0, 'builtin', {}, [])
step(is_(1, 2 - 1), 'builtin', {}, [])
step(moves(1, ['goat']), rule(13), {'N': 1, '__anon2': 'goat', 'Rest': [], 'M': 0}, [1 > 0, is_(0, 1 - 1), moves(0, [])])
step(1 > 0, 'builtin', {}, [])
step(is_(0, 1 - 1), 'builtin', {}, [])
step(moves(0, []), fact(12), {}, [])
step(once(solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'])), 'control', {}, [solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'])])
step(solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(2), {'State': ['w', 'w', 'w', 'w'], 'Move': 'goat', 'Rest': ['nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'], 'Next': ['e', 'w', 'e', 'w']}, [move(['w', 'w', 'w', 'w'], 'goat', ['e', 'w', 'e', 'w']), safe(['e', 'w', 'e', 'w']), solution(['e', 'w', 'e', 'w'], ['nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'])])
step(move(['w', 'w', 'w', 'w'], 'goat', ['e', 'w', 'e', 'w']), rule(4), {'X': 'w', 'Wolf': 'w', 'Cabbage': 'w', 'Y': 'e'}, [change('w', 'e')])
step(change('w', 'e'), fact(8), {}, [])
step(safe(['e', 'w', 'e', 'w']), rule(9), {'Farmer': 'e', 'Wolf': 'w', 'Goat': 'e', 'Cabbage': 'w'}, [one_eq('e', 'e', 'w'), one_eq('e', 'e', 'w')])
step(one_eq('e', 'e', 'w'), fact(10), {'X': 'e', '__anon0': 'w'}, [])
step(solution(['e', 'w', 'e', 'w'], ['nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(2), {'State': ['e', 'w', 'e', 'w'], 'Move': 'nothing', 'Rest': ['wolf', 'goat', 'cabbage', 'nothing', 'goat'], 'Next': ['w', 'w', 'e', 'w']}, [move(['e', 'w', 'e', 'w'], 'nothing', ['w', 'w', 'e', 'w']), safe(['w', 'w', 'e', 'w']), solution(['w', 'w', 'e', 'w'], ['wolf', 'goat', 'cabbage', 'nothing', 'goat'])])
step(move(['e', 'w', 'e', 'w'], 'nothing', ['w', 'w', 'e', 'w']), rule(6), {'X': 'e', 'Wolf': 'w', 'Goat': 'e', 'Cabbage': 'w', 'Y': 'w'}, [change('e', 'w')])
step(change('e', 'w'), fact(7), {}, [])
step(safe(['w', 'w', 'e', 'w']), rule(9), {'Farmer': 'w', 'Wolf': 'w', 'Goat': 'e', 'Cabbage': 'w'}, [one_eq('w', 'e', 'w'), one_eq('w', 'e', 'w')])
step(one_eq('w', 'e', 'w'), fact(11), {'X': 'w', '__anon1': 'e'}, [])
step(solution(['w', 'w', 'e', 'w'], ['wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(2), {'State': ['w', 'w', 'e', 'w'], 'Move': 'wolf', 'Rest': ['goat', 'cabbage', 'nothing', 'goat'], 'Next': ['e', 'e', 'e', 'w']}, [move(['w', 'w', 'e', 'w'], 'wolf', ['e', 'e', 'e', 'w']), safe(['e', 'e', 'e', 'w']), solution(['e', 'e', 'e', 'w'], ['goat', 'cabbage', 'nothing', 'goat'])])
step(move(['w', 'w', 'e', 'w'], 'wolf', ['e', 'e', 'e', 'w']), rule(3), {'X': 'w', 'Goat': 'e', 'Cabbage': 'w', 'Y': 'e'}, [change('w', 'e')])
step(safe(['e', 'e', 'e', 'w']), rule(9), {'Farmer': 'e', 'Wolf': 'e', 'Goat': 'e', 'Cabbage': 'w'}, [one_eq('e', 'e', 'e'), one_eq('e', 'e', 'w')])
step(one_eq('e', 'e', 'e'), fact(10), {'X': 'e', '__anon0': 'e'}, [])
step(solution(['e', 'e', 'e', 'w'], ['goat', 'cabbage', 'nothing', 'goat']), rule(2), {'State': ['e', 'e', 'e', 'w'], 'Move': 'goat', 'Rest': ['cabbage', 'nothing', 'goat'], 'Next': ['w', 'e', 'w', 'w']}, [move(['e', 'e', 'e', 'w'], 'goat', ['w', 'e', 'w', 'w']), safe(['w', 'e', 'w', 'w']), solution(['w', 'e', 'w', 'w'], ['cabbage', 'nothing', 'goat'])])
step(move(['e', 'e', 'e', 'w'], 'goat', ['w', 'e', 'w', 'w']), rule(4), {'X': 'e', 'Wolf': 'e', 'Cabbage': 'w', 'Y': 'w'}, [change('e', 'w')])
step(safe(['w', 'e', 'w', 'w']), rule(9), {'Farmer': 'w', 'Wolf': 'e', 'Goat': 'w', 'Cabbage': 'w'}, [one_eq('w', 'w', 'e'), one_eq('w', 'w', 'w')])
step(one_eq('w', 'w', 'e'), fact(10), {'X': 'w', '__anon0': 'e'}, [])
step(one_eq('w', 'w', 'w'), fact(10), {'X': 'w', '__anon0': 'w'}, [])
step(solution(['w', 'e', 'w', 'w'], ['cabbage', 'nothing', 'goat']), rule(2), {'State': ['w', 'e', 'w', 'w'], 'Move': 'cabbage', 'Rest': ['nothing', 'goat'], 'Next': ['e', 'e', 'w', 'e']}, [move(['w', 'e', 'w', 'w'], 'cabbage', ['e', 'e', 'w', 'e']), safe(['e', 'e', 'w', 'e']), solution(['e', 'e', 'w', 'e'], ['nothing', 'goat'])])
step(move(['w', 'e', 'w', 'w'], 'cabbage', ['e', 'e', 'w', 'e']), rule(5), {'X': 'w', 'Wolf': 'e', 'Goat': 'w', 'Y': 'e'}, [change('w', 'e')])
step(safe(['e', 'e', 'w', 'e']), rule(9), {'Farmer': 'e', 'Wolf': 'e', 'Goat': 'w', 'Cabbage': 'e'}, [one_eq('e', 'w', 'e'), one_eq('e', 'w', 'e')])
step(one_eq('e', 'w', 'e'), fact(11), {'X': 'e', '__anon1': 'w'}, [])
step(solution(['e', 'e', 'w', 'e'], ['nothing', 'goat']), rule(2), {'State': ['e', 'e', 'w', 'e'], 'Move': 'nothing', 'Rest': ['goat'], 'Next': ['w', 'e', 'w', 'e']}, [move(['e', 'e', 'w', 'e'], 'nothing', ['w', 'e', 'w', 'e']), safe(['w', 'e', 'w', 'e']), solution(['w', 'e', 'w', 'e'], ['goat'])])
step(move(['e', 'e', 'w', 'e'], 'nothing', ['w', 'e', 'w', 'e']), rule(6), {'X': 'e', 'Wolf': 'e', 'Goat': 'w', 'Cabbage': 'e', 'Y': 'w'}, [change('e', 'w')])
step(safe(['w', 'e', 'w', 'e']), rule(9), {'Farmer': 'w', 'Wolf': 'e', 'Goat': 'w', 'Cabbage': 'e'}, [one_eq('w', 'w', 'e'), one_eq('w', 'w', 'e')])
step(solution(['w', 'e', 'w', 'e'], ['goat']), rule(2), {'State': ['w', 'e', 'w', 'e'], 'Move': 'goat', 'Rest': [], 'Next': ['e', 'e', 'e', 'e']}, [move(['w', 'e', 'w', 'e'], 'goat', ['e', 'e', 'e', 'e']), safe(['e', 'e', 'e', 'e']), solution(['e', 'e', 'e', 'e'], [])])
step(move(['w', 'e', 'w', 'e'], 'goat', ['e', 'e', 'e', 'e']), rule(4), {'X': 'w', 'Wolf': 'e', 'Cabbage': 'e', 'Y': 'e'}, [change('w', 'e')])
step(safe(['e', 'e', 'e', 'e']), rule(9), {'Farmer': 'e', 'Wolf': 'e', 'Goat': 'e', 'Cabbage': 'e'}, [one_eq('e', 'e', 'e'), one_eq('e', 'e', 'e')])
step(solution(['e', 'e', 'e', 'e'], []), fact(1), {}, [])
step(shortest_crossing(['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), rule(18), {'Plan': ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']}, [~'shorter_solution', moves(7, ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat']), solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'wolf', 'goat', 'cabbage', 'nothing', 'goat'])])
step(shortest_crossing(['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(18), {'Plan': ['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']}, [~'shorter_solution', moves(7, ['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']), solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat'])])
step(moves(7, ['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(13), {'N': 7, '__anon2': 'goat', 'Rest': ['nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat'], 'M': 6}, [7 > 0, is_(6, 7 - 1), moves(6, ['nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat'])])
step(moves(6, ['nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(13), {'N': 6, '__anon2': 'nothing', 'Rest': ['cabbage', 'goat', 'wolf', 'nothing', 'goat'], 'M': 5}, [6 > 0, is_(5, 6 - 1), moves(5, ['cabbage', 'goat', 'wolf', 'nothing', 'goat'])])
step(moves(5, ['cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(13), {'N': 5, '__anon2': 'cabbage', 'Rest': ['goat', 'wolf', 'nothing', 'goat'], 'M': 4}, [5 > 0, is_(4, 5 - 1), moves(4, ['goat', 'wolf', 'nothing', 'goat'])])
step(moves(4, ['goat', 'wolf', 'nothing', 'goat']), rule(13), {'N': 4, '__anon2': 'goat', 'Rest': ['wolf', 'nothing', 'goat'], 'M': 3}, [4 > 0, is_(3, 4 - 1), moves(3, ['wolf', 'nothing', 'goat'])])
step(moves(3, ['wolf', 'nothing', 'goat']), rule(13), {'N': 3, '__anon2': 'wolf', 'Rest': ['nothing', 'goat'], 'M': 2}, [3 > 0, is_(2, 3 - 1), moves(2, ['nothing', 'goat'])])
step(solution(['w', 'w', 'w', 'w'], ['goat', 'nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(2), {'State': ['w', 'w', 'w', 'w'], 'Move': 'goat', 'Rest': ['nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat'], 'Next': ['e', 'w', 'e', 'w']}, [move(['w', 'w', 'w', 'w'], 'goat', ['e', 'w', 'e', 'w']), safe(['e', 'w', 'e', 'w']), solution(['e', 'w', 'e', 'w'], ['nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat'])])
step(solution(['e', 'w', 'e', 'w'], ['nothing', 'cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(2), {'State': ['e', 'w', 'e', 'w'], 'Move': 'nothing', 'Rest': ['cabbage', 'goat', 'wolf', 'nothing', 'goat'], 'Next': ['w', 'w', 'e', 'w']}, [move(['e', 'w', 'e', 'w'], 'nothing', ['w', 'w', 'e', 'w']), safe(['w', 'w', 'e', 'w']), solution(['w', 'w', 'e', 'w'], ['cabbage', 'goat', 'wolf', 'nothing', 'goat'])])
step(solution(['w', 'w', 'e', 'w'], ['cabbage', 'goat', 'wolf', 'nothing', 'goat']), rule(2), {'State': ['w', 'w', 'e', 'w'], 'Move': 'cabbage', 'Rest': ['goat', 'wolf', 'nothing', 'goat'], 'Next': ['e', 'w', 'e', 'e']}, [move(['w', 'w', 'e', 'w'], 'cabbage', ['e', 'w', 'e', 'e']), safe(['e', 'w', 'e', 'e']), solution(['e', 'w', 'e', 'e'], ['goat', 'wolf', 'nothing', 'goat'])])
step(move(['w', 'w', 'e', 'w'], 'cabbage', ['e', 'w', 'e', 'e']), rule(5), {'X': 'w', 'Wolf': 'w', 'Goat': 'e', 'Y': 'e'}, [change('w', 'e')])
step(safe(['e', 'w', 'e', 'e']), rule(9), {'Farmer': 'e', 'Wolf': 'w', 'Goat': 'e', 'Cabbage': 'e'}, [one_eq('e', 'e', 'w'), one_eq('e', 'e', 'e')])
step(solution(['e', 'w', 'e', 'e'], ['goat', 'wolf', 'nothing', 'goat']), rule(2), {'State': ['e', 'w', 'e', 'e'], 'Move': 'goat', 'Rest': ['wolf', 'nothing', 'goat'], 'Next': ['w', 'w', 'w', 'e']}, [move(['e', 'w', 'e', 'e'], 'goat', ['w', 'w', 'w', 'e']), safe(['w', 'w', 'w', 'e']), solution(['w', 'w', 'w', 'e'], ['wolf', 'nothing', 'goat'])])
step(move(['e', 'w', 'e', 'e'], 'goat', ['w', 'w', 'w', 'e']), rule(4), {'X': 'e', 'Wolf': 'w', 'Cabbage': 'e', 'Y': 'w'}, [change('e', 'w')])
step(safe(['w', 'w', 'w', 'e']), rule(9), {'Farmer': 'w', 'Wolf': 'w', 'Goat': 'w', 'Cabbage': 'e'}, [one_eq('w', 'w', 'w'), one_eq('w', 'w', 'e')])
step(solution(['w', 'w', 'w', 'e'], ['wolf', 'nothing', 'goat']), rule(2), {'State': ['w', 'w', 'w', 'e'], 'Move': 'wolf', 'Rest': ['nothing', 'goat'], 'Next': ['e', 'e', 'w', 'e']}, [move(['w', 'w', 'w', 'e'], 'wolf', ['e', 'e', 'w', 'e']), safe(['e', 'e', 'w', 'e']), solution(['e', 'e', 'w', 'e'], ['nothing', 'goat'])])
step(move(['w', 'w', 'w', 'e'], 'wolf', ['e', 'e', 'w', 'e']), rule(3), {'X': 'w', 'Goat': 'w', 'Cabbage': 'e', 'Y': 'e'}, [change('w', 'e')])
