condition('C1', 'resolution', 'ok', 14)
condition('C2', 'well_founded', 'ok', 25)
condition('C3', 'justification', 'ok', 25)
condition('C4', 'coverage', 'ok', 29)
condition('C5', 're_decision', 'ok', 10)
condition('C6', 'boundary_consistency', 'ok', 1)
condition('C7', 'relevance', 'ok', 28)
obligation('collected', 'theory_scoped', findall(A, weight(B, A), [18000, 14250, 4950]))
steps(25)
verified(14)
recomputed(10)
composed(0)
trusted(1)
claims(3)
verdict('checked_with_obligations')
