condition('C1', 'resolution', 'ok', 9)
condition('C2', 'well_founded', 'ok', 21)
condition('C3', 'justification', 'ok', 21)
condition('C4', 'coverage', 'ok', 21)
condition('C5', 're_decision', 'ok', 12)
condition('C6', 'boundary_consistency', 'ok', 0)
condition('C7', 'relevance', 'ok', 23)
steps(21)
verified(9)
recomputed(12)
composed(0)
trusted(0)
claims(2)
verdict('checked')
