condition('C1', 'resolution', 'ok', 506)
condition('C2', 'well_founded', 'ok', 913)
condition('C3', 'justification', 'ok', 913)
condition('C4', 'coverage', 'ok', 1478)
condition('C5', 're_decision', 'ok', 372)
condition('C6', 'boundary_consistency', 'ok', 35)
condition('C7', 'relevance', 'ok', 937)
obligation('absent', 'theory_scoped', ~has_factor(5, 3))
obligation('absent', 'theory_scoped', ~has_factor(13, 3))
obligation('absent', 'theory_scoped', ~has_factor(29, 3))
obligation('absent', 'theory_scoped', ~has_factor(61, 3))
obligation('absent', 'theory_scoped', ~has_factor(7, 3))
obligation('absent', 'theory_scoped', ~has_factor(11, 3))
obligation('absent', 'theory_scoped', ~has_factor(17, 3))
obligation('absent', 'theory_scoped', ~has_factor(19, 3))
obligation('absent', 'theory_scoped', ~has_factor(109, 3))
obligation('absent', 'theory_scoped', ~has_factor(251, 3))
obligation('absent', 'theory_scoped', ~has_factor(509, 3))
obligation('absent', 'theory_scoped', ~has_factor(1021, 3))
obligation('absent', 'theory_scoped', ~has_factor(2029, 3))
obligation('absent', 'theory_scoped', ~has_factor(4093, 3))
obligation('absent', 'theory_scoped', ~has_factor(8179, 3))
obligation('absent', 'theory_scoped', ~has_factor(16381, 3))
obligation('absent', 'theory_scoped', ~has_factor(32749, 3))
obligation('absent', 'theory_scoped', ~has_factor(65519, 3))
obligation('absent', 'theory_scoped', ~has_factor(131059, 3))
obligation('absent', 'theory_scoped', ~has_factor(262139, 3))
obligation('absent', 'theory_scoped', ~has_factor(524269, 3))
obligation('absent', 'theory_scoped', ~has_factor(1048573, 3))
obligation('absent', 'theory_scoped', ~has_factor(2097133, 3))
obligation('absent', 'theory_scoped', ~has_factor(4194301, 3))
obligation('absent', 'theory_scoped', ~has_factor(23, 3))
obligation('absent', 'theory_scoped', ~has_factor(31, 3))
obligation('absent', 'theory_scoped', ~has_factor(37, 3))
obligation('absent', 'theory_scoped', ~has_factor(8388571, 3))
obligation('absent', 'theory_scoped', ~has_factor(16777213, 3))
obligation('absent', 'theory_scoped', ~has_factor(41, 3))
obligation('absent', 'theory_scoped', ~has_factor(43, 3))
obligation('absent', 'theory_scoped', ~has_factor(47, 3))
obligation('absent', 'theory_scoped', ~has_factor(53, 3))
obligation('absent', 'theory_scoped', ~has_factor(59, 3))
obligation('absent', 'theory_scoped', ~has_factor(33554371, 3))
steps(913)
verified(506)
recomputed(333)
composed(39)
trusted(35)
claims(24)
verdict('checked_with_obligations')
