condition('C1', 'resolution', 'ok', 8)
condition('C2', 'well_founded', 'ok', 10)
condition('C3', 'justification', 'ok', 10)
condition('C4', 'coverage', 'ok', 12)
condition('C5', 're_decision', 'ok', 0)
condition('C6', 'boundary_consistency', 'ok', 2)
condition('C7', 'relevance', 'ok', 14)
obligation('absent', 'theory_scoped', ~t('carol', 'blocked', 'true'))
obligation('collected', 'theory_scoped', findall(A, t(A, 'child_of', 'alice'), ['bob', 'carol']))
steps(10)
verified(8)
recomputed(0)
composed(0)
trusted(2)
claims(4)
verdict('checked_with_obligations')
