condition('C1', 'resolution', 'ok', 5)
condition('C2', 'well_founded', 'ok', 9)
condition('C3', 'justification', 'ok', 9)
condition('C4', 'coverage', 'ok', 9)
condition('C5', 're_decision', 'ok', 3)
condition('C6', 'boundary_consistency', 'ok', 1)
condition('C7', 'relevance', 'ok', 10)
obligation('collected', 'theory_scoped', findall(A, line_total(B, A), [6, 12, 10]))
steps(9)
verified(5)
recomputed(3)
composed(0)
trusted(1)
claims(1)
verdict('checked_with_obligations')
