condition('C1', 'resolution', 'ok', 1)
condition('C2', 'well_founded', 'ok', 2)
condition('C3', 'justification', 'ok', 2)
condition('C4', 'coverage', 'ok', 2)
condition('C5', 're_decision', 'ok', 0)
condition('C6', 'boundary_consistency', 'ok', 1)
condition('C7', 'relevance', 'ok', 3)
obligation('absent', 'theory_scoped', ~'counterexample')
steps(2)
verified(1)
recomputed(0)
composed(0)
trusted(1)
claims(1)
verdict('checked_with_obligations')
