condition('C1', 'resolution', 'ok', 185)
condition('C2', 'well_founded', 'ok', 218)
condition('C3', 'justification', 'ok', 218)
condition('C4', 'coverage', 'ok', 419)
condition('C5', 're_decision', 'ok', 33)
condition('C6', 'boundary_consistency', 'ok', 0)
condition('C7', 'relevance', 'ok', 242)
steps(218)
verified(185)
recomputed(33)
composed(0)
trusted(0)
claims(24)
verdict('checked')
