condition('C1', 'resolution', 'ok', 11)
condition('C2', 'well_founded', 'ok', 13)
condition('C3', 'justification', 'ok', 13)
condition('C4', 'coverage', 'ok', 15)
condition('C5', 're_decision', 'ok', 0)
condition('C6', 'boundary_consistency', 'ok', 2)
condition('C7', 'relevance', 'ok', 16)
obligation('absent', 'theory_scoped', ~suspended('alice'))
obligation('absent', 'theory_scoped', ~suspended('bob'))
steps(13)
verified(11)
recomputed(0)
composed(0)
trusted(2)
claims(3)
verdict('checked_with_obligations')
