condition('C1', 'resolution', 'ok', 32)
condition('C2', 'well_founded', 'ok', 57)
condition('C3', 'justification', 'ok', 57)
condition('C4', 'coverage', 'ok', 69)
condition('C5', 're_decision', 'ok', 18)
condition('C6', 'boundary_consistency', 'ok', 7)
condition('C7', 'relevance', 'ok', 61)
obligation('absent', 'theory_scoped', ~has_notice('c1'))
obligation('absent', 'theory_scoped', ~safeguard('c1', 'inform'))
obligation('collected', 'theory_scoped', findall(A, higher(100, A), []))
obligation('collected', 'theory_scoped', findall(A, higher(85, A), [100, 97]))
obligation('collected', 'theory_scoped', findall(A, higher(70, A), [100, 85, 97]))
obligation('absent', 'theory_scoped', ~safeguard('c3', 'consent'))
obligation('collected', 'theory_scoped', findall(A, higher(97, A), [100]))
steps(57)
verified(32)
recomputed(18)
composed(0)
trusted(7)
claims(4)
verdict('checked_with_obligations')
