condition('C1', 'resolution', 'ok', 225)
condition('C2', 'well_founded', 'ok', 273)
condition('C3', 'justification', 'ok', 273)
condition('C4', 'coverage', 'ok', 474)
condition('C5', 're_decision', 'ok', 15)
condition('C6', 'boundary_consistency', 'ok', 30)
condition('C7', 'relevance', 'ok', 310)
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r6', 'ex:research', A), []))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r6', 'ex:noTransferUS', A), []))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, permitted('ex:r2', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r2', A), []))
obligation('collected', 'theory_scoped', findall(A, governs(B, 'ex:r2') & t(B, 'odrl:permission', C) & unmet('ex:r2', C, A), [unmet('ex:forResearch', 'odrl:purpose', 'dpv:PersonalisedAdvertising', 'odrl:isA', 'dpv:ResearchAndDevelopment'), unmet('ex:underConsent', 'ex:legalBasis', 'dpv:LegitimateInterest', 'odrl:eq', 'dpv:Consent'), unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentUnknown', 'odrl:eq', 'dpv:ConsentGiven')]))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r3', 'ex:noMarketing', A), []))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, permitted('ex:r4', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r4', A), []))
obligation('collected', 'theory_scoped', findall(A, governs(B, 'ex:r4') & t(B, 'odrl:permission', C) & unmet('ex:r4', C, A), [unmet('ex:consentGiven', 'ex:consentStatus', 'dpv:ConsentWithdrawn', 'odrl:eq', 'dpv:ConsentGiven')]))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, permitted('ex:r5', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r5', A), []))
obligation('collected', 'theory_scoped', findall(A, governs(B, 'ex:r5') & t(B, 'odrl:permission', C) & unmet('ex:r5', C, A), [unmet('ex:pseudonymised', 'ex:technicalMeasure', 'dpv:Encryption', 'odrl:eq', 'dpv:Pseudonymisation'), unmet('ex:before2027', 'odrl:dateTime', 20270301, 'odrl:lt', 20270101)]))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, candidate('ex:r11', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r11', A), []))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r10', 'ex:research', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r10', A), []))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r1', 'ex:research', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r1', A), []))
obligation('collected', 'theory_scoped', findall(A, t('ex:policy', 'odrl:conflict', A), ['odrl:prohibit']))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r7', 'ex:research', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r7', A), []))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r8', 'ex:research', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r8', A), []))
obligation('collected', 'theory_scoped', findall(A, unmet('ex:r9', 'ex:research', A), []))
obligation('collected', 'theory_scoped', findall(A, prohibited('ex:r9', A), []))
steps(273)
verified(225)
recomputed(15)
composed(0)
trusted(33)
claims(37)
verdict('checked_with_obligations')
