condition('C1', 'resolution', 'ok', 7)
condition('C2', 'well_founded', 'ok', 10)
condition('C3', 'justification', 'ok', 10)
condition('C4', 'coverage', 'ok', 10)
condition('C5', 're_decision', 'ok', 2)
condition('C6', 'boundary_consistency', 'ok', 1)
condition('C7', 'relevance', 'ok', 11)
obligation('absent', 'theory_scoped', ~cheaper('a', 'd', 6))
steps(10)
verified(7)
recomputed(2)
composed(0)
trusted(1)
claims(1)
verdict('checked_with_obligations')
