condition('C1', 'resolution', 'ok', 56)
condition('C2', 'well_founded', 'ok', 72)
condition('C3', 'justification', 'ok', 72)
condition('C4', 'coverage', 'ok', 113)
condition('C5', 're_decision', 'ok', 15)
condition('C6', 'boundary_consistency', 'ok', 1)
condition('C7', 'relevance', 'ok', 75)
obligation('absent', 'theory_scoped', ~'shorter_solution')
steps(72)
verified(56)
recomputed(14)
composed(1)
trusted(1)
claims(3)
verdict('checked_with_obligations')
